### ISSUE TITLE
CodeGPT missing license

### ISSUE THREAD

**Issue by hughesthe1st** [davila7/code-gpt-docs#1]
The project overview mentions that this is an open source project, however it is unclear what the license is. It looks like the extension is using an MIT license [per the listing in Visual Studio Marketplace](https://marketplace.visualstudio.com/items/DanielSanMedium.dscodegpt/license) - it would be good to clarify this in the docs.

**Comment by davila7** [comment]
The license has already been updated.

https://github.com/davila7/code-gpt-docs/blob/main/LICENSE.md
