### ISSUE TITLE
Return a "undefined" file

### ISSUE THREAD

**Issue by syhwawa** [davila7/code-gpt-docs#10]
Hi, this is awesome extesntion but it seems doesn't work for me. Not sure where did I something wrong.  

After setting my API key, all responses are by creating a "undefined" file and it says"Ops! Account problems. More information in the VSCode notification error."

**Comment by davila7** [comment]
In the version that is updated today, you will be able to see the error that the OpenAI API sends directly in the message, and in this way, you will be able to solve it.
The new version is 1.0.10

**Comment by davila7** [comment]
@syhwawa 
The new version is now available so you can see the message that comes from the OpenAI API

**Comment by davila7** [comment]
Fixed in version 1.0.12

**Comment by syhwawa** [comment]
Hi @davila7,  thanks for tracking the problem. when I installed the latest version 1.0.12, it still created a "undefined" file and gave me an error saying "Error: TypeError: Cannot read properties of undefined (reading 'data')"

**Comment by davila7** [comment]
What language are you using?
You could write the comment you are making and the file extension.

**Comment by syhwawa** [comment]
Hi, @davila7 I am using Python. When I open a `.py` file and selected some content writing in Python and choose Explain Code GPT, it give an error says "Error: TypeError: Cannot read properties of undefined (reading 'data')".
