### ISSUE TITLE
New line as "\n" instead a new line.

### ISSUE THREAD

**Issue by PePeLeGal** [davila7/code-gpt-docs#100]
Sometimes, the chat response shows a "\n" instead a new line, as bellow:

const delay = 5000;\n\nconst countView = () => {
    const l = document.location;
    const href = l.href;
    const origin = l.origin;
    const uri = href.substring(origin.length);
    const ads = [];

    for (const e of document.querySelectorAll("a.cca")) {
        const img = e.querySelector("img:first-child");
        const pos = e.dataset.pos;
        const adv = e.dataset.adv;

        if (img?.visible && img.complete) {
            ads.push({ "pos": pos, "adv": adv });
        }
    }

    if (ads.length > 0) {
        fetch("/ajax/view_listener", { 
            method: "POST", 
            body: JSON.stringify({ "uri": uri, "ads": ads })\n        })
        .then((response) => response.json())
        .then((data) => {
            console.log("Success: " + data.success + ", Message: " + data.message);
        });
    }
};

setTimeout(countView, delay);

**Comment by davila7** [comment]
Working on this
