### ISSUE TITLE
GPT4 not working

### ISSUE THREAD

**Issue by Fowlplaychiken** [davila7/code-gpt-docs#102]
Type: <b>Bug</b>

CodeGPT says it supports GPT4, and I pay for API access via GPT so have GPT4, despite this it does not seem to work and has a 4000 token limit instead of 8000

Extension version: 2.1.3
VS Code version: Code 1.77.0 (7f329fe6c66b0f86ae1574c2911b681ad5a45d63, 2023-03-29T10:02:16.981Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz (16 x 3792)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.91GB (19.98GB free)|
|Process Argv|--crash-reporter-id 8fac4efa-43dd-41cd-80ac-1fbb7fa14e26|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30672706
vsccsb:30677849
pythonb192cf:30669361
defaultazurewalk:30687958
pythonms35:30701012

```

</details>

**Comment by jtbg** [comment]
Do you have access to [the GPT4 API?](https://openai.com/waitlist/gpt-4-api)? It is still in limited rollout via waitlist, so feel free to apply for it if you don't have access yet.

While GPT-Plus (OpenAI's paid plan) allows you to try out GPT-4 through the ChatGPT interface, it doesn't include access to the GPT-4 API.

**Comment by Fowlplaychiken** [comment]
Thanks, figured this out. Bummer!! A lot of tasks will need GPT4 at best, if not 4-32. Signed up for access, fingers crossed!
