### ISSUE TITLE
Feature: add option to export a chat

### ISSUE THREAD

**Issue by AndiLeni** [davila7/code-gpt-docs#103]
Feature request: export chat (as text, markdown, pdf, ...)

**Comment by GigaVik** [comment]
Another would be a chat history feature. I just cleared the chat in which I talked with the bot for half a day ....

**Comment by PilarHidalgo** [comment]
I understand you're interested in a feature to export a chat. As of the current version of CodeGPT, there isn't a direct feature to export a chat. However, you can manually copy the chat history. If you're interested in this feature being added, I recommend providing this feedback directly to the CodeGPT team. They're always looking for ways to improve the platform based on user feedback.
