### ISSUE TITLE
 Error 429 on code gpt even though works in chat browser

### ISSUE THREAD

**Issue by Saad-Alareqi** [davila7/code-gpt-docs#110]
Hi,
i get this error:
OpenAI: API Response was: Error 429: You exceeded your current quota, please check your plan and billing details.

i checked my quota in settings on my account and i only used 0.12$ from 18$ of free plan. also tried using gpt in chat.openai.com/chat and it works fine and there is no limitation. so there might be an error with the extension?

**Comment by davila7** [comment]
@Saad-Alareqi 

please check if the expiration date of your credits has not expired.

**Comment by gordondm** [comment]
same here: I am getting the error 429 in VSCode, but the browser works fine.
<img width="333" alt="image" src="https://user-images.githubusercontent.com/4449540/235363958-f1dd0b49-910b-48c3-bf11-bb28c07de3db.png">

**Comment by gabrielbull** [comment]
Same here. I have the paid version of ChatGPT too so it looks like it is not using the correct API Key.

**Comment by maycomayco** [comment]
What version of VSCode are you using?

**Comment by maycomayco** [comment]
> The problem is solved, but I am confused now. there are two ways to pay for your subscription:
> 
> 1. $20 for ChatGPT Plus Subscription, at pay.openai.com
>    it gives you access to chatGPT4 in the browser, but I was getting the error 429 in VSCode
> 2. in openai billing page platform.openai.com/account/billing
>    it enables VSCode to access chaGRP with the API key.
> 
> Even though I paid #1 for ChatGPT Plus Subscription, I had to enable a payment plan at #2 in order to use it with VSCode.

So, could you use the CodeGPT extension only if you put your Credit Card data in your openAI account?

**Comment by gordondm** [comment]
I don't know, my ChatGPT Plus Subscription didn't expire yet

**Comment by krb3d** [comment]
> same here: I am getting the error 429 in VSCode, but the browser works fine. <img alt="image" width="333" src="https://user-images.githubusercontent.com/4449540/235363958-f1dd0b49-910b-48c3-bf11-bb28c07de3db.png">

same for me

**Comment by nomocas** [comment]
Same for me.

Even if I reset the api key, delete it and reset it, etc.

Nothing changes.

**Comment by DamirMakhmudov** [comment]
Same for me. U use free plan, and it works on chat open AI page on browser. But not in charCode extension, already updated api key, but steel have trouble

**Comment by PilarHidalgo** [comment]
Hi, the error you're encountering is related to the rate limit of your OpenAI API. This error typically occurs when the number of requests sent to the API exceeds the limit set by your current plan. Even though you have only used a small portion of your credit, the number of requests you're making might be too high.

You can check your usage details and rate limits by logging into your OpenAI account at https://openai.com/api/. If you continue to experience this issue, it might be worth considering an upgrade to a plan with a higher rate limit.
