### ISSUE TITLE
Please enter your api key, go to https://codegpt.co/ for more information.

### ISSUE THREAD

**Issue by JiYeHuanXiang** [davila7/code-gpt-docs#111]
I set it up many times and tried to add two different keys, and he would only answer me!

**Comment by davila7** [comment]
@JiYeHuanXiang 
Once you enter the API Key you must use the command: Developer: Reload Window

**Comment by WidgetWolf** [comment]
I seem to be running into the same issue. I have tried running the command, reopening vs code itself and even tried to restart the pc. Is there a way I can spot what the actual issue is? (like logs for example)

**Comment by cl0udsm1th** [comment]
Experiencing the same issue. 
I have a paid account incl. for API access. 
I am attempting to use gpt-3.5 turbo model (on waitlist for 4). 
I'm prompted my API key is saved, and I use Developer: Reload Window from command palette. 
Issue persists.

**Comment by davila7** [comment]
> I seem to be running into the same issue. I have tried running the command, reopening vs code itself and even tried to restart the pc. Is there a way I can spot what the actual issue is? (like logs for example)

try to update VSCode to the last version

**Comment by topcheese** [comment]
@gebeer It's VS Code only.  I had the same problem.

**Comment by gebeer** [comment]
> @gebeer It's VS Code only. I had the same problem.

Where you able to resolve it?

**Comment by topcheese** [comment]
@gebeer, yes and see this comment why.  https://github.com/davila7/code-gpt-docs/issues/142#issuecomment-1538751358
