### ISSUE TITLE
When downloading the program, the plugin window does not load

### ISSUE THREAD

**Issue by Treflax** [davila7/code-gpt-docs#112]
![Знімок екрана 2023-04-08 о 20 47 13](https://user-images.githubusercontent.com/93861846/230737933-7c3766af-209a-4cc4-b4bf-ab9d939ad9e2.png)

**Comment by PilarHidalgo** [comment]
I'm sorry to hear that you're having trouble with the plugin window. Let's try to troubleshoot this issue.

First, please ensure that you have the latest version of Visual Studio Code installed. You should be running version 1.85 or higher.

Next, make sure that you have Node.js version 20.0 or higher installed on your system.

Finally, check that you have the latest version of the CodeGPT extension, which is 3.2.5 or higher.

If you've checked all of these and the issue persists, consider reinstalling the extension or restarting Visual Studio Code.
