### ISSUE TITLE
No answer is generated in the new update

### ISSUE THREAD

**Issue by Zag495** [davila7/code-gpt-docs#113]
It just stop answering. No matter what you do it won't answer . The new update has produced more issues for me than fixing them . The answer section is blank /
AND when you try to ask it other than chat like writing documentation it will give you this error
"OpenAI API could not process the query, try selecting the code and using Ask CodeGPT to write your own query"

**Comment by parisChatz** [comment]
I have the same problem. Made sure I had the latest version of vscode, I uninstalled the extension and then reinstalled it. I even set a new API key. I also get this error you said above when I use "Ask CODEGPT".

**Comment by davila7** [comment]
That error occurs when you don't get any response from OpenAI.

Could you detail what type of question you are asking and what model you are using?

**Comment by DenisZackharov** [comment]
I using gpt-3.5-turbo and have a same problem
<img width="503" alt="image" src="https://user-images.githubusercontent.com/78980031/230790863-7eca8caf-024b-4021-aad4-e783d5c75977.png">

**Comment by davila7** [comment]
@DenisZackharov could you try to use Developer: Reload Window ? 

I'm trying to replicate the error but everything works correctly for me.

<img width="948" alt="Captura de Pantalla 2023-04-09 a la(s) 5 21 14 p  m" src="https://user-images.githubusercontent.com/6216945/230797071-ef047860-4b47-4435-9c50-dcb7a49db392.png">

**Comment by DenisZackharov** [comment]
@davila7, yep you are right, but i get only first response, when i try to request a new question, i get this error again(

**Comment by parisChatz** [comment]
Same as @DenisZackharov, GPT 3.5 turbo. The first thing I did was Developer: Reload Window. Then After that changed my key. Tried uninstalling and reinstalling the extension and even vs code. 

Here is the funny thing. I have a second machine on which I tried to recreate this problem and still have the same issue. Suddenly, out of the blue on my main machine, everything seems to work fine. Apparently, on the second machine, I still have this issue. I had the same, stable internet connection on both occasions. 

Could it be a problem on OpenAi's end?

**Comment by davila7** [comment]
@parisChatz 

Everything seems to be fine in OpenAI:

https://status.openai.com/

We have detected that there are times when an empty response arrives from OpenAI... no error, just an empty string.

The extension needs to display something to the user so we display an error for them to retry. For now, we will continue to review these cases so that CodeGPT resends the request a few seconds after the empty response arrived.

**Comment by davila7** [comment]
When I used ChatGPT this happened to me very often. You had to refresh the page or create a new chat to continue the conversation.

**Comment by Zag495** [comment]
I just switched back to previous version that something .3 version before this one and it is working good but it is generating the answer of my 1st question in the answer of 2nd question .It is like this :
if I ask n num of questions then it will answer upto n-1

**Comment by dkent600** [comment]
All of the same is happening to me too.

**Comment by hayusama** [comment]
same for me

**Comment by davila7** [comment]
@dkent600 @hayusama 

Could you send me an image of the error and exactly when it happens?

**Comment by hayusama** [comment]
I have exactly the same problem as Denis Zackharov


However, if I install an older version, it works.

**Comment by davila7** [comment]
@Zag495 @parisChatz @DenisZackharov @dkent600 @hayusama 

We are publishing an update (version 2.1.5) to fix the OpenAI response timeout.
With accounts that have free credits, the response time can be more than 30 seconds, but we can handle it.

**Comment by davila7** [comment]
version 2.1.5 is available

**Comment by hayusama** [comment]
Yes it's work thanks!

**Comment by PaunaRares** [comment]
3.5 turbo still not working

**Comment by dkent600** [comment]
Looks like it is working with the new update, thanks!

**Comment by Gexar** [comment]
I have the same problem, but I solved it by switching back to 2.1.3 version.

**Comment by davila7** [comment]
@Gexar 
Could you give me more information?

**Comment by cschokke** [comment]
same issue here, using gpt-3.5. When I press CMD + SHIFT + I for some function like "//validate an email with regex and comment each line", I get the error: OpenAI API could not process the query, try selecting the code and using Ask CodeGPT to write your own query. When I Ask CodeGPT, I get error: OpenAI: API Response was: Error 404: The model: gpt-4 does not exist More information about this error: https://www.codegpt.co/docs/tutorial-basics/api_errors. When I check https://platform.openai.com/account/members for my membershipt/organisation I am a member with organisation 'Personal'. My API key is created today as described at https://platform.openai.com/docs/quickstart/add-your-api-key and added to visual studio code

**Comment by rostamiani** [comment]
I tried my api key with Genie extension and I got this response: "You exceeded your current quota, please check your plan and billing details."

CodeGPT should display the error instead of an empty response

**Comment by davila7** [comment]
@rostamiani 
Thank you! working on this

**Comment by BRS3CTY** [comment]
Hi,
in 2.1.6 I have blank response, in 2.1.3 I have:
OpenAI API Response was: Error 429: You exceeded your current quota, please check your plan and billing details. More information about this error: https://www.codegpt.co/docs/tutorial-basics/api_errors

I'm on free api plan, I want to test it before buying :)

**Comment by yamkin** [comment]
Hi!
I have the same problem as https://github.com/davila7/code-gpt-docs/issues/113#issuecomment-1543471899

**Comment by willardc** [comment]
Messed around with this for hours, had the SAME EXACT ISSUES as everyone else.
- no answers
- "..write your own query" error
- something about quota/tokens or something

THIS IS WHAT WORKED FOR ME:

Check your current quota in your OpenAI account settings here: (https://beta.openai.com/account/billing/limits). 
You can see how many tokens your requests have consumed here: (https://beta.openai.com/account/usage).

That's right, switch to an OpenAI paid account and put a credit card in.
Give OpenAI a few minutes to process a payment of $5 and it'll just start working.

I assume any free tokens were used up or whatever (maybe because I use copilot?), so I'll use it lightly for a month and monitor the charges. 
I also set it to a max of $50 for now :)


Tech:
OS: Windows_NT x64 v10.0.19045
Visual Studio Code: v1.78.1
Code GPT: v2.1.6 (provider: OpenAI, model: gpt-4)

**Comment by coayscue** [comment]
Yep same issue all blank responses:
<img width="852" alt="Screenshot 2023-05-14 at 5 47 10 PM" src="https://github.com/davila7/code-gpt-docs/assets/11601141/a32e5807-928a-459e-8a60-45009a0fd18a">

**Comment by Moises9** [comment]
![image](https://github.com/davila7/code-gpt-docs/assets/19894030/04248d58-c65d-4817-854e-96037b4b6c30)



Here with the same problem

**Comment by tiagonunocosta** [comment]
I have the same problema.. 

Any help please

**Comment by DamirMakhmudov** [comment]
I got message: OpenAI API Response was: Error 429: You exceeded your current quota, please check your plan and billing details. More information about this error: https://docs.codegpt.co/docs/tutorial-basics/api_errors

I have free plan

<img width="917" alt="image" src="https://github.com/davila7/code-gpt-docs/assets/49723817/f2879ceb-b8bf-48d6-8242-607da1d5cd7a">

I tried reconfigured api key, could anyone give some advice pls

**Comment by justinas-kazanavicius** [comment]
Same issue here, I'm using Azure OpenAI. I have copied the endpoint & API key from completions in the Azure portal and the settings are all according to the docs.

Typing anything into chat, including any commands on the code returns an instant empty response.

**Comment by davila7** [comment]
Fixed up!
Please update to version 2.1.25

**Comment by K-e-d-i** [comment]
I am still having this issue. I am on codegpt v2.1.26 on Linux Fedora 38, vscode 1.83.0, ollama version 0.0.1 with llama code 7b. An error code would be nice to track down the problem.

**Comment by alanwilhelm** [comment]
I'm still seeing this now. CodeGPT enpoints/models work GPT just sits there and gives no response, but in Runtime status for the plugin see: `Unterminated string in JSON at position 133
Unexpected token 's', "sages, 100"... is not valid JSON`
