### ISSUE TITLE
Grouping items in the context menu.

### ISSUE THREAD

**Issue by CzarOfScripts** [davila7/code-gpt-docs#114]
Hi, thanks for your work! I'd like to see the context menu items collected in a single tabbed item. All those items take up too much space when only a couple are used. If that can be optional, that would be awesome.

That's the size the context menu grows to for me:
![image](https://user-images.githubusercontent.com/78804737/230775502-9caa7f38-dded-40c2-bfeb-95dc97a9754a.png)

**Comment by SergioSuarezDev** [comment]
how about? im interested on this

**Comment by PilarHidalgo** [comment]
Done in the new version https://app.vssps.visualstudio.com/_msal/_popup#
