### ISSUE TITLE
Point to private GPT instance 

### ISSUE THREAD

**Issue by mtweak** [davila7/code-gpt-docs#115]
In order to support private development, it would be necessary to point to a custom API endpoint such as GPT4all, or even Azure's OpenAI as a service:  https://azure.microsoft.com/en-in/products/cognitive-services/openai-service/.  Having a 'Custom', a few standard configuration paramenters should do the trick based on Azure's docs:

```
import os
import openai
openai.api_type = "azure"
openai.api_base = "https://docs-test-001.openai.azure.com/"
openai.api_version = "2023-03-15-preview"
openai.api_key = os.getenv("OPENAI_API_KEY")
```

<img width="545" alt="image" src="https://user-images.githubusercontent.com/13370087/231002388-cd8c8c1b-cf95-40b6-b4cb-484673d5c8ff.png">

**Comment by PilarHidalgo** [comment]
Yes, you can connect to custom API endpoints like Azure's OpenAI service in CodeGPT. Here are the steps to do so:

Create an account in Microsoft Azure.
Get access to Azure OpenAI Services.
Go to Azure OpenAI Studio.
Get your Secret Key and the Custom Link.
Go to VSCode and choose Azure as Provider.
Set connection on 🔑 button.
Paste API Key here, and click on Connect.
If you want to remove your API Key from CodeGPT, select Edit Connection on 🔑, and click on Disconnect.

Please note that you will need to have the necessary permissions and credentials to access the API. If you encounter any issues, you can refer to the Microsoft Azure Documentation.
