### ISSUE TITLE
Code GPT in VSC seems broken

### ISSUE THREAD

**Issue by Fowlplaychiken** [davila7/code-gpt-docs#116]
Now in VSC, every prompt has an extra 4000 tokens tacked onto it, so every prompt is rejected as having too many tokens. When it says how many tokens the prompt is, its always 4000 higher (which is the max token count) than it should be. This issue just started happening a couple days ago. Everything worked as intended until then. Ive tried reinstalling, re-inputting my API (which I have tested elsewhere and does work), and other tricks, no luck. Other GPT extensions seem to work fine still, but this was the best one until it broke.

**Comment by davila7** [comment]
Please lower the number of max tokens to 2500 and it should work.

**Comment by Fowlplaychiken** [comment]
Sadly no. Just tried as suggested. Same result. It seems to calculate the real token value, add a flat 4K, then send the errorOn Apr 10, 2023, at 10:56 PM, Daniel Avila ***@***.***> wrote:﻿
Please lower the number of max tokens to 2500 and it should work.

**Comment by Fowlplaychiken** [comment]
My mistake. I spoke too soon. After a restart, yes, that did fix it, sort of. Its still calculating tokens wrong or at least differently than it did before. Bummer. Can only do very very small code segments since it seems to add the input and output together now, as part of the same token limit. Essentially looks like it can do half as much code as before; but your right that it does work with small chunks of code and 2500 instead of 4K set. On Apr 10, 2023, at 11:15 PM, ***@***.*** wrote:﻿Sadly no. Just tried as suggested. Same result. It seems to calculate the real token value, add a flat 4K, then send the errorOn Apr 10, 2023, at 10:56 PM, Daniel Avila ***@***.***> wrote:﻿
Please lower the number of max tokens to 2500 and it should work.
