### ISSUE TITLE
Add ability to edit history

### ISSUE THREAD

**Issue by michox** [davila7/code-gpt-docs#117]
I would love to have more control over the history of the chat. I often use it to come up with new logic and describe the goal in a few chat messages first, being able to edit or delete individual history messages like in the openAI Playground would be amazing!

**Comment by PilarHidalgo** [comment]
I understand your need for more control over the chat history. Currently, CodeGPT Playground does not support editing or deleting individual history messages. However, you can reset the entire chat to start fresh. This feature is designed to ensure the integrity of the conversation history with the AI.
