### ISSUE TITLE
Confusion Output

### ISSUE THREAD

**Issue by whutddk** [davila7/code-gpt-docs#119]
I am not sure whether this issue comes from, `code gpt` or `openai`: the output sometimes looks fine, but sometimes becomes confusion. Can we output in Raw without any format?

![image](https://user-images.githubusercontent.com/20044360/231426609-55ea9487-0b30-49b5-9884-c2741f35002c.png)
![image](https://user-images.githubusercontent.com/20044360/231426738-cdfccb4e-f8e4-48c2-9ae4-1fe0390ffc9b.png)

**Comment by PilarHidalgo** [comment]
Yes, you can get raw output without any formatting. In CodeGPT, the output format is determined by the settings you choose. If you want to get raw output, you can adjust the settings accordingly. However, please note that the quality of the output also depends on the AI model you are using. If you are using an OpenAI model, the output might vary based on the model's understanding and interpretation of the input.
