### ISSUE TITLE
Error in golang: Create a comment and leave the cursor at the end of the comment line

### ISSUE THREAD

**Issue by TomerYakir** [davila7/code-gpt-docs#12]
JS files work fine.
I'm not using co-pilot.
VSCode version 1.74.3 (Universal).

**Comment by davila7** [comment]
The file extension in golang is .go?

**Comment by davila7** [comment]
I found the bug, it is fixed in the next version 1.0.12

**Comment by davila7** [comment]
Fixed in version 1.0.12

**Comment by TomerYakir** [comment]
thanks for the quick turnaround!
