### ISSUE TITLE
can't use cohere

### ISSUE THREAD

**Issue by lifesign** [davila7/code-gpt-docs#120]
i've set cohere as api provider, but when query codegpt, it seems use openapi for provider.
ps: both user and workspace are set to cohere

![image](https://user-images.githubusercontent.com/2189610/231630798-ede72b9c-1a8b-4dda-905f-6f5152116ff1.png)
![image](https://user-images.githubusercontent.com/2189610/231630822-7881bde4-fa51-4d5b-bbeb-d20d69b92080.png)

**Comment by arribi** [comment]
Exactly the same in my case.

**Comment by davila7** [comment]
Every time you make a change in settings, use the command Developer: Reload Window

Also, you must change the model to:
command-xlarge-nightly or command-medium-nightly

<img width="718" alt="Captura de Pantalla 2023-04-13 a la(s) 9 44 38 a  m" src="https://user-images.githubusercontent.com/6216945/231778059-70b36df3-7fcf-4219-9d33-852f1560b790.png">

**Comment by lifesign** [comment]
change model solved. thx~
