### ISSUE TITLE
404 when trying to use gpt 4

### ISSUE THREAD

**Issue by Maivand** [davila7/code-gpt-docs#121]
I get a 404 when trying to use gpt 4 (both models) 3.5 seem to work fine. any suggestions?

**Comment by esenliyim** [comment]
Your account needs to be given early access to gpt-4 API by openAI for it to work. 

By the way it's a little confusing, but ChatGPT Plus subscription will NOT give you access to the gpt-4 API. You can use it with the chatbot, but not with things like this extension.

**Comment by CaseyGarland** [comment]
How do you configure the vscode extension to use the 3.5 model not gpt-4?

**Comment by SaiTech** [comment]
> Your account needs to be given early access to gpt-4 API by openAI for it to work right now.
> 
> By the way it's a little confusing, but a ChatGPT Plus subscription will NOT give you access to the gpt-4 API. The Plus subscription lets you use gpt-4 with the chatbot, but not with things like this extension.

Thanks I have ChatGPT Plus, and I have spent some hours testing much. VSCode and the insiders, lode extension, and uninstall them. When I change to GPT3.5 everyting works. 
I have learned lots of other thing that maybe help me in the future.

**Comment by JseMatamoros** [comment]
Does anyone know if the service integrated in vscode is paid?

**Comment by PilarHidalgo** [comment]
. The error code 404 indicates that the model you're trying to access is not available. You can use the GPT-3.5-turbo model which is currently available and working fine. If you have any other issues or questions, feel free to ask!
