### ISSUE TITLE
No longer opening a new tab

### ISSUE THREAD

**Issue by YodaPants** [davila7/code-gpt-docs#122]
When I try run the Ask CodeGPT command it now opens the chat window on the side and doesn't show the response in a new tab but rather it makes the response in the chat window on the left.

Could you add an option to choose between where you want the output? 
Or make it so that if you run the command it opens a new tab rather than opening the extension window?

**Comment by pravinsingh** [comment]
Because of this issue, the README.md generation is broken. It now shows the HTML formatted view of the documentation rather than the raw Markdown, and copying it from the chat window just copies the text, not the Markdown formatting.

**Comment by JJpepe12** [comment]
This is a serious issue, many features have been blocked by the chat window :(. Please get back the new tab by default!

**Comment by PilarHidalgo** [comment]
I understand your concern. Currently, the design of CodeGPT is such that the responses are displayed in the chat window on the side. This is to facilitate a conversational interaction with the AI model.
