### ISSUE TITLE
independently set proxy for this plugin.

### ISSUE THREAD

**Issue by fvbfvbfvb** [davila7/code-gpt-docs#128]
Now it could not set proxy for code-gpt plugin enabled on WSL in VScode independently. If possible,  it is more convenient.

**Comment by PilarHidalgo** [comment]
Well, not at the moment, but if you want to run a model on a WSL server, you must verify that the server of VSCode has a connection and access to the WSL server. To help you with this, you can follow this article: https://medium.com/p/881b91ba193e
