### ISSUE TITLE
Request: Updates to the system message used by CodeGPT

### ISSUE THREAD

**Issue by blackirishmec** [davila7/code-gpt-docs#129]
Hi @davila7, thank you for this fantastic work. Is there a way to update the System message used with CodeGPT and VSCode when using OpenAI's provider? I'd love to modify that to increase usability. Thank you!

**Comment by PilarHidalgo** [comment]
I'm glad you're finding CodeGPT useful! However, the system message used with CodeGPT and VSCode when using OpenAI's provider is not directly modifiable by users. It's designed to provide a standard interface for all users. If you have specific suggestions for improvements, I recommend sharing your feedback with the CodeGPT team. They're always open to user suggestions to enhance the usability and experience. You can share your thoughts on our Canny Roadmap:  https://codegpt.canny.io/requests
