### ISSUE TITLE
Error: TypeError: Cannot read properties of undefined (reading 'data')

### ISSUE THREAD

**Issue by emanuelecastelli** [davila7/code-gpt-docs#13]
I got this message when i try to `Cmd + Shift + i`:
`Error: TypeError: Cannot read properties of undefined (reading 'data')`
Maybe my key is incorrect?
How can i change that?

**Comment by Ronan-david** [comment]
I have the same issue when i ask CodeGPT on VSCode, on windows 11 x64.
I have put my key and reloaded VSCode, to no avail.

**Comment by davila7** [comment]
What language are they using?
You could write the comment you are making and the file extension.

**Comment by oberos** [comment]
I have very similar problem:
`Error: TypeError: Cannot read properties of undefined (reading 'message')`
But i tested it on another laptop and it works as expected. How to get more debug to check what is wrong?

**Comment by davila7** [comment]
@oberos 
Could you tell me exactly what functionality you are using? the programming language and file extension, please.

**Comment by Ronan-david** [comment]
HI, I am using the english language on a javascript file. I still get the "data" error. I have no way of debugging it.

**Comment by sbdoy** [comment]
Hi @davila7 
I am experiencing the same issue, is typescript file comment below
// validate an email with regex and comment each line

**Comment by oberos** [comment]
> @oberos Could you tell me exactly what functionality you are using? the programming language and file extension, please.

I used python file and bash file and this error occures. Strange thing is that when I use python library openai with this same token and question everything is working fine even on this same machine.

**Comment by davila7** [comment]
There are some errors that OpenAI sends via API that I need to handle in the extension.

https://help.openai.com/en/articles/6891839-api-error-code-guidance

I am correcting it in the next version so that you can have the specific error that is occurring from the API

**Comment by oberos** [comment]
Even with this error handling it tells me nothing 
![image001](https://user-images.githubusercontent.com/13794575/215412454-4a683808-9c1a-4bc2-8b2f-218d81ccc6cb.png)

**Comment by Ronan-david** [comment]
Thanks, I get a bit more info now : 
OpenAI API Response was: Error [ERR_SOCKET_CLOSED]: Socket is closed. More information about this error: https://www.codegpt.co/docs/tutorial-basics/api_errors
It does not help me much but thank you for helping resolving the issue.

**Comment by davila7** [comment]
> Even with this error handling it tells me nothing ![image001](https://user-images.githubusercontent.com/13794575/215412454-4a683808-9c1a-4bc2-8b2f-218d81ccc6cb.png)

Here is a possible solution for the 400 error
https://community.openai.com/t/error-retrieving-completions-400-bad-request/34004

**Comment by davila7** [comment]
@incomingstick 

Close and reopen VSCode to fix that problem.
The new OpenAI API updates node packages and VSCode must close and reopen for this to work

**Comment by incomingstick** [comment]
Interesting. It was a fresh install of the extension, so I guess I just assumed it would only have needed to restart if I had updated the extension from a previous version, but ultimately restarting did fix it.

Perhaps a pop-up in the bottom left when the extension requires a full restart of VS Code?

**Comment by davila7** [comment]
good idea! I'll add it, thank you!
I hope the chat version works well for you, the following versions will be more integrated with the code you work with
