### ISSUE TITLE
Feature: add option to support Azure OpenAI

### ISSUE THREAD

**Issue by duchenpaul** [davila7/code-gpt-docs#132]
Request to add support for azure openai, which uses Azure's open AI API

Reference: https://jussiroine.com/2023/03/a-practical-look-at-using-and-building-on-azure-openai-specifically-the-chatgpt-style-feature/

**Comment by vlerenc** [comment]
Hello... same thing. I got GPT4 via Azure, not via OpenAI. The API is practically the same. Only minimal differences (deployment id vs model), so there really isn't much to do. Is there maybe a "hacky way" somehow?

**Comment by duchenpaul** [comment]
If it has an option to customize the API URL, I think this can easily achieve as there is a very cool project https://github.com/stulzq/azure-openai-proxy that can convert Azure API to openai API

**Comment by stnaw** [comment]
Also hope that developers can add this feature.🙏🏻

**Comment by davila7** [comment]
@duchenpaul @vlerenc @duchenpaul @stnaw @bkarstaedt 

We are finishing some details of this integration 🙌

**Comment by rajesh-ne-algoworks** [comment]
@davila7  Is there any ETA by when it will be done. We are really looking for azure open ai integration in this extension.

**Comment by emirhosseini** [comment]
Also would like to have Azure support. Most companies will not allow using the OpenAI models since they're public. Azure provides the ability to deploy internal models which this extension unfortunately still doesn't support.

**Comment by carusyte** [comment]
+1 for the request!

**Comment by PilarHidalgo** [comment]
Hello! It seems like you're interested in adding support for Azure OpenAI in your project. CodeGPT already supports Azure OpenAI. Here's how you can set it up:

Create an account in Microsoft Azure.
Get access to Azure OpenAI Services.
Go to Azure OpenAI Studio.
Get your Secret Key and the Custom Link.
Go to VSCode and choose Azure as Provider.
Set connection on the 🔑 button.
Paste your API Key, and click on Connect.
If you want to remove your API Key from CodeGPT, select Edit Connection on the 🔑, and click on Disconnect.
