### ISSUE TITLE
Support for local models

### ISSUE THREAD

**Issue by mudler** [davila7/code-gpt-docs#133]
Hi :wave: ! 

Very nice project! any plans/interest in running local models, with something like LocalAI? https://github.com/go-skynet/LocalAI

I'd be happy to take a stab at it if there is interest in it

**Comment by mudler** [comment]
@davila7 any interest in this?

**Comment by davila7** [comment]
@mudler  you can check the GPT4All integration, it's really similar

**Comment by davila7** [comment]
https://docs.codegpt.co/docs/tutorial-basics/installation#gpt4all

**Comment by mudler** [comment]
@davila7 thanks for replying. that doesn't seem to allow me to set an URL, right? how can I point to a different API URL?
