### ISSUE TITLE
Cannot copy and paste code from completion response window pane - totally bogus!!  Fix this!!

### ISSUE THREAD

**Issue by richlysakowski** [davila7/code-gpt-docs#136]
I need to incorporate completion responses for "Explain Code" from the CODEGPT Chat response window.  I cannot copy-and-paste anything.  It is totally disabled now.    I can select documentation text that was generated, but when I try to copy it to the clipboard, nothing gets copied to the clipboard that can be pasted into code cells or .py files.  

Please fix this.  

Also, my preference is to have the CODEGPT Chat window to the right side of VSCode, not frozen on the left-sidebar.   There are no instructions for changing the placement, undocking, or moving the CodeGPT window widget to other locations in VSCode.

**Comment by PilarHidalgo** [comment]
Hello! Ensure that you're using the latest version of the CodeGPT extension. You can check this in the Extensions tab in VSCode.
