### ISSUE TITLE
Cannot apply API Key from other service, like Cohere

### ISSUE THREAD

**Issue by TalantRys** [davila7/code-gpt-docs#139]
What i'm was tried and chat didn't work:
 - I changed provider from OpenAI to Cohere
 - Started command to set API key and pasted it
 - **EACH STEP I RELOADED WINDOW**

After that i starting chat and getting error 401 from **Open AI** with link to their web-documentation.
I don't understand what to do

My setting:
![image](https://user-images.githubusercontent.com/78742311/236195005-fed6dd1c-2535-4462-976f-c78d6ee9ae67.png)

**Comment by PilarHidalgo** [comment]
It seems like you're having trouble connecting to the Cohere provider in CodeGPT. Here are the steps you should follow:

Go to your dashboard on the Cohere official website.
In VSCode, choose Cohere as your Provider.
Click on the Set Connection button (🔑).
Paste your Cohere API Key and click on Connect.
If you've followed these steps and are still getting an error, it's possible that there might be an issue with your API Key. Please double-check that your API Key is correct and try again. If the problem persists, you might want to check the Cohere API Errors documentation for more information.
