### ISSUE TITLE
Commands Inaccessible via VSCode Command Palette

### ISSUE THREAD

**Issue by greatwaldini** [davila7/code-gpt-docs#14]
Maybe this is user error, but I can't figure out what's causing this.  Submitting this here in case it's not just me.

**Code GPT Version:** 1.0.12

**Installation Method:** VSCode integrated Extension search/installer

**Visual Studio Code Version:** 1.74.3

**OS:** macOS 12.3.1

**Issue:** None of the Code GPT commands are available through the VSC Command Palette.  I tried closing and reopening VSC to no effect.  In order to add my API key, I had to set a keyboard shortcut specifically to execute the respective Code GPT function.

After adding my API key, the commands are still unavailable via the Command Palette.  However, the extension otherwise works normally as described in the docs.  I.e. the various commands are available in the right-click menu.  Command-shift-i works fine.  Etc.  Just nothing available through Command Palette.

**Comment by davila7** [comment]
In the command palette you only have the following commands available:

Ask Code GPT
Ask StackOverflow
Set Api Key
Remove Api Key

The other commands are only available on right click as you need to have a code selected in order to use them.
