### ISSUE TITLE
Exceeded maximum context length, but not possible - based on 1 simple string of code

### ISSUE THREAD

**Issue by exelanz** [davila7/code-gpt-docs#140]
Hi all,

I was using CodeGPT extension without problem for some months, but now something has changed and it is not working anymore.

Example (in attached screenshot): I select one (1) line of code, right-click, select "Explain CodeGPT" and then I hit an error about exceeding maximum context length. 

I think this should not be possible as this line (and others tested) in tokenizer does not even generate more than 200 tokens. 

I cannot find the issue...any help is appreciated. 

![image](https://user-images.githubusercontent.com/831364/236199766-436564a8-ee89-4619-af25-c1c0e7df994e.png)

**Comment by exelanz** [comment]
Holy crap...

The CodeGPT extension setting:
"Code GPT: Max Tokens
The maximum number of tokens for request"

was set to 5000, which is bigger than 4097. Setting it to a value lower than 4097, e.g. 4000, resolved the issue.

**Comment by davila7** [comment]
@exelanz I recommend you to use 2500 max tokens

**Comment by exelanz** [comment]
@davila7 thanks for your suggestion. Will implement the 2500 max limit
