### ISSUE TITLE
Open VSX version outdated

### ISSUE THREAD

**Issue by 0x00A1FA** [davila7/code-gpt-docs#141]
Please update the VSX version!

**Comment by leonhardholz** [comment]
@davila7 I'd also be interested in this. We use Gitpod and it would allow to install the plugin without manually uploading the extension file.

**Comment by davila7** [comment]
@0x00A1FA @leonhardholz 

It is already updated to version 2.1.6
This weekend it will be with version 2.1.8 with the updates of Anthropic and Judini
