### ISSUE TITLE
[Error] Please enter your api key, go to https://codegpt.co/ for more information.

### ISSUE THREAD

**Issue by 0x00A1FA** [davila7/code-gpt-docs#142]
Can you please refactor your code and communicate better errors? I'm getting this even though I've set-up my API key.

**Comment by Chasty** [comment]
Same here :(

**Comment by topcheese** [comment]
Yeah I don't get it except for it may be an IDE issue.  I think updating to the latest VS Code may fix it, but not on Codium ... at least on a Mac.

**Comment by Maol-1997** [comment]
> 

did you updated the extension ?

**Comment by topcheese** [comment]
My understanding is that some 3rd party dependencies cannot be open-sourced  with some plugins, and they can only be released for VS Code.  Actually I think it's some of the code MS included in it, now that I'm remembering ... probably a little of both.
The developer can confirm this?  I know they released it for some other IDEs, but I'm thinking Codium might be a special case being built off VS Code?

**Comment by Maol-1997** [comment]
Codegpt office extension is in vscode only. It uses an vscode encripted storage to store the api keys, maybe in your os you need to send special permissions ?

**Comment by topcheese** [comment]
Thank you so much, that's just what I needed to hear.  The developer should be able to close at least one ticket, and should probably should add the clarification in bold somewhere.

**Comment by adepeuf** [comment]
same issue, and using vs code

**Comment by topcheese** [comment]
@adepeuf , which version, what platform, and is it the exact issue and error message?

**Comment by adepeuf** [comment]
VS CODE:
Version: 1.73.0 (system setup)
Commit: 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
Date: 2022-11-01T15:34:06.111Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

CODE GPT extension: v2.1.6

**Comment by topcheese** [comment]
@adepeuf Your problem is wrong VS Code version, please update to the latest version. 1.78.

**Comment by adepeuf** [comment]
> @adepeuf Your problem is wrong VS Code version, please update to the latest version. 1.78.

works with 1.78, thank you

**Comment by pareekshithraj** [comment]
what is my api ?😒

**Comment by 0x3N3JVhPUV** [comment]
Version: 1.79.1 (user setup)
Commit: 4cb974a7aed77a74c7813bdccd99ee0d04901215
Date: 2023-06-12T16:14:05.102Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19044

I still receiving the following message after entering my api key:
[[Error] Please enter your api key, go to https://codegpt.co/ for more information.]

I need help please

**Comment by rmeissn** [comment]
I think I got the same problem. I'm using VScodium 1.80 and codeGPT 2.1.9. Whenever I set the API key, it seems it was set correctly. After restart of VScodium, the chat sidebar says I should set my API key (even though I did before).
I tried this several times and with different workflows. Other extensions (like Gitlab) is able to store API keys successfully.

Here's the log, that is thrown by this extension (not sure whether it is related):
```
2023-07-12 14:02:22.569 [error] TypeError: Cannot read properties of null (reading 'webview')
    at /.../.vscode-oss/extensions/danielsanmedium.dscodegpt-2.1.10-universal/src/extension.js:447:30
    at e.ExtHostCommands._executeContributedCommand (/usr/share/codium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:72243)
    at e.ExtHostCommands.$executeContributedCommand (/usr/share/codium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:73232)
    at t._doInvokeHandler (/usr/share/codium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:14416)
    at t._invokeHandler (/usr/share/codium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:14098)
    at t._receiveRequest (/usr/share/codium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:12856)
    at t._receiveOneMessage (/usr/share/codium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:11555)
    at i.value (/usr/share/codium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:9662)
    at b._deliver (/usr/share/codium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:60:2465)
    at b.fire (/usr/share/codium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:60:2784)
    at fire (/usr/share/codium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:76:16556)
    at i.value (/usr/share/codium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:36590)
    at b._deliver (/usr/share/codium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:60:2465)
    at b.fire (/usr/share/codium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:60:2784)
    at fire (/usr/share/codium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:76:16556)
    at MessagePortMain.<anonymous> (/usr/share/codium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:34667)
    at MessagePortMain.emit (node:events:513:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367) codegpt.askCodeGPT {"value":"DanielSanMedium.dscodegpt","_lower":"danielsanmedium.dscodegpt"}
```

**Comment by rmeissn** [comment]
The problem seems to stem from ChatSidebarProvider, lines 58 onwards.
The `const apiKey` is filled with:
```json
{"_actual":null,"_actualOk":null,"_actualErr":null,"_hasValue":false,"_value":null,"_hasErr":false,"_err":null}
```
which is not an API key. I guess something is wrong with the context variable...

**Comment by tiagonunocosta** [comment]
In my Mac Ventura  i enter the API Key and I don’t receive any error but when I use the chat e receive a empty response 
![image](https://github.com/davila7/code-gpt-docs/assets/17408764/b6c90995-268a-41da-b79c-55c8bf4cc50f)

Can any one help me please

**Comment by silentsilas** [comment]
> The problem seems to stem from ChatSidebarProvider, lines 58 onwards. The `const apiKey` is filled with:
> 
> ```json
> {"_actual":null,"_actualOk":null,"_actualErr":null,"_hasValue":false,"_value":null,"_hasErr":false,"_err":null}
> ```
> 
> which is not an API key. This stems from the fact that `context.secrets.get()` is an async function, but there is no await. Thus, the constant is filled with a promise... Later the result of the promise is accessed with `apiKey.g`, which fails. Simple fix: make `_update` an async function and await for the api key. Use `apiKey` only, not `apiKey.g` These changes fixed the plugin for me in VScodium. I'm uncertain whether this change breaks anything else....

You're a lifesaver! Created a gist with those changes. Confirmed it's working for OpenAI on an M2 Macbook Pro running VSCodium v1.81.0

https://gist.github.com/silentsilas/c11acff9d65d04f40920ddb782d17195

**Comment by tiagonunocosta** [comment]
Hello

After the update to 1.81 it works, thanks



Com os melhores cumprimentos | Best regards
[Image]

Tiago Silva Costa | MSc
Chief Executive Officer
Skype: tiagocostanuno
Tlm: +351 917 269 041 , +351 918 069 762

http://virtualcare.pt<https://virtualcare.pt>

UPTEC Asprela I, Rua Alfredo Allen, 461 | 4200-135 Porto



From: Silas ***@***.***>
Date: Friday, 4 August 2023 at 20:36
To: davila7/code-gpt-docs ***@***.***>
Cc: Tiago Silva-Costa ***@***.***>, Comment ***@***.***>
Subject: Re: [davila7/code-gpt-docs] [Error] Please enter your api key, go to https://codegpt.co/ for more information. (Issue #142)

The problem seems to stem from ChatSidebarProvider, lines 58 onwards. The const apiKey is filled with:

{"_actual":null,"_actualOk":null,"_actualErr":null,"_hasValue":false,"_value":null,"_hasErr":false,"_err":null}

which is not an API key. This stems from the fact that context.secrets.get() is an async function, but there is no await. Thus, the constant is filled with a promise... Later the result of the promise is accessed with apiKey.g, which fails. Simple fix: make _update an async function and await for the api key. Use apiKey only, not apiKey.g These changes fixed the plugin for me in VScodium. I'm uncertain whether this change breaks anything else....

You're a lifesaver! Created a gist with those changes. Confirmed it's working for OpenAI on an M2 Macbook Pro running VSCodium v1.81.0

https://gist.github.com/silentsilas/c11acff9d65d04f40920ddb782d17195
