### ISSUE TITLE
Save API Keys when switching provider

### ISSUE THREAD

**Issue by kferrone** [davila7/code-gpt-docs#145]
I select OpenAI then set the API key. Then I must reload the window, now OpenAPI works. I switch to AI21 with j2-grande-instruct and set my API key and must reload window yet again. Now AI21 works. I switch back to OpenAI, now I must set the API key again and reload the window again? Please store the API keys separately for each provider so I don't have to input it every time I switch.

**Comment by davila7** [comment]
@kferrone 
We are creating an object that can store all the keys for each provider.
soon this will be resolved

**Comment by PilarHidalgo** [comment]
Hi everyone!

I hope you're all doing well. Please take a moment to update to the latest version here: [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=DanielSanMedium.dscodegpt&ssr=false#overview).

Thank you!
