### ISSUE TITLE
No response output received

### ISSUE THREAD

**Issue by chrismurtagh** [davila7/code-gpt-docs#147]
Was working great, recently stopped giving the output of the responses.

Extension Version 2.1.6
vscode Version : 1.78.1    6a995c4f4cc2ced6e3237749973982e751cb0bf9  x64
Gentoo Linux
Kernel Version: 6.3.2

OpenAI personal tier
Limits not hit.
API key has been input

Extension settings:
"CodeGPT.apiKey": "OpenAI"
"CodeGPT.maxTokens": 800
"CodeGPT.model": "gpt-3.5-turbo"
"CodeGPT.query.language": "English"
"CodeGPT.temperature": 0.3

no output in response.

![image](https://github.com/davila7/code-gpt-docs/assets/122645304/de7f9625-ebbd-4865-adad-905c035ce5b1)

**Comment by EmperorRXF** [comment]
I'm encountering the exact same behavior, sometimes when I restart vscode, the very 1st question is answered. But then it stops responding at all

Extension Version 2.1.6

Vscode:
Version: 1.78.2 (user setup)
OS: Windows_NT x64 10.0.19045

**Comment by substitute5** [comment]
I'm also encountering this problem.

**Comment by ebasurto** [comment]
Check your USAGE  [https://platform.openai.com/account/usage](url) you may have exceeded your "free trial" quota. I was having exactly the same problem and changed to a paid subscription and it's working now.

If the "pay as you go" model doesn't meet your expectations, stick to the good old website and the mighty copy-paste.

Hope this works!

**Comment by ZzyzxIsAlreadyTaken** [comment]
I have used almost nothing of my free credits. Still experiencing the same problem.

**Comment by davila7** [comment]
@rickfadeli @Messiahs100 @EmperorRXF @ZzyzxIsAlreadyTaken  @ebasurto @substitute5 @chrismurtagh 

Version 2.1.7 is going to show the error message you are getting from the API.

This version will be updated today 🙌

**Comment by chrismurtagh** [comment]
The new version was received 

Error did say limits hit

I looked back at my usage and noticed that even though my limits were not hit, my credits had expired.

Moved to pay as you go, and everything is fine now.

Can close this issue as resolved now that the error is being shown.

Thanks a bunch

**Comment by davila7** [comment]
Update to the last version 2.1.8 

Now you could see the error message
