### ISSUE TITLE
The Ask feature isn't working and I don't see the icon in the sidebar.

### ISSUE THREAD

**Issue by cr545l** [davila7/code-gpt-docs#148]
![스크린샷 2023-05-13 오후 1 12 20](https://github.com/davila7/code-gpt-docs/assets/10678303/b87b2288-43cd-4e29-b407-fce4ea4d175c)  
Installed but not seeing the icon in the sidebar

![스크린샷 2023-05-13 오후 1 13 35](https://github.com/davila7/code-gpt-docs/assets/10678303/1f0b6c85-944b-4097-bb3d-34cabb62defa)  
Only the Explorer window is visible when using the Ask feature

Things I tried
- Switching Disable/Enable 
- Reinstall

**Comment by topcheese** [comment]
Please provide system stats, in order for people to have more of a clue to the possible problem?  How did you install it?, What are all the version numbers you working with?

**Comment by GFrost72** [comment]
ye me 2 have this problem

**Comment by PilarHidalgo** [comment]
Hi everyone!

I hope you're all doing well. Please take a moment to update to the latest version here: [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=DanielSanMedium.dscodegpt&ssr=false#overview).

Also, Update the Node js to 18.0 or lasted

Thank you!
