### ISSUE TITLE
Not compatible can't install danielsanmedium.dscodegpt extension

### ISSUE THREAD

**Issue by enjofaes** [davila7/code-gpt-docs#15]
Any way to fix this error? Using v 1.73.1 -- not possible to download an older version of the extension. I'm unable to upgrade vscode

**Comment by davila7** [comment]
I'm checking with the Visual Studio Code team to see if the version requirement can be lowered.

I'll have news soon.

**Comment by davila7** [comment]
The next version will have support for VSCode 1.73.0.

I will update it during the week

**Comment by davila7** [comment]
@enjofaes 
Update to version 1.0.13 as it should be compatible with this version of VSCode.

Please confirm if everything works correctly.
