### ISSUE TITLE
Enter your API KEY to save it securely.

### ISSUE THREAD

**Issue by harry0402** [davila7/code-gpt-docs#151]
Always meet this error, vscode version 1.78, I've enter the api many times.

**Comment by Vivekanandapolu** [comment]
same issue brother

**Comment by Vivekanandapolu** [comment]
i just solved that issue bro 
CLICK ctrl+shift+p and paste this "CodeGPT: Set API KEY' and enter any key in that pop-up

**Comment by PilarHidalgo** [comment]
Hi everyone!

I hope you're all doing well. Please take a moment to update to the latest version here: [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=DanielSanMedium.dscodegpt&ssr=false#overview).

Thank you!
