### ISSUE TITLE
Can't install 'danielsanmedium.dscodegpt' extension because it is not compatible with the current version of Visual Studio Code (version 1.69.1).

### ISSUE THREAD

**Issue by sonydaman** [davila7/code-gpt-docs#152]
Can't install 'danielsanmedium.dscodegpt' extension because it is not compatible with the current version of Visual Studio Code (version 1.69.1).

**Comment by davila7** [comment]
@sonydaman @handersonc 

Please update your version of visual studio code to version 1.72.0 or higher
