### ISSUE TITLE
Set API secret via Console

### ISSUE THREAD

**Issue by mmailaender** [davila7/code-gpt-docs#153]
Is there a way to set the chatGPT API secret via the console? 

We're using ephemeral vscode instances (Gitpod.io). That means we need to add the API key every time we start a new instance (Which happens daily). That's quite repetitive. So we would like to inject the secret from our secret management tool via console into the plugin.

like `codegpt secret set "<superSecureSecret>"`

**Comment by mmailaender** [comment]
Alternatively, it would help if you add an autoloader into your extension that automatically loads an env (e.g., $CODEGPT_TOKEN) into the VScode secret store so I can set the env via the terminal.

I would also be open to adding a bounty on this if this is currently not on your priority list. @davila7

**Comment by PilarHidalgo** [comment]
Currently, CodeGPT doesn't support setting the API key via the console. The API key is typically set through the VSCode interface. However, I understand your situation and the need for a more streamlined process in an ephemeral environment. I recommend reaching out to the CodeGPT team directly for more tailored assistance. They might be able to provide a solution or consider this feature in future updates
