### ISSUE TITLE
Code boxes in chat breaking

### ISSUE THREAD

**Issue by DeviousD4n** [davila7/code-gpt-docs#155]
This doesn't occur all the time but when it does it makes the reply worthless, especially with python.

![Screenshot from 2023-05-28 19-28-10](https://github.com/davila7/code-gpt-docs/assets/129655658/bfda5039-1df5-45b4-8c9e-15bb9f10760d)
)

**Comment by PilarHidalgo** [comment]
Hi everyone!

I hope you're all doing well. Please take a moment to update to the latest version here: [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=DanielSanMedium.dscodegpt&ssr=false#overview).

Thank you!
