### ISSUE TITLE
"Ask a question" sidebar scrolling behavior

### ISSUE THREAD

**Issue by geertj** [davila7/code-gpt-docs#156]
The scrolling behavior in "Ask a question sidebar UI is quirky and frustrating to use. This seems like a core use case so I'd recommend to prioritize fixing this. The best behavior in my view would be:

* Autoscroll while an answer is being generated.
* The "Stop responding" button should not obscure the last few lines of the answer.

**Comment by PilarHidalgo** [comment]
Hi everyone!

I hope you're all doing well. Please take a moment to update to the latest version here: [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=DanielSanMedium.dscodegpt&ssr=false#overview).

Thank you!
