### ISSUE TITLE
Enter your API KEY to save it securely.

### ISSUE THREAD

**Issue by S4ezChoco** [davila7/code-gpt-docs#157]
i cant do anything this always show up

**Comment by davila7** [comment]
Check this link:

https://docs.codegpt.co/docs/tutorial-basics/installation#get-your-api-key

**Comment by zhkzyth** [comment]
the same issue, added the api key, but still showing the err msg. after reload, the same.

Info:
vscode plugin version: v2.1.16
MacBook Pro (Intel-based)
MacOS 13.4.1 (c)

**Comment by JackDaexter** [comment]
thanks to @davila7.
Follow the step : 

- CodeGPT Plus
- Request your API Key from the [CodeGPT Plus](https://account.codegpt.co/auth/register)
- Go to the Settings / Access tokens and copy your API Key
- In VSCode press cmd + shift + p and search Set API Key
- Paste your API Key
-

**Comment by PilarHidalgo** [comment]
Hi everyone!

I hope you're all doing well. Please take a moment to update to the latest version here: [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=DanielSanMedium.dscodegpt&ssr=false#overview).

Thank you!
