### ISSUE TITLE
Code GPT 429

### ISSUE THREAD

**Issue by Ningen-jpg** [davila7/code-gpt-docs#158]
Hello I got the error 429 "ou exceeded your current quota, please check your plan and billing details. More information about this error" and I can't use codegpt whatsoever even though I barely used it and I was just trying simple instructions.

How do i resolve this?

Thank you so much in advance

**Comment by davila7** [comment]
Please check this section of the documentation:
https://docs.codegpt.co/docs/tutorial-ai-providers/openai#openai-api

You should check if you have the initial credits and if the date has not expired.
If so, you must add a card to be able to continue using the OpenAI api.

**Comment by lyaguxafrog** [comment]
the same problem, though I didn't have a single request in ChatGPT, although it also writes that it expired

**Comment by judiniAI** [comment]
@lyaguxafrog 
If your credits have expired, you must add your credit card to the OpenAI account in order to use the API.

Check this link: https://help.openai.com/en/articles/6891831-error-code-429-you-exceeded-your-current-quota-please-check-your-plan-and-billing-details
