### ISSUE TITLE
Notifications Obscures Input

### ISSUE THREAD

**Issue by mholtzhausen** [davila7/code-gpt-docs#159]
When using a shortcut to activate `Ask CodeGPT`, it displays a notification that obscures the input, and you have to close the notification with your mouse (or wait a really long time for it to disappear on its own). This means I can't see what I'm typing unless I use my mouse, which defeats the purpose of defining a keyboard shortcut for it.

The ask:
Could we maybe have an option to disable info-notifications?

![image](https://github.com/davila7/code-gpt-docs/assets/90659/2459b315-685b-438d-b16a-e02abd42aa24)

**Comment by PilarHidalgo** [comment]
Hi everyone!

I hope you're all doing well. Please take a moment to update to the latest version here: [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=DanielSanMedium.dscodegpt&ssr=false#overview).

Thank you!
