### ISSUE TITLE
VS Code and Open API. Correct Code Request doesn't return all the code.

### ISSUE THREAD

**Issue by kfoubert** [davila7/code-gpt-docs#160]
When I asked CodeGPT to correct code in a file it returns about two thirds of the code and then it stops. The file has 188 lines of code. Is there a setting I need to change or does OpenAI return X number of characters?

**Comment by davila7** [comment]
@kfoubert 

What model are you using?
And how many Max Tokens do you have?

**Comment by squld** [comment]
@davila7 
Hi, I have the same problem in `CodeGPT Chat` panel with the following conditions:

Visual Studio Code: `Version: 1.85.2`
Extension: `Code GPT: Chat & AI Agents v3.1.4`
Provider: `OpenAI`
Model: `gpt-4-1106-preview`
settings.json:
```json
{
    "CodeGPT.apiKey": "OpenAI",
    "CodeGPT.Autocomplete.enabled": true,
    "CodeGPT.Autocomplete.maxTokens": 4000,
    "CodeGPT.Autocomplete.provider": "OpenAI - gpt-3.5-turbo-instruct"
}
```
Message: `Rewrite the JavaScript code into TypeScript`
Selected code: about **2000** tokens
Output code: **497** tokens

I guess that the number of output tokens at `CodeGPT Chat` panel is limited to **500**.

**Comment by PilarHidalgo** [comment]
Hi everyone!

I hope you're all doing well. Please take a moment to update to the latest version here: [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=DanielSanMedium.dscodegpt&ssr=false#overview).

Thank you!
