### ISSUE TITLE
Detected: as Trojan:Script/ObfusScript.A!ml

### ISSUE THREAD

**Issue by eddycy92** [davila7/code-gpt-docs#161]
Type: <b>Bug</b>

Detected: as Trojan:Script/ObfusScript.A!ml
Status: Removed
A threat or app was removed from this device.

Date: 6/8/2023 2:42 PM
Details: This program is dangerous and executes commands from an attacker

Affected items: file: C:\Users\elect\.vscode\extensions\danielsanmedium.dscodegpt-2.1.10\src\clients\anthropic_client.js

Extension version: 2.1.10
VS Code version: Code 1.79.0 (b380da4ef1ee00e224a15c1d4d9793e27c2b6302, 2023-06-07T14:26:35.552Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900X 12-Core Processor             (24 x 3693)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|79.89GB (63.44GB free)|
|Process Argv|--crash-reporter-id 2813c73d-2dc1-4c2c-a842-d96d29fcdd57|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30730052
showsbindicator:30760979
pythongtdpathcf:30739705
dh2dc718:30763024
pythonnosmt12:30757131

```

</details>

**Comment by davila7** [comment]
@eddycy92 

That file only has a POST to the Anthropic api "api.anthropic.com"
