### ISSUE TITLE
chatSidebarProvider.clearChat is not a function (v2.1.12)

### ISSUE THREAD

**Issue by mc1903** [davila7/code-gpt-docs#164]
Clear Chat gives the error message `chatSidebarProvider.clearChat is not a function` everytime.

![image](https://github.com/davila7/code-gpt-docs/assets/13692287/4d109fdd-ec24-44ef-b2b9-b9609bdfb72c)

![image](https://github.com/davila7/code-gpt-docs/assets/13692287/093e2815-4996-4e07-b0ca-1797cc9d9291)

![image](https://github.com/davila7/code-gpt-docs/assets/13692287/66577f04-952f-43c0-ba9a-d77bacd0e3ed)

**Comment by S-Cardenas** [comment]
I'm seeing this also. Please advise.

**Comment by davila7** [comment]
Fixed in the 2.1.13 version
