### ISSUE TITLE
CODEGPT Please enter your api key, go to https://codegpt.co for more information.

### ISSUE THREAD

**Issue by cangarot** [davila7/code-gpt-docs#165]
Hello, i´ve already followed the manual information to set the API Key in Visual Studio Code, and also to refresh the window, however when i try to use the chat it keeps repeating the message 

CODEGPT
Please enter your api key, go to https://codegpt.co/ for more information.

Im currently using the last version 1.79.1

Does anybody have any idea how to fix it ?

**Comment by 0x3N3JVhPUV** [comment]
> Hello, i´ve already followed the manual information to set the API Key in Visual Studio Code, and also to refresh the window, however when i try to use the chat it keeps repeating the message
> 
> CODEGPT Please enter your api key, go to https://codegpt.co/ for more information.
> 
> Im currently using the last version 1.79.1
> 
> Does anybody have any idea how to fix it ?

I have the same issue. Need help. Please

**Comment by Rihyx** [comment]
I have the same issue

**Comment by davila7** [comment]
Please update to the latest version of CodeGPT and then reload the VSCode instance with the command cmd + shift + p and then search for Reload Windows

**Comment by mauroigor1** [comment]
I have the same issue @davila7 . Need this for tomorrow hackathon

**Comment by mauroigor1** [comment]
I solved with ctrl+shift+P select set Judini data and enter the API key. For differents architecture you need to search the codegpt documentation.

**Comment by fckyeslol** [comment]
how can i know my API key?
