### ISSUE TITLE
Make the initial context prompt customizable

### ISSUE THREAD

**Issue by hapablap21** [davila7/code-gpt-docs#166]
It would be nice if users could override the default prompt context ("I am an expert...").  Default can remain if no override is set, but I'd like to be able to cut down on the sent tokens sometimes, possibly tweak the context to my specific needs over time.

**Comment by davila7** [comment]
@hapablap21 

This is a very good idea. We will add it in the following versions.

**Comment by PilarHidalgo** [comment]
Hi everyone!

I hope you're all doing well. Please take a moment to update to the latest version here: [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=DanielSanMedium.dscodegpt&ssr=false#overview).

Thank you!
