### ISSUE TITLE
Error when set API KEY

### ISSUE THREAD

**Issue by sipatanjana** [davila7/code-gpt-docs#168]
![image](https://github.com/davila7/code-gpt-docs/assets/48237674/d2aa5478-c7ad-45da-b84a-3ab26d2b05e7)
always show this error message when set API KEY

**Comment by davila7** [comment]
Please upgrade your computer's resources and check that you have all the permissions available.

You can review the VSCode Secrets documentation at this link:
https://code.visualstudio.com/api/references/vscode-api#SecretStorage
