### ISSUE TITLE
Feature Request: User Customizable baseURL

### ISSUE THREAD

**Issue by cuixiaorui** [davila7/code-gpt-docs#169]
Hello,

I have been using your plugin and I find it very useful. However, I have encountered a situation where I need to modify the baseURL. Currently, the plugin does not provide this feature and I have to modify the source code each time to achieve this.

I believe it would be beneficial for users if we could have

Thank you for considering my request. I look forward to any updates on this matter.

Best regards

**Comment by cuixiaorui** [comment]
I understand that you may have other priorities and time constraints. If it helps, I would be more than happy to contribute to the development of this feature. Please let me know if this is something you would consider, and I can start working on it.

Thank you once again for your time and consideration.

**Comment by davila7** [comment]
@cuixiaorui 

Working on this

**Comment by yachen4ever** [comment]
any update on this? :)

**Comment by swuecho** [comment]
https://github.com/davila7/code-gpt-docs/issues/208

**Comment by Lufffya** [comment]
@cuixiaorui big old, can you share the code you have modified?

**Comment by speedyankur** [comment]
You can Try GENIEAI extension, https://marketplace.visualstudio.com/items?itemName=genieai.chatgpt-vscode, it supports custom open AI urls in settings

**Comment by davila7** [comment]
In the latest version 3.1.1 you can now use Customizable baseURL

<img width="508" alt="Captura de pantalla 2024-01-12 a las 08 25 59" src="https://github.com/davila7/code-gpt-docs/assets/6216945/a965b4e8-acb5-451e-83be-75e61249c453">

**Comment by DimIsaev** [comment]
custom url 
 status  "Connected"
But not  view list models

**Comment by igor-elbert** [comment]
> custom url status "Connected" But not view list models

Same
