### ISSUE TITLE
This language is not supported

### ISSUE THREAD

**Issue by obwohl** [davila7/code-gpt-docs#171]
I tried the easiest example:
# a hello world program

and then command+shift+i
result: this language is not supported.

vscode is in english.

**Comment by PilarHidalgo** [comment]
Hi everyone!

I hope you're all doing well. Please take a moment to update to the latest version here: [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=DanielSanMedium.dscodegpt&ssr=false#overview).

Thank you!
