### ISSUE TITLE
Error 404: This is a chat model and not supported in the v1/completions endpoint.

### ISSUE THREAD

**Issue by ackvf** [davila7/code-gpt-docs#172]
Hi, I get this error, what model should I use?

> OpenAI: API Response was: Error 404: This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions? More information about this error: https://docs.codegpt.co/docs/tutorial-basics/api_errors

Moreover, I found that `v1/completions` is a legacy endpoint only supported by old legacy models `text-davinci-003, text-davinci-002, text-curie-001, text-babbage-001, text-ada-001`
https://platform.openai.com/docs/models/model-endpoint-compatibility 
https://platform.openai.com/docs/models/moderation (they have wrong anchor link, lol, see the **GPT-3** section below)

**Comment by ackvf** [comment]
Ah, okay, I see, I set `gpt-3.5-turbo-16k` that was the issue. When I reverted back to default `gpt-3.5-turbo` the error went away.

**Comment by PilarHidalgo** [comment]
Hi everyone!

I hope you're all doing well. Please take a moment to update to the latest version here: [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=DanielSanMedium.dscodegpt&ssr=false#overview).

Thank you!
