### ISSUE TITLE
Update AI21 model on extension

### ISSUE THREAD

**Issue by grizzlybearg** [davila7/code-gpt-docs#175]
Hi, So, I wanted to try out AI21 on codegpt but found two model `j2-grande-instruct` and `j2-jumbo-instruct`. However, AI21 documentation states that there are only 3 variants of ` encompasses three variants - Ultra, Mid, and Light. Can this be updated for the extension?

**Comment by judiniAI** [comment]
@grizzlybearg Do you have the AI21 Documentation for this models. Could you share the link?

**Comment by judiniAI** [comment]
@grizzlybearg 
We already have the j2 light, mid and ultra models!

They come in the next version. Thank you so much!

**Comment by grizzlybearg** [comment]
Thanks
