### ISSUE TITLE
Transfer API key between syncthinged VSCode installations

### ISSUE THREAD

**Issue by traits** [davila7/code-gpt-docs#176]
I have a portable VS Code "Installation" on Windows, using syncthing to sync this installation between different machines. This does not work very well with a stored OpenAI API key. Some or all local VSCode instances start making requests for a key update after synchronization. There seems to be some machine-dependent token involved in CodeGPT's or VSCodes procedure for storing this information. Is there any way to solve or work around this problem - perhaps the ability to identify a configuration file that can be excluded from synchronization, or even some other form of key storage? An environment variable (like the OpenAI API can do)?

**Comment by PilarHidalgo** [comment]
It seems like you're having trouble with synchronizing your OpenAI API key across different machines using a portable VS Code installation. The API key is typically stored in the settings of the VS Code extension, which might not be synchronized across different machines.

One workaround could be to manually enter the API key each time you switch machines. However, I understand this might not be the most convenient solution.

As for storing the key in an environment variable, while this is a common practice for managing sensitive information like API keys, currently, the CodeGPT extension does not support this feature.

If you want to exclude a specific configuration file from synchronization, you might want to look into the 'settings.json' file of VS Code, where extension settings are typically stored. However, please be aware that manipulating this file might affect other VS Code settings and extensions as well.
