### ISSUE TITLE
problem with answers

### ISSUE THREAD

**Issue by Dmont188** [davila7/code-gpt-docs#178]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by PilarHidalgo** [comment]
Hi everyone!

I hope you're all doing well. Please take a moment to update to the latest version here: [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=DanielSanMedium.dscodegpt&ssr=false#overview).

Thank you!
