### ISSUE TITLE
Problem with dialog text color

### ISSUE THREAD

**Issue by AnatolyZZZ** [davila7/code-gpt-docs#179]
At some moment instead of white/light-grey color for text prompts my Code GPT started using dark grey color, so it is very difficult to read.
Screenshot:
<img width="642" alt="Снимок экрана 2023-08-15 в 17 25 45" src="https://github.com/davila7/code-gpt-docs/assets/42940380/8b9860d8-f9f6-4b92-9b62-7b06f4eb0caa">

**Comment by AnatolyZZZ** [comment]
Using Dark Modern color theme if it is relevant, but changing to any theme except light doesn't help

**Comment by davila7** [comment]
<img width="466" alt="Captura de pantalla 2023-10-03 a las 16 27 40" src="https://github.com/davila7/code-gpt-docs/assets/6216945/6392bc6b-ac27-4e7d-a52b-98f65f5129d1">


Could you try with the last version (2.1.26)
