### ISSUE TITLE
can't install  codegpt extension because it is not compatible with the current version of vscode 1.73.0

### ISSUE THREAD

**Issue by IlyesAtoui** [davila7/code-gpt-docs#18]
![image](https://user-images.githubusercontent.com/89246725/214683455-850a1c21-333d-407b-9d47-2c73fc9d54ca.png)
v

**Comment by davila7** [comment]
The next version will have support for VSCode 1.73.0.

I will update it during the week

**Comment by IlyesAtoui** [comment]
> The next version will have support for VSCode 1.73.0.
> 
> I will update it during the week

Thanks Daniel
