### ISSUE TITLE
Possible to use ollama codellama:13b?

### ISSUE THREAD

**Issue by DaveSanders** [davila7/code-gpt-docs#183]
I noted that the base codellama, and the 34b are available, but not 13b.

Is there a way to add that to the list?

**Comment by ishaan-jaff** [comment]
Hi @DaveSanders  I’m the maintainer of LiteLLM - we allow you to create a proxy server to call 100+ LLMs, and I think it can solve your problem (I'd love your feedback if it does not)

Try it here: https://docs.litellm.ai/docs/proxy_server

## Using LiteLLM Proxy Server
```python
import openai
openai.api_base = "http://0.0.0.0:8000/" # proxy url
print(openai.ChatCompletion.create(model="test", messages=[{"role":"user", "content":"Hey!"}]))
```

## Creating a proxy server 
Ollama models
```shell
$ litellm --model ollama/llama2 --api_base http://localhost:11434
```

Hugging Face Models 
```shell
$ export HUGGINGFACE_API_KEY=my-api-key #[OPTIONAL]
$ litellm --model claude-instant-1
```


Anthropic 
```shell
$ export ANTHROPIC_API_KEY=my-api-key
$ litellm --model claude-instant-1
```
Palm

```shell
$ export PALM_API_KEY=my-palm-key
$ litellm --model palm/chat-bison
```

**Comment by davila7** [comment]
@DaveSanders @ishaan-jaff 

Codellama:13B will be available in version 2.1.26

**Comment by sourasis** [comment]
when will codellama:7b be available in vscode ?

**Comment by davila7** [comment]
@DaveSanders 
codellama:13b is now available in the latest version

@sourasis 
codellama is the same as codellama:7b so you can use that model and it will be exactly the same
