### ISSUE TITLE
 How to enter the Api key

### ISSUE THREAD

**Issue by sanfootball** [davila7/code-gpt-docs#184]
I can’t enter the API key, because the field indicated in the instructions only accepts the provider for chat through the drop-down list, it is preset. And there’s simply no way to enter your own text! Tell me how to enter the key.

**Comment by davila7** [comment]
To add the API key you must enter the command "cmd + shift + p" and look for the "Set API Key" command

Check this link: https://docs.codegpt.co/docs/tutorial-basics/installation#get-your-api-key
