### ISSUE TITLE
add new models as per latest update

### ISSUE THREAD

**Issue by nikhil-swamix** [davila7/code-gpt-docs#193]
![image](https://github.com/davila7/code-gpt-docs/assets/54004431/8bbb1639-95f7-4726-a46f-fd2aabeea164)

**Comment by PilarHidalgo** [comment]
Hi everyone!

I hope you're all doing well. Please take a moment to update to the latest version here: [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=DanielSanMedium.dscodegpt&ssr=false#overview).

Thank you!
