### ISSUE TITLE
Is selection of GPT4All Model in extension settings relevant?

### ISSUE THREAD

**Issue by fhg-isi** [davila7/code-gpt-docs#194]
Hello, I would like to use CodeGPT with GPT4All. In the extension settings there is a property "model" and I am wondering, if it is relevant for GPT4All. 

I already selected a model in the GPT4All GUI (GPT4All Falcon) and enabled the API in the settings of the GPT4All gui. 

I am not able to select the model "GPT4ALL Falcon" in the CodeGPT extension settings. The only model that seems to be related is "gpt4all-j-v1.3-groovy"

=> Is the selection of a model in CodeGPT not relevant at all when using GPT4All, because I already make a seleciton in the GPT4All gui?

=> Or do I need to exactly use the "gpt4all-j-v1.3-groovy" model and otherwise, CodeGPT would not work for GPT4All?

Please clarify the relevance of the model selection for the different API providers in the documentation at:

https://docs.codegpt.co/docs/tutorial-basics/configuration#model

Furthermore, I would like to be able to run VsCode on a differnt computer than the model and I am wondering, how I could specify so in the CodeGPT extension settings. Related: https://github.com/davila7/code-gpt-docs/issues/133#issuecomment-1597283259

If its curently only possible to use GPT4All provider on the same server, please clarify so in the documentation at:
https://docs.codegpt.co/docs/tutorial-ai-providers/gpt4all

**Comment by fhg-isi** [comment]
Just saw that the documentation says:

```
GPT4All Models available in Code GPT

gpt4all-j-v1.3-groovy
vicuna-13b-1.1-q4_2
replit-code-v1-3b
```

Strangely, the selection gpt4all-j-v1.3-groovy worked, even If I use the Falcon model in GPT4 all. 

Therefore, I am still wondering how relevant the selection of the model is.

**Comment by PilarHidalgo** [comment]
Hi everyone!

I hope you're all doing well. Please take a moment to update to the latest version here: [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=DanielSanMedium.dscodegpt&ssr=false#overview).

Thank you!
