### ISSUE TITLE
Code does not format correctly in VS Code

### ISSUE THREAD

**Issue by xmjiao** [davila7/code-gpt-docs#195]
When trying CodeGPT Chat in VS Code, I encountered two issues. I will describe the first issue here and will create a separate issue for the second.

Neither the input nor the output code was formatted properly in VS Code. The following is a screenshot:

<img width="650" alt="Screenshot 2023-11-09 at 7 06 26 PM" src="https://github.com/davila7/code-gpt-docs/assets/364752/b8aa4199-13f4-47b6-8e19-a48941f51b90">

I used VS Code 1.84.2 on Mac. 
The version of Code GPT: Chat & AI Agents was v2.2.3.
The GPT model was `gpt-4-1106-preview`

**Comment by PilarHidalgo** [comment]
I'm sorry to hear that you're having trouble with the formatting in CodeGPT Chat. Here are a few things you could try:

Ensure that your VS Code is updated to the latest version. The minimum required version for CodeGPT is 1.85.

Check if you have any other extensions installed that might interfere with the formatting of the code. You can try disabling other extensions to see if the problem persists.

Try to reset the settings of the CodeGPT extension to their default values. You can do this by going to the Extensions tab in VS Code, finding the CodeGPT extension, and clicking on the gear icon to access the settings.

If none of the above solutions work, you might want to reinstall the CodeGPT extension.

If you're still experiencing issues after trying these steps, please provide more details about the problem, such as the specific formatting issues you're encountering and any error messages you might be seeing.
