### ISSUE TITLE
"Copy all" button copies "Stop responding"

### ISSUE THREAD

**Issue by xmjiao** [davila7/code-gpt-docs#196]
When trying CodeGPT Chat in VS Code, I encountered two issues. I described the first issue in another issue I am creating a separate issue for the second.

When clicking on the "Copy all" button to the far right of the CodeGPT icon, it copies "Stop responding", even after the output has been fully generated.

I used VS Code 1.84.2 on Mac. 
The version of Code GPT: Chat & AI Agents was v2.2.3.
The GPT model I used was gpt-4-1106-preview

**Comment by PilarHidalgo** [comment]
Hi everyone!

I hope you're all doing well. Please take a moment to update to the latest version here: [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=DanielSanMedium.dscodegpt&ssr=false#overview).

Thank you!
