### ISSUE TITLE
Feature: Add option to add Azure OpenAI for autocompletions

### ISSUE THREAD

**Issue by ashutoshdtu** [davila7/code-gpt-docs#197]
Request to add support for Azure's OpenAI API in completions as well.

**Comment by PilarHidalgo** [comment]
CodeGPT already supports Azure's OpenAI API. You can connect your Microsoft Azure account to CodeGPT by following these steps:

Create an account in Microsoft Azure.
Get access to Azure OpenAI Services.
Go to Azure OpenAI Studio.
Get your Secret Key and the Custom Link.
Go to VSCode and choose Azure as Provider.
Set connection on 🔑 button.
Paste your API Key and click on Connect.
Remember, if you want to remove your API Key from CodeGPT, select Edit Connection on 🔑, and click on Disconnect.
