### ISSUE TITLE
Feature: Make CodeGPT VSCode Extension Free Software Again

### ISSUE THREAD

**Issue by orkutmuratyilmaz** [davila7/code-gpt-docs#200]
Hello,

After creating the issue #199, I've decided to create a fork and a pull request for the project. Then, I've realized that this repository is a fork of [docusaurus](https://github.com/facebook/docusaurus) and the purpose of the repository is to update documentation of [CodeGPT](https://www.codegpt.co/). 

However, it is not my misunderstanding, because when I click on the issues link on [this extension's page at Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=DanielSanMedium.dscodegpt), it redirects me to this repository.

When we check the older versions like [1.0.6](https://open-vsx.org/extension/DanielSanMedium/dscodegpt/1.0.6), we can notice that the extension was licensed with [MIT License](https://openvsxorg.blob.core.windows.net/resources/DanielSanMedium/dscodegpt/1.0.6/LICENSE.md) and the repository was [public](https://github.com/davila7/codegpt.git).

Right now, the license is [404](https://marketplace.visualstudio.com/items/DanielSanMedium.dscodegpt/license) and former repository is too.

Can you solve the license and repository issues? It is a great extension and keeping it as a FLOSS will be the best choice, IMHO:)

Best,
Orkut

**Comment by nashishere** [comment]
+1

**Comment by ErtanOz** [comment]
+1

**Comment by soldatino13** [comment]
+1

**Comment by dmter** [comment]
+1

**Comment by flightlesstux** [comment]
+1

**Comment by isik5** [comment]
+1

**Comment by yaman** [comment]
use continue.dev: https://github.com/continuedev/continue it is OSS and much more configurable(e.g. you can set ollama url+port)
