### ISSUE TITLE
Vision input

### ISSUE THREAD

**Issue by grass29** [davila7/code-gpt-docs#201]
Are there plans to add vision? Ctrl-v and uploading images.

**Comment by grass29** [comment]
still not there...

**Comment by PilarHidalgo** [comment]
Hi everyone!

I hope you're all doing well. Please take a moment to update to the latest version here: [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=DanielSanMedium.dscodegpt&ssr=false#overview).


Now with Vision option :)

Thank you!
