### ISSUE TITLE
Feature: Add DeepSeek Coder to models

### ISSUE THREAD

**Issue by daniel-a-diaz** [davila7/code-gpt-docs#202]
DeepSeek Coder seems to be the next big model that is performing better than GPT-3.5-Turbo and CodeLlama-34B. Could you please add them to your supported models? Also, does there happen to be a way to add any model for use with CodeGPT?

**Comment by daniel-a-diaz** [comment]
Ollama just added DeepSeek Coder https://github.com/jmorganca/ollama/issues/1040#event-11017917085

**Comment by davila7** [comment]
It will come in the next version, probably next week

**Comment by ivanfioravanti** [comment]
DeepSeek is super!

**Comment by ivanfioravanti** [comment]
Please give possibility to select up to the 33b model

**Comment by davila7** [comment]
DeepSeek-coder is now available in version 2.2.5 🙌

**Comment by daniel-a-diaz** [comment]
It might be something more general with the 2.2.5 release, or maybe just the ollama models. I just switched it to wizardcoder:34b-python to ask the same question, which before had answered the prompt great, and it responded with this. And that is a temperature of 0.2, so it should have been more on target.
![image](https://github.com/davila7/code-gpt-docs/assets/107445915/72bde46c-be39-434e-bc25-5df0e843fcc4)

**Comment by rasterize-art** [comment]
please add the 6.7b-instruct model as well. per the big code llm leaderboard, its the best performing 7b parameter model:

[big Code Models Leaderboard - a Hugging Face Space by bigcode](https://huggingface.co/spaces/bigcode/bigcode-models-leaderboard)
