### ISSUE TITLE
BUG: GPT-4 model selector is wrongly pointing to GPT-3

### ISSUE THREAD

**Issue by gudzenkov** [davila7/code-gpt-docs#205]
**Description**
GPT-4 model selector is actually pointing to GPT-3 instead of `gpt-4-0613` (validated by direct model inquiry, overall question quality, context length and training dataset cut-off date)

`gpt-4-1106-preview` is also pointing to GPT-3 (see screenshot attached)
`gpt-4-32k` errors out `OpenAl API Response was: Error 404`
`gpt-3.5-turbo` (`gpt-3.5-turbo-1106`) is not responding at all, no API requests logged in https://platform.openai.com/usage)
`gpt-3.5-turbo-16k` (`GPT-3.5-turbo-16k-0613`) actually works. 

**Environment**:
- OpenAI API Key with enough credits & far from API rate limits (Tier 1, max ~10 RPM / 1000 TPM)
- CodeGPT plugin v2.2.3
- VSCode latest
```
Version: 1.84.2
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:52:57.054Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.1.0
```

<img width="1415" alt="CodeGPT-gpt-4" src="https://github.com/davila7/code-gpt-docs/assets/11720732/20f78fc6-29e5-475d-96cc-0b24895e7291">

<img width="1417" alt="CodeGPT-gpt-4-1106-preview" src="https://github.com/davila7/code-gpt-docs/assets/11720732/ccea8eab-cfdd-4f79-a121-976c120c5acb">

**Comment by PilarHidalgo** [comment]
Hi everyone!

I hope you're all doing well. Please take a moment to update to the latest version here: [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=DanielSanMedium.dscodegpt&ssr=false#overview).

Thank you!
