### ISSUE TITLE
Cmd + Shift + I is parsing empty string

### ISSUE THREAD

**Issue by Chimpaya** [davila7/code-gpt-docs#206]
macOS 14.0
vscode codeGPT extension v2.2.3

When I use cmd+shift+i to prompt from a comment in my .js file 
<img width="374" alt="image" src="https://github.com/davila7/code-gpt-docs/assets/43206064/0d435359-641e-4078-b2cb-57618fe19960">
Nothing is generated. This is what i saw in the codegpt chat:
<img width="471" alt="image" src="https://github.com/davila7/code-gpt-docs/assets/43206064/aef73eda-4160-4c6e-b8c2-1ab422bae3c3">

If i prompt directly in the chat, it works.

**Comment by davila7** [comment]
what model are you using ?

**Comment by PilarHidalgo** [comment]
Hi everyone!

I hope you're all doing well. Please take a moment to update to the latest version here: [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=DanielSanMedium.dscodegpt&ssr=false#overview).

Thank you!
