### ISSUE TITLE
[feature] when use local llm such as ollama, support custom host and port

### ISSUE THREAD

**Issue by swuecho** [davila7/code-gpt-docs#208]

**Comment by davila7** [comment]
working on this!

**Comment by qdrop17** [comment]
yeah, I'm hosting Ollama on a powerful PC (not on my notebook) but I'm not able to connect Code GPT to it.

Is there a workaround until this is natively supported?

**Comment by jpatters** [comment]
> Is there a workaround until this is natively supported?
You could proxy the requests from localhost:11434 to your custom host/port.

**Comment by mf-zf** [comment]
A dirty workaround: patch `extension.js` after extension installation. Replace the `http://localhost:11434` occurrences with the REST API URL of your compute machine.

The solution proposed by @jpatters is also a nice workaround since it is easy to set up with SSH port forwarding. It even provides a layer of transparent security.

**Comment by orkutmuratyilmaz** [comment]
#199

**Comment by acmol** [comment]
> yeah, I'm hosting Ollama on a powerful PC (not on my notebook) but I'm not able to connect Code GPT to it.
> 
> Is there a workaround until this is natively supported?

You can use iptables or sth else to port forwarding your localhost:11434 to remote host port.

I meet a more harder situation... My remote servers is on k8s, I connect to my server with ingress as proxy. Ingress use the hostname in HTTP requests to identify which backend it should proxy to, but the HTTP requests are made by this extension, it must be 127.0.0.1... 
I eventually had to set up a http reverse proxy server (mitmproxy with a special option to support streaming chunked encoding..., nginx may also work)

**Comment by thawkins** [comment]
Just add my desire to have this customizable, I run ollama as a rest service on a big server machine on my network.

**Comment by speedyankur** [comment]
You can Try GENIEAI extension, https://marketplace.visualstudio.com/items?itemName=genieai.chatgpt-vscode, it support custom open AI urls in settings

**Comment by speedyankur** [comment]
You can Try GENIEAI extension, https://marketplace.visualstudio.com/items?itemName=genieai.chatgpt-vscode, it support custom open AI urls in settings

**Comment by davila7** [comment]
@thawkins 

In the latest version 3.1.1 you can now use Customizable baseURL

<img width="508" alt="Captura de pantalla 2024-01-12 a las 08 25 59" src="https://github.com/davila7/code-gpt-docs/assets/6216945/a965b4e8-acb5-451e-83be-75e61249c453">

**Comment by speedyankur** [comment]
I tried configuring the API key and Proxy url. but not sure how and wehere to populate the models.

And if I dont select the models. I see an error.
<img width="562" alt="Screenshot 2024-01-12 at 14 43 45" src="https://github.com/davila7/code-gpt-docs/assets/1248020/c136f8dc-b0b0-46cd-bfcd-138fd9022672">
