### ISSUE TITLE
error Create a comment and leave the cursor at the end of the comment line

### ISSUE THREAD

**Issue by fragpit** [davila7/code-gpt-docs#21]
Hi, 
Looks line "Create a comment and leave the cursor at the end of the comment line" is a little bit generic. It's randomly appears with programming languages and always with YAML. 

I don't understand the problem is in my request or somewhere else?

**Comment by davila7** [comment]
Please update to version 1.0.13 which already supports YAML files

**Comment by davila7** [comment]
@fragpit  
I close the issue
I would be grateful if you can add a rating to the extension in the VSCode marketplace:
https://marketplace.visualstudio.com/items?itemName=DanielSanMedium.dscodegpt&ssr=false#review-details
