### ISSUE TITLE
No completion in editor but there is output in logs when using ollama + code llama

### ISSUE THREAD

**Issue by PRESIDENT810** [davila7/code-gpt-docs#210]
I'm using Ollama with code llama locally. I installed codeGPT plugin in VSCode and enabled it. However, there's no completion in the code editor, but I can see there's output from code llama in "output" tab:

<img width="1716" alt="image" src="https://github.com/davila7/code-gpt-docs/assets/44538064/3b0f32b0-7316-462b-a42c-8c07d5b4f907">

whereas I'm expecting something like this:
<img width="791" alt="image" src="https://github.com/davila7/code-gpt-docs/assets/44538064/ae90a1c3-c69b-40b6-a265-3ef1d6028632">

Did I configure it wrong? Or code llama doesn't support displaying completion in editor?

**Comment by Skybladev2** [comment]
Same for me. It does not even emit to Output tab since v.3.X

**Comment by PilarHidalgo** [comment]
Hi! you can follow the instructions here: https://docs.codegpt.co/docs/tutorial-ai-providers/ollama
