### ISSUE TITLE
Annoying "GPT-4 Free Trial!" Banner

### ISSUE THREAD

**Issue by moritz-t-w** [davila7/code-gpt-docs#214]
This banner at the top should have an x button. I've seen it. I don't want it. Now it's just annoying and not gonna make me want to buy your product but it's gonna make me annoyed of it.
![image](https://github.com/davila7/code-gpt-docs/assets/90388353/4fd980ac-25e5-43a6-9e83-c5ab115f6cf1)

**Comment by davila7** [comment]
@moritz-t-w 

There is a new version that will provide a better chat experience.
Will be updated in the next few days
