### ISSUE TITLE
HTML injection

### ISSUE THREAD

**Issue by moritz-t-w** [davila7/code-gpt-docs#215]
![image](https://github.com/davila7/code-gpt-docs/assets/90388353/d5bf2564-ca55-485e-be3d-306af5840cfe)
User input HTML should not get rendered, come on

**Comment by moritz-t-w** [comment]
![Screenshot from 2023-12-15 16-23-39](https://github.com/davila7/code-gpt-docs/assets/90388353/d0a76a6a-9bcf-46a0-a68e-b95cc74caade)
![Screenshot from 2023-12-15 16-23-45](https://github.com/davila7/code-gpt-docs/assets/90388353/7e14bbb3-34c6-426c-8cb8-4d37f3f7c095)
![Screenshot from 2023-12-15 16-24-17](https://github.com/davila7/code-gpt-docs/assets/90388353/e707c61f-0a08-42a8-a4ae-ed8ed8fbef85)

**Comment by moritz-t-w** [comment]
Bro is building a whole subscription model and ecosystem but hasn't even finished the most basic functionality :skull:

**Comment by davila7** [comment]
@moritz-t-w 

ChatGPT is free and will remain that way forever. The CodeGPT Plus version is paid and allows the entire team to continue working on the extension.

We are moving to a new version of the chat very soon that comes with all of this improved. Thank you for your comments, they help us continue improving the version and always make it FREE!

**Comment by moritz-t-w** [comment]
Oh I misinterpreted that banner. Thanks!
