### ISSUE TITLE
Render Math Text

### ISSUE THREAD

**Issue by saritbha** [davila7/code-gpt-docs#216]
The text window doesn't seem to render math formula, is this aa bug or the feature itself is lacking? And Im not able to copy texts, the windows clipboard is also looks empty after i try to copy text (not code), when I try to copy text, it copies "Stop" that's all. It also lacks the view for table representation.

**Comment by PilarHidalgo** [comment]
I'm sorry to hear that you're experiencing these issues. Let's address them one by one:

Math Formula Rendering: Currently, the CodeGPT chat window may not support the rendering of mathematical formulas. This is a limitation of the feature, not a bug. You might need to use a different tool or extension that supports math formula rendering in VSCode.

Copying Text: If you're having trouble copying text from the chat window, this could be a bug. Please ensure you're using the latest version of the CodeGPT extension and VSCode. If the issue persists, it would be helpful to report this to the CodeGPT team with specific details about your system and the steps you're taking when you encounter this issue.

Table Representation: Similar to the math formula rendering, the CodeGPT chat window might not support complex table views. You might need to view such data directly in your code or use a different tool to visualize it.
