### ISSUE TITLE
Code GPT can no longer see selected codes

### ISSUE THREAD

**Issue by ChukwukaUbani** [davila7/code-gpt-docs#218]
Code GPT Plus was able to see codes before on the VScode coding section and make corrections, but now, it can't see codes except it is typed directly in the chat box. 

I loved CodeGPT extension because of its ability to detect codes on the coding section, but now that has stopped, I won't be renewing my subscription, rather use the free ChatGPT

**Comment by PilarHidalgo** [comment]
@ChukwukaUbani thanks for the feedback, we would like to meet you to discuss about this problem, I'm sending you a link meeting to help you.

**Comment by diegor1vs** [comment]
After the last update, I have the same problem, for example, to create a unit test, the feature that allows selecting the code and calls "CodeGPT: Unit Test" is no longer working, and the same for any other call, the only option now is to copy and paste the code in the dialog box
<img width="456" alt="Screenshot 2024-01-08 at 09 00 18" src="https://github.com/davila7/code-gpt-docs/assets/117783393/1473b5a4-b99d-471b-8be1-e061856e3caf">

**Comment by marcel-hacklaender** [comment]
Same Problem. 

macOS 14.2.1
VSCode 1.85.1 
CodeGPT v3.1.3

**Comment by stf1981** [comment]
I think we have the same Problem.

Win **10**
VSCode **1.85.1**
CodeGPT **3.1.3** with **OpenAI** Provider and **GPT-4** Model

Previous version **2.2.10** works

**Comment by chaig15** [comment]
any updates on this issue? @PilarHidalgo . Without this feature the application is pretty much useless

**Comment by davila7** [comment]
Finally, we identified this problem that happens in some situations.

Thanks for reporting this bug
We are uploading a fix this week with the correction.

**Comment by davila7** [comment]
It is already fixed in version 3.1.7
