### ISSUE TITLE
The Google API key cannot be successfully used

### ISSUE THREAD

**Issue by ThirvenGree** [davila7/code-gpt-docs#219]
When I finished setting up the Google API key, it kept showing failure when I tried to use it.

**Comment by yicheng-He** [comment]
Same issue is seen.
Popup: fetch error.

**Comment by davila7** [comment]
Try downloading the latest version of CodeGPT (v3.1.4)

You can follow this tutorial: https://youtu.be/iSFMrkYVopg?si=iz8aIAg8MUReU3Zl
