### ISSUE TITLE
Couldn't find the option to select the new model  added in ollama

### ISSUE THREAD

**Issue by lavahasif** [davila7/code-gpt-docs#221]
![image](https://github.com/davila7/code-gpt-docs/assets/22430922/46944e74-7717-45f6-8ef4-11c0bc410fdd)

I installed the llama2 ,tinyllama .etc model. I couldn't find the option to select the model .

os:windows (wsl - Ubuntu)

**Model Missing .**
https://ollama.ai/library/tinyllama
https://ollama.ai/library/llama2

**Comment by davila7** [comment]
@lavahasif 

Now you don't need to select the model, just delete the mistral option and write the name of the model that you downloaded from Ollama.

The model is a selectable and writable field.

**Comment by itopaloglu83** [comment]
Thank you @davila7
But this was not clear with the interface, I had to find this issue to change the model. It is far better to keep the model in the settings as well.

**Comment by davila7** [comment]
> Thank you @davila7 But this was not clear with the interface, I had to find this issue to change the model. It is far better to keep the model in the settings as well.

Thank you!
We are trying to improve the interface a lot to support new features like Vision or Code Interpreter.

Some changes will come but we will try to keep them as few as possible.
