### ISSUE TITLE
CodeGPT v.3.1.3 does not work with ollama

### ISSUE THREAD

**Issue by senovr** [davila7/code-gpt-docs#226]
Gents, 
I have an issue with CodeGPT and ollama.

CodeGPT v3.1.3
Ollama version 0.1.22
ollama is running on 127.0.0.1:11434
I pulled mixtral with ollama pull mixtral, and it is working via ollama run mixtral in bash.

In codeGPT settings, I choosed ollama as a provider.

When I am trying to do any task in the codegpt chat, I am getting:
![image](https://github.com/davila7/code-gpt-docs/assets/20754344/51b59771-c8e9-460e-9619-80b9f5ba6a02)

Any ideas/workaround/suggestions?

**Comment by PilarHidalgo** [comment]
Hi!, you can fix this issue turn off and turn on again Ollama,  we still working on this bug. Try it and tell us how is going. 
![image](https://github.com/davila7/code-gpt-docs/assets/37567214/3313605a-45a2-4cb4-9d76-fc983359397a)
