### ISSUE TITLE
Configure code language and framework

### ISSUE THREAD

**Issue by danielmessi13** [davila7/code-gpt-docs#23]
Basically when asking to generate a test code for me, it generates it but it's not in the language I'm programming, I think that both for this functionality and for others that generate code it would be valid to have an option to select the language of the code and maybe the framework too

**Comment by davila7** [comment]
@danielmessi13 
Could you add a code example?

**Comment by dnovatchev** [comment]
@davila7 Does CodeGPT support C# coding at present? Any examples? If negatives, what are the plans to add such a feature?

**Comment by davila7** [comment]
@dnovatchev 
C# projects are supported by CodeGPT

I leave you an example:
<img width="956" alt="Captura de Pantalla 2023-02-05 a la(s) 5 12 08 p  m" src="https://user-images.githubusercontent.com/6216945/216848889-18ee0e97-8763-4c93-ae8b-8cd07172489e.png">

**Comment by dnovatchev** [comment]
Wow... Great, thank you!

Maybe it would be good clearly to state this fact in the Redme.md and articles, or otherwise you will have many other people bothering you and wasting your time with the same question!

**Comment by davila7** [comment]
Yes, soon I will add the Blog section in the documentation to start uploading articles on how to use CodeGPT with different technologies.

Thanks for the suggestion.
