### ISSUE TITLE
Cannot set API key for OpenAI and GPT-4 model for autocomplete

### ISSUE THREAD

**Issue by thexray** [davila7/code-gpt-docs#230]
**Description**
I am following this instructions:

`Select an AI provider and enter your [API Key] press cmd+shift+p (mac) ctrl+shift+p (windows) and search for 'CodeGPT: Set API KEY'.`

I select "OpenAI" in "Code GPT: Api Key" list, press ctrl+shift+p, enter "CodeGPT: Set API KEY", but cannot see an appropriate entry (image 1).

Additionally, there is no model "gpt-4" in the "Code GPT.Autocomplete Provider" list (image 2).

**Environment**
* CodeGPT plugin v2.2.3
* VSCode latest v3.1.7
```
Version: 1.86.0 (user setup)
Commit: 05047486b6df5eb8d44b2ecd70ea3bdf775fd937
Date: 2024-01-31T10:28:19.990Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045
```
**Image 1**

![image](https://github.com/davila7/code-gpt-docs/assets/7498609/bc225f82-983e-4f25-af97-14d57183e477)
**Image 2**

![image](https://github.com/davila7/code-gpt-docs/assets/7498609/c289aa7d-5e4d-4a8a-8c97-5a052b8588a5)

**Comment by PilarHidalgo** [comment]
Hi! try to do it by the menu: 
![image](https://github.com/davila7/code-gpt-docs/assets/37567214/527dc592-021b-4a27-9cd2-07bf15ad90f1)

**Comment by TannerLow** [comment]
Where do I find the popup? Can you provide a link to the website where I can set the connection to OpenAI?

**Comment by JinHwi** [comment]
so do i i can't find CodeGPT : Set API Key

**Comment by JinHwi** [comment]
![image](https://github.com/davila7/code-gpt-docs/assets/11894259/5c7bd08f-cb21-483e-add6-6fbda78b5934)

**Comment by JinHwi** [comment]
![image](https://github.com/davila7/code-gpt-docs/assets/11894259/b437cc15-c0b4-469a-bbab-5e5c2c21a833)

**Comment by JinHwi** [comment]
where is new dialog window? how to we open this window in vs code?

**Comment by Andric34** [comment]
I have the same problem, it's like the extension isn't properly installed or something. A lot of commands are missing SET API KEY being one of them resulting in codeGPT window having only black screen. CodeGPT extension version 3.2.0 and vscode version 1.86.2

**Comment by gyaaniguy** [comment]
same problem

**Comment by PilarHidalgo** [comment]
Hi guys no need to  Set API Key like that, just follow these instructions:  https://www.youtube.com/watch?v=yErnyqXobcI
