### ISSUE TITLE
I can't find GPT4All 

### ISSUE THREAD

**Issue by mike2003** [davila7/code-gpt-docs#231]
How to connect GPT4All ?
It's not in the providers.
If you select it in the settings, it doesn't work and resets.
It's not in the autocomplete settings either.
https://docs.codegpt.co/docs/tutorial-ai-providers/gpt4all

**Comment by PilarHidalgo** [comment]
Hello! no need to set up GPTAll, since you can use GPTAll models from CodeGPT Plus or OpenAI as provider
