### ISSUE TITLE
Get error: Failed to fetch the chat response

### ISSUE THREAD

**Issue by xavax31** [davila7/code-gpt-docs#232]
Hi, 
I can't get codeGPT extension to work in vscode (on macbook 14' m1). It returns this error at each request: "Failed to fetch the chat response". I had the api key firstly use command set api key, and then using the set connection panel. Something weird is that pasting the api key doesn't seem to work, the field input stays empty with placeholder 'Api key'.  I then selected provider openai and model turbo 3.5 (same problem with 4).
Making a request with same key using curl works.
Any suggestion?

**Comment by mateusmacedo** [comment]
The same thing is happening to me. When selecting the CodeGPT Plus provider and putting it in try mode it works perfectly. This makes me wonder if I'm losing my right to choose and being held hostage by the plugin's paid model. This really disappoints me and I believe all other users; If this is the case this is truly absurd.
<img width="552" alt="Captura de Tela 2024-02-09 às 21 42 03" src="https://github.com/davila7/code-gpt-docs/assets/25123805/5104ad0e-22b5-4a7b-beb6-b4b996f4d55b">
<img width="552" alt="Captura de Tela 2024-02-09 às 21 42 45" src="https://github.com/davila7/code-gpt-docs/assets/25123805/49f77c3a-c084-4824-aadc-0cc2d71f5dfc">

**Comment by xavax31** [comment]
@mateusmacedo, I don't think that is the same issue, my error is specific 'Failed to fetch the chat response'. May be it could be better that you open rather a new issue?
There are my snapshots for more details:
<img width="533" alt="Capture d’écran 2024-02-10 à 12 07 36" src="https://github.com/davila7/code-gpt-docs/assets/4051022/08164de3-2101-4d8a-9914-69b8b77b479e">
<img width="533" alt="Capture d’écran 2024-02-10 à 12 08 07" src="https://github.com/davila7/code-gpt-docs/assets/4051022/c357744c-f035-4257-ba4f-1f4cca19fb7c">

The video just shows that copying/pasting the key seems to do nothing.

https://github.com/davila7/code-gpt-docs/assets/4051022/ff848f71-521c-41dd-8c9c-69337b912fa8

**Comment by PilarHidalgo** [comment]
@xavax31 and @mateusmacedo , thank you for writing us, We are working on this issues, we keep informed as soon as will be resolver it.

**Comment by PilarHidalgo** [comment]
@xavax31 and @mateusmacedo, we fix this, could you please check again?

**Comment by xavierboisnon** [comment]
Perfect, it's ok for me now ! thanks

**Comment by mateusmacedo** [comment]
Awesome!!! hi really corrected, thank you very much.

**Comment by nekineroni** [comment]
> @xavax31 and @mateusmacedo, we fix this, could you please check again?

i have the same problem

**Comment by mateusmacedo** [comment]
I'm using the latest version, it works perfectly.

**Comment by chanmaoganda** [comment]
observed on wsl2 ubuntu20.04

**Comment by wqd008** [comment]
observed on wsl2 ubuntu20.04
