### ISSUE TITLE
CodeGPT listens on a different port than announced (VSCodium flatpak)

### ISSUE THREAD

**Issue by handlebargh** [davila7/code-gpt-docs#235]
This may be related to #234 

I'm running CodeGPT 3.2.0

codeGPT announces to bind to port `54112` on localhost. However, on my machine (running VSCodium as flatpak) it seems to bind on port `54113` on localhost. If I try to redirect port `54113` to `54112` I get a "Not Found" message in the extension's window.

![Screenshot1](https://github.com/davila7/code-gpt-docs/assets/153601029/57f490d5-1110-4345-8756-17e5697d7473)

codeGPT listens on my public interface as well (which in this case is my wifi card):

![Screenshot2](https://github.com/davila7/code-gpt-docs/assets/153601029/fb8300af-c5d4-41fe-a5be-907088046811)

If I redirect from this interface to `localhost:54112` codeGPT works. So at the moment my workaround looks like this:

1. Start VSCodium (but do not open the codeGPT window immediately)
2. Run this socat command to redirect traffic:
    ```
    sudo socat tcp-listen:54112,reuseaddr,fork,bind=127.0.0.1 tcp:192.168.0.144:54112
    ```
3. Use codeGPT

This leads me to 2 questions:

1. Why does codeGPT bind to a different port than it announces on localhost? I currently don't suspect the flatpak being responsible since it runs in host network mode.
2. Is there a way to restrict codeGPT to listen on localhost only?

**Comment by PilarHidalgo** [comment]
Hi @handlebargh , could you share the source where we announce that ports? So far I now, we don't have that information publicly.

**Comment by octrow** [comment]
@PilarHidalgo I'm experiencing a similar issue. I'm also using WSL2 (Ubuntu 22.04), and the CodeGPT extension seems to be opening the login and signup pages on a different port than the one announced - http://localhost:54112/login. This aligns with the behavior reported in this issue.

**Comment by clintonruairi** [comment]
same issue here. Just bought a subscription and it won't connect

**Comment by djacquensf9** [comment]
> Hi @handlebargh , could you share the source where we announce that ports? So far I now, we don't have that information publicly.

I found this response to be appalling! 
@handlebargh probably found how to resolve a problem that has been bothering many users of your solution, and all you seem to care about is where the ports are announced

**Comment by PilarHidalgo** [comment]
Hi everyone, sorry for the misunderstanding, thank you @handlebargh for the description of the solution. Shortly, we will be communicating about being able to use other extensions in parallel without problems.

**Comment by clintonruairi** [comment]
Has this issue been fixed @PilarHidalgo ?
