### ISSUE TITLE
Autocomplete is not working

### ISSUE THREAD

**Issue by itsAbhirup** [davila7/code-gpt-docs#236]
Autocomplition of code is not working

**Comment by PilarHidalgo** [comment]
@itsAbhirup , you have a screenshot to understand your problem?. Also I recommend to you our docs: https://docs.codegpt.co/docs/tutorial-features/code_autocompletion

**Comment by suhonen91** [comment]
It is not working. I am unable to enable it from the settings. It does not turn on. Neither I can select example Ollama Deepseek-coder. It just defaults to "plus"

**Comment by PilarHidalgo** [comment]
Indeed, we are improving the autocomplete option, we will have updates soon.
