### ISSUE TITLE
command 'CodeGPT: Set API KEY' resulted in an error ( command 'codegpt.setApiKeyGPT' not found)

### ISSUE THREAD

**Issue by IlyesAtoui** [davila7/code-gpt-docs#24]
![image](https://user-images.githubusercontent.com/89246725/215099906-f7a4ca36-2fe6-46c9-9ff6-0f94fcb68f49.png)

**Comment by davila7** [comment]
Could you post the version of VSCode and the version of CodeGPT that you are using?

**Comment by IlyesAtoui** [comment]
vscode : 1.73.0 and codeGpt : 1.0.13
![image](https://user-images.githubusercontent.com/89246725/215104659-dc63ca08-2b61-4866-9430-79cf4dd908cf.png)

**Comment by davila7** [comment]
You could try the following:
cmd+shift+p
Search "Ask CodeGPT"
Write any question and then "enter".

It should show the input to add the API Key

**Comment by IlyesAtoui** [comment]
> You could try the following: cmd+shift+p Search "Ask CodeGPT" Write any question and then "enter".
> 
> It should show the input to add the API Key

thanks Daniel, that's work :D , thanks for creating the extension too <3

**Comment by davila7** [comment]
> > You could try the following: cmd+shift+p Search "Ask CodeGPT" Write any question and then "enter".
> > It should show the input to add the API Key
> 
> thanks Daniel, that's work :D , thanks for creating the extension too <3

Cool!

I will review the code so that the SET API Key can work correctly. Thanks for the info!

**Comment by DrewMcArthur** [comment]
just leaving a note that this same problem and solution happened/worked for me on VSCode version 1.72.1 and CodeGPT v1.0.15.  thanks!

**Comment by davila7** [comment]
> just leaving a note that this same problem and solution happened/worked for me on VSCode version 1.72.1 and CodeGPT v1.0.15. thanks!

thank! I will check for the next version 1.0.16

**Comment by luizantoniojr** [comment]
Hello guys! 

Similar error herer:

![image](https://user-images.githubusercontent.com/9661479/227597065-ff4efc8f-8295-44c3-910e-39c5209f2853.png)

Command 'CodeGPT: Set API KEY' result in an error
"Not enough memory resources available to process this command" 

VSCode version:

![image](https://user-images.githubusercontent.com/9661479/227597568-76be8bbf-0b42-45cd-8c65-4222374820f2.png)

Extension version: v2.1.1

**Comment by davila7** [comment]
@Skubenyk  could you translate your error message?

**Comment by Skubenyk** [comment]
this command resulted in an error

**Comment by inter1965** [comment]
> Hello guys!
> 
> Similar error here:
> 
> ![image](https://user-images.githubusercontent.com/9661479/227597065-ff4efc8f-8295-44c3-910e-39c5209f2853.png)
> 
> Command 'CodeGPT: Set API KEY' result in an error "Not enough memory resources available to process this command"
> 
> VSCode version:
> 
> ![image](https://user-images.githubusercontent.com/9661479/227597568-76be8bbf-0b42-45cd-8c65-4222374820f2.png)
> 
> Extension version: v2.1.1
run below in powershell under windows
`cmdkey /list | Select-String -Pattern "LegacyGeneric:target=(vscode.+)" | ForEach-Object { cmdkey.exe /delete $_.Matches.Groups[1].Value }`

**Comment by regex5440** [comment]
Help!!
Facing the same error after hitting Enter for `CodeGPT: Set API KEY` command.
Error Screenshot:
><img width="335" alt="image" src="https://github.com/davila7/code-gpt-docs/assets/34965581/495aeee0-1855-4cae-9ee5-71d181d96dfb">

Visual Studio Software Info Screenshot:
><img width="298" alt="image" src="https://github.com/davila7/code-gpt-docs/assets/34965581/890b49f1-964a-4e23-8716-09f92d117cc0">

Extension Screenshot v2.1.13
><img width="451" alt="image" src="https://github.com/davila7/code-gpt-docs/assets/34965581/ff6b10ec-4bb8-442a-b881-f7dd3a53ce85">

**Comment by ayungkeiron** [comment]
Hi
I have the same problem, i tried the solutions cmd+ship+p... but its still dont work, can somebody helpme??


<img width="1963" alt="image" src="https://github.com/davila7/code-gpt-docs/assets/127903456/82345571-ad0b-4b36-9766-cd70f21079e2">


<img width="1963" alt="image" src="https://github.com/davila7/code-gpt-docs/assets/127903456/2f488e65-6036-47f3-a040-f0b5d7795847">

**Comment by AliFahed** [comment]
Hey Everyone, 

To work around this issue, after installing Code GPT, I clicked the dropdown next to uninstall, and then from the options choose 'Install another version...', this worked for me. I installed v2.2.10 just to test and it worked. Make sure to try to install recent version of the extension and then try set api key, if not then try the same process with a previous version.

![image](https://github.com/davila7/code-gpt-docs/assets/90851899/90b51f58-f826-4890-87e8-d7e984d0b07a)

![image](https://github.com/davila7/code-gpt-docs/assets/90851899/338740d9-7aa7-478e-a0c5-09df309a4573)

![image](https://github.com/davila7/code-gpt-docs/assets/90851899/51a48bb6-79b9-4c84-8500-3c7805099cb5)

![image](https://github.com/davila7/code-gpt-docs/assets/90851899/1402b6cd-08b2-461f-a9a0-841a2d982645)


Visual Studio Code, Version: 1.75.1

**Comment by geweb7** [comment]
the same problem and solution didn't work neither for 3.0.21 version nor for 2.2.10
VSCode 1.75.1

![image](https://github.com/davila7/code-gpt-docs/assets/1274645/2dd0d0e8-cd2b-4a0b-a58d-d6016cfa819d)

**Comment by andrewlpvs** [comment]
No result found for CodeGPT: Set API KEY, in the command pallette.
Rolled back to an older version as another person suggested. 
Setting was found. Key was pasted, nothing happened. 
Tried the "Ask CodeGPT" approach. Entered a question, was prompted to log in.  404 Error.  

Very sad.

**Comment by ybalkind** [comment]
> No result found for CodeGPT: Set API KEY, in the command pallette. Rolled back to an older version as another person suggested. Setting was found. Key was pasted, nothing happened. Tried the "Ask CodeGPT" approach. Entered a question, was prompted to log in. 404 Error.
> 
> Very sad.

Same
