### ISSUE TITLE
Extension settings incoherent

### ISSUE THREAD

**Issue by traits** [davila7/code-gpt-docs#241]
Code: 1.87.2. Windows portable

~~This happens at least for a default provider (does such a concept even exist?) as well as for chat windows settings. In the first case after  restarting code, always "Select a Model" is selected. for the second one Window Memory, Max Tokens, and Temperature are back to default.~~

Also the extensions vscode settings are not helpful here. They are incoherent BTW,  "CodeGPT.apiKey" has no functionality and the corresponding help text is misleading, there is no 'Code GPT: Api Key' command. But this might also be outdated info, considering the documentations remark regarding 'Secret Storage'.

p.s. First part is working now, no idea why. Renamed the issue to reflect the settings part.

**Comment by PilarHidalgo** [comment]
@traits thanks for writing us, Could you send a picture about the problem?, because the current features doesn't include CodeGPT: Api Key. Please install the last version 3.2.2. 
![image](https://github.com/davila7/code-gpt-docs/assets/37567214/1f8a4f48-dbce-43f0-82e2-43d165fde61d)

**Comment by ItsReddi** [comment]
I just installed the extension version: 3.2.3
I think he meaning this:
![grafik](https://github.com/davila7/code-gpt-docs/assets/3147888/3fef3881-5ab0-41fa-a3e3-cd0466fb4d5e)

**Comment by PilarHidalgo** [comment]
@ItsReddi Yes, but as I mentioned, in this version it is not necessary to use the Set API Key. You can connect directly from the Set Connections button.
