### ISSUE TITLE
Login prompting is extremely annoying

### ISSUE THREAD

**Issue by TonyGravagno** [davila7/code-gpt-docs#242]
This prompt opens with every new project/workspace and the directive to turn off notifications is not respected.  
Please allow us to turn it off, or explain why we should maintain a permanent login when not using CodeGPT Plus.

![image](https://github.com/davila7/code-gpt-docs/assets/499473/0045c340-c05b-4f42-a017-65e6ab888485)

![image](https://github.com/davila7/code-gpt-docs/assets/499473/6a556727-e6fa-49fa-838b-e155c20abf97)

**Comment by davila7** [comment]
It must be a VSCode issue, as it should not ask again if you disable the notification.

We will submit the issue to the VSCode team to fix it in the next update.
