### ISSUE TITLE
error

### ISSUE THREAD

**Issue by alien-arnab-009** [davila7/code-gpt-docs#244]
{"error":"Non active subscription"}
it's showing there

**Comment by jeremiah1201** [comment]
Same, paid, reinstalled plug-in on VSCode, logged in, still give me the Non active subscription. 
Tried on another computer, still no luck. 
What else should I do?

**Comment by PilarHidalgo** [comment]
@jeremiah1201 @alien-arnab-009 We've noticed your account issues in the inbox on the Discord channel. Please reach out to our team here: https://discord.gg/6pCdgcre
