### ISSUE TITLE
fetch is not defined

### ISSUE THREAD

**Issue by HuyPham52** [davila7/code-gpt-docs#248]
Type: <b>Bug</b>

I'm trying to install CodeGPT chat, but getting the issue

Extension version: 3.0.21
VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T17:05:47.808Z)
OS version: Darwin arm64 23.1.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Pro (11 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 2, 2|
|Memory (System)|36.00GB (0.16GB free)|
|Process Argv|--crash-reporter-id 67d4dbbb-6b61-4713-be91-ca575a240181|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
bg6jg535:30979843
ccp2r6:30993542
dsvsc020:30976470
pythonait:30996668
dsvsc021:30996838
gd77d436:30999572

```

</details>

**Comment by PilarHidalgo** [comment]
@HuyPham52 Hi!, you need to update the VSCode to 1.85 or more and tge CodeGPT extension to 3.2.3

**Comment by Charlie0314** [comment]
@PilarHidalgo That works, thank you!
