### ISSUE TITLE
404 {type:error,error:{type:not_found_error,message:model: claude-3-haiku-20240229}} while selecting haiku as model

### ISSUE THREAD

**Issue by padmanabanSampath** [davila7/code-gpt-docs#249]
404 {type:error,error:{type:not_found_error,message:model: claude-3-haiku-20240229}}, bcoz the model available is haiku 20240307

**Comment by davila7** [comment]
thanks!
It is already corrected in version 3.2.5 that will be published during the week

**Comment by padmanabanSampath** [comment]
thanks....can you propose a way to user configure the model name instead of hard-coded, then in code completion model selection how to use haiku and opus
