### ISSUE TITLE
Error in Swift: Create a comment and leave the cursor at the end of the comment line

### ISSUE THREAD

**Issue by ineilzhang** [davila7/code-gpt-docs#25]
Hi，is Swift supported?

**Comment by davila7** [comment]
Hi @ineilzhang 

Swift files only have the extension .swift ? or is there another extension?
With that information, I can add support for this type of file in the next version 1.0.14

**Comment by davila7** [comment]
@ineilzhang
Please update the extension to version 1.0.14

This version already supports .swift files

**Comment by ineilzhang** [comment]
@davila7 Yeah, it works in version 1.0.14. Thanks a lot.

**Comment by davila7** [comment]
Cool!
I would be very grateful if you can rate the extension on the Visual Studio Code marketplace.
https://marketplace.visualstudio.com/items?itemName=DanielSanMedium.dscodegpt&ssr=false#review-details

Thanks!
