### ISSUE TITLE
CodeGPT: {error: Non active subscription}???

### ISSUE THREAD

**Issue by anna-pet** [davila7/code-gpt-docs#251]
i have had subscription for 2 days ago and used codeGPT active in my coding. since yesterday I have error: CodeGPT: {error: Non active subscription}???

![codeGPT_error_2](https://github.com/davila7/code-gpt-docs/assets/74401247/80ef6f41-10ef-4130-8069-0bf82c30f9ee)

Even i have loged in:
![codeGPT_error](https://github.com/davila7/code-gpt-docs/assets/74401247/25815a60-4a93-4d6f-b7b9-c0c3126a935f)

and i have CodeGPT installed:
![codeGPT_installed](https://github.com/davila7/code-gpt-docs/assets/74401247/6f80d3fa-8e9a-45a4-988c-3ca58b467af5)

what happened yesterday?

**Comment by PilarHidalgo** [comment]
Hello! please open an appointment with us to help you here: https://calendly.com/pilar-hidalgo

**Comment by anna-pet** [comment]
![image](https://github.com/davila7/code-gpt-docs/assets/74401247/a12cf69f-30b9-4466-ad0d-f382555c6799)

**Comment by PilarHidalgo** [comment]
@anna-pet after our meeting, we've conclude that the error was due to your free-trial ends. But you can create a new free account from https://app.codegpt.co/en/account/subscription.
