### ISSUE TITLE
fail to fetch the chat response from ollama codellama on wsl of ubuntu 18.04.

### ISSUE THREAD

**Issue by bitlgy** [davila7/code-gpt-docs#253]
![image](https://github.com/davila7/code-gpt-docs/assets/2434332/928330cf-2295-4cee-b383-1a46e91e0c65)
In the above pic, codellama (on the local wsl running ubuntu 18.04) has reponsed code-gpt's request, but code-gpt show a error "fail to fetch the chat response".

**Comment by PilarHidalgo** [comment]
Hello! please ensure that Ollama is running locally and download the model that you are using 
![image](https://github.com/davila7/code-gpt-docs/assets/37567214/2e24c680-5fab-48f8-89e6-c39f2e8317ac)

**Comment by PilarHidalgo** [comment]
Hello! please ensure that Ollama is running locally and download the model that you are using

**Comment by PilarHidalgo** [comment]
@bitlgy  I made a procedure on WSL here: https://medium.com/p/881b91ba193e. Hope works for you
