### ISSUE TITLE
CodeGpt v3.2.5 not work with ollama (on windows)

### ISSUE THREAD

**Issue by GhosTHaise** [davila7/code-gpt-docs#254]
Hello everyone, I'm using codegpt v3.2.5 with ollama on windows.When i try to send one prompt , It says that ollama is not running even if ollama is running on the background like in the picture bellow :
![image](https://github.com/davila7/code-gpt-docs/assets/68249758/b7c98528-26c8-4248-8034-06b1d74b7f8f)
Is there a way to fix this ?

**Comment by PilarHidalgo** [comment]
Hi @GhosTHaise, please follow this instructions to connect Ollama properly https://docs.codegpt.co/docs/tutorial-ai-providers/ollama

**Comment by PilarHidalgo** [comment]
Hello! please ensure that Ollama is running locally and download the model that you are using
![image](https://github.com/davila7/code-gpt-docs/assets/37567214/aa49730a-b21e-4bc5-a090-67d74bdef064)

**Comment by GhosTHaise** [comment]
![image](https://github.com/davila7/code-gpt-docs/assets/68249758/fb6e9541-4a5d-4d05-a6cf-8307c618d043)
@PilarHidalgo , @davila7  , @gustavoespindola  , @psmyrdek  My ollama is running on the background and model is already download . 
Is there a specific host(ip address like 127.0.0.1 as localhost) or specific port that I should config to ollama that codeGpt is listning?

**Comment by GhosTHaise** [comment]
> Hello! please ensure that Ollama is running locally and download the model that you are using ![image](https://private-user-images.githubusercontent.com/37567214/322685349-aa49730a-b21e-4bc5-a090-67d74bdef064.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1NTM1NjYsIm5iZiI6MTcxMzU1MzI2NiwicGF0aCI6Ii8zNzU2NzIxNC8zMjI2ODUzNDktYWE0OTczMGEtYjIxZS00YmM1LWEwOTAtNjdkNzRiZGVmMDY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDE5MDEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljNzk2MDJhMmRhZGM5YmE3NTc1NTg2YWZhYTc2ZjdmNjM1MTZiMTc4YzA4ZmFmNzRhMjNiOTNiOGZkYzAzNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.39LmMCiVryqLJFSW7GHfL18LhKVhb9NS0G88KwkBf-0)

Finally , i have found a solution for my issues. We need to remove manual OLLAMA_HOST to system environment variables and let the default 👍  .
