### ISSUE TITLE
Not compatible with 1.70.0?

### ISSUE THREAD

**Issue by SeaDude** [davila7/code-gpt-docs#26]
Trying to install from within VS Code. 

**Error**:

![image](https://user-images.githubusercontent.com/8636973/215304233-41b362d8-13b3-407b-9c2f-f3fac677dea7.png)

**Ideas?**

**Comment by davila7** [comment]
It currently supports version 1.73.0 or higher.
I'm working with the VSCode team to lower the versions.

You can update your VSCode or wait for the extension to be backward compatible.

**Comment by SeaDude** [comment]
Coo! Updated to 1.74.3 and it installed.

Can't wait to try it!

Thank you!

**Comment by davila7** [comment]
Great!
If you have any problem or query you can open an issue and I will help you.

I would be grateful if you leave a rating on the VSCode marketplace.
https://marketplace.visualstudio.com/items?itemName=DanielSanMedium.dscodegpt&ssr=false#review-details

Regards
