### ISSUE TITLE
Model name is wrong in Autocomplete

### ISSUE THREAD

**Issue by gidorah** [davila7/code-gpt-docs#261]
In model selection drop-down list there is a model named llama3:8b-instruct. But maybe it should be llama3:instruct since there is no model named llama3:8b-instruct in ollama repo.

**Comment by Facug03** [comment]
Hi, you can use this command to copy a model that you have and put the name you want

![imagen](https://github.com/davila7/code-gpt-docs/assets/107658697/d72f0488-8442-4fba-82ef-4df421c7e5e4)

it worked for me but the completions it gaves me are pretty bad

**Comment by gidorah** [comment]
Thank you, it worked! But as you said it is really bad.
