### ISSUE TITLE
Something went wrong! Try again

### ISSUE THREAD

**Issue by RJBcas** [davila7/code-gpt-docs#264]
![error](https://github.com/davila7/code-gpt-docs/assets/25237453/542d58cd-3b92-4f2e-bcd9-7e3759ccfb31)

**Comment by PilarHidalgo** [comment]
Hello @angelbarrera92 and @COOLIRON2311! Could you please upgrade Node.js to version 20? Afterward, follow the instructions provided in this link: https://docs.codegpt.co/docs/tutorial-features/code_autocompletion. Please note that you'll need to configure the other providers, which are not CodeGPT, with your personal API Keys.

**Comment by Adel242** [comment]
Hello, could you provide us with more details about the problem, such as how it occurred or originated? With this information, we can better track it to assist you.

**Comment by PilarHidalgo** [comment]
@RJBcas  If you update to the latest version, you will not experience this issue again. :)
