### ISSUE TITLE
web and local extentio fail on vs code server remotely

### ISSUE THREAD

**Issue by billyjeanrae** [davila7/code-gpt-docs#267]
web and local extentio fail on vs code server remotely

error: localhost refused connection

**Comment by riccardo-unipg** [comment]
![image](https://github.com/davila7/code-gpt-docs/assets/117158780/6fe66514-d33c-4e90-9de2-afeff18f5eb7)

**Comment by PilarHidalgo** [comment]
@riccardo-unipg , please set the meeting to help you https://calendly.com/pilar-hidalgo

**Comment by PilarHidalgo** [comment]
> web and local extentio fail on vs code server remotely
> 
> error: localhost refused connection

https://calendly.com/pilar-hidalgo

**Comment by PilarHidalgo** [comment]
@riccardo-unipg Hi! thanks for let us know, could you please explain to us, how you resolved? or set a meet with me here, I'll appreciate your feedback. https://calendly.com/pilar-hidalgo

**Comment by riccardo-unipg** [comment]
Yeah, once logged in with my credentials in web interface , the problem went away and the extension started working

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________
