### ISSUE TITLE
Unable to connect to the extension services. Click here to check possible reasons.

### ISSUE THREAD

**Issue by Mengzhiyaa** [davila7/code-gpt-docs#268]
When I install codegpt on remote linux VSCode, it raise this error `Unable to connect to the extension services.
[Click here](vscode-webview://0a5bjoemc2tb2nnffe84gm1eihp5hh75dhncb6hg7f8j0nfnv4nf/index.html?id=367e90d6-7251-4019-8d7f-0e982306cf7a&origin=53b7c042-d9aa-41c7-83cc-12239b12678c&swVersion=4&extensionId=DanielSanMedium.dscodegpt&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app&remoteAuthority=ssh-remote%2Bmaster&purpose=webviewView#) to check possible reasons.`  but in local vscode, it can be opened normally.
<img width="273" alt="image" src="https://github.com/davila7/code-gpt-docs/assets/82879383/957d02b1-f274-459c-8576-f20b85ed0c02">

**Comment by ignacorp** [comment]
Same here

**Comment by acetechnologist** [comment]
same issue:(

**Comment by xamelion** [comment]
I really want to use the plugin. But it doesn't open in devcontainer

**Comment by KnightKevin** [comment]
me too

**Comment by mbaltar** [comment]
Same here.

**Comment by apro** [comment]
Same problem:
Linux Rocky 9, VSCode 1.89
Server seems to kind'a work:
tcp        0      0 192.168.67.99:54112     0.0.0.0:*               LISTEN     
tcp6       0      0 :::54113                :::*                    LISTEN   
(ipv6 is disabled btw)

but do not listen on localhost.

logs from code:
[2922766:0507/081227.672055:INFO:CONSOLE(656)] "%c  ERR color: #f33 [Extension Host] Error: No open ports found in between 54112 and 54112
	at /home/apro/.vscode/extensions/danielsanmedium.dscodegpt-3.2.11/dist/extension.js:475:3792
	at /home/apro/.vscode/extensions/danielsanmedium.dscodegpt-3.2.11/dist/extension.js:471:2675
	at I2 (/home/apro/.vscode/extensions/danielsanmedium.dscodegpt-3.2.11/dist/extension.js:471:6194)
	at D (/home/apro/.vscode/extensions/danielsanmedium.dscodegpt-3.2.11/dist/extension.js:471:6121)
	at /home/apro/.vscode/extensions/danielsanmedium.dscodegpt-3.2.11/dist/extension.js:471:5910
	at /home/apro/.vscode/extensions/danielsanmedium.dscodegpt-3.2.11/dist/extension.js:475:3192
	at Server.I (/home/apro/.vscode/extensions/danielsanmedium.dscodegpt-3.2.11/dist/extension.js:475:1673)
	at Object.onceWrapper (node:events:631:28)
	at Server.emit (node:events:517:28)
	at emitListeningNT (node:net:1851:10)
	at process.processTicksAndRejections (node:internal/process/task_queues:81:21)", source: vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (656)

**Comment by Mayorc1978** [comment]
I get the same problem if I "click" the link it asks to open the example.com URL, which obviously works.

If I try to signing in the top right corner of the extension tab the extension tries to connect to:
`http://localhost:54112/54113/login`

But it doesn't seem to work:
![image](https://github.com/davila7/code-gpt-docs/assets/32271686/54bffb58-3c28-4a91-93c9-1e49a2a84fb0)

**Comment by PilarHidalgo** [comment]
@Mayorc1978 @apro @Mengzhiyaa In Linux the port must be able,  the http://localhost:54112/54113/login works for me 
![image](https://github.com/davila7/code-gpt-docs/assets/37567214/8aa23b22-e275-4f72-b590-69a44110db6c)

![image](https://github.com/davila7/code-gpt-docs/assets/37567214/5ca0b81a-3113-4afb-bd58-94838836026f)

**Comment by Mengzhiyaa** [comment]
@PilarHidalgo Hello, thank you for your answer. I tried to install codegpt today and found that it can be opened normally on a remote Linux server, which may be due to an update of codegpt. My server is running Ubuntu 22.04.

**Comment by PilarHidalgo** [comment]
@Mengzhiyaa I made a procedure on  WSL here: https://medium.com/p/881b91ba193e. Hope works for you
