### ISSUE TITLE
Getting error 429

### ISSUE THREAD

**Issue by aravindnc** [davila7/code-gpt-docs#27]
OpenAI API Response was: Error: Request failed with status code 429. More information about this error: https://www.codegpt.co/docs/tutorial-basics/api_errors

**Comment by davila7** [comment]
> OpenAI API Response was: Error: Request failed with status code 429. More information about this error: https://www.codegpt.co/docs/tutorial-basics/api_errors

You must click on the error link:
https://www.codegpt.co/docs/tutorial-basics/api_errors

<img width="694" alt="Captura de Pantalla 2023-01-31 a la(s) 9 53 25 a  m" src="https://user-images.githubusercontent.com/6216945/215794628-12696d7a-426f-4013-8ed8-f39ce937e715.png">

Then select the OpenAI errors and you can see the 429 errors:

<img width="836" alt="Captura de Pantalla 2023-01-31 a la(s) 9 53 05 a  m" src="https://user-images.githubusercontent.com/6216945/215794677-a923399c-ddf9-4808-908e-e6d10152e379.png">
