### ISSUE TITLE
Error Message when using OpenIA provider

### ISSUE THREAD

**Issue by romulow22** [davila7/code-gpt-docs#273]
After last update (v3.3.19) Im receiving bellow error when i use any model from OpenAI provider.

This started happening after i changed the max_tokens value and now every value that i set in it giver this error

Alert: Openai Message

400 Invalid type for 'max_tokens': expected an integer, but got a string instead.

**Comment by davila7** [comment]
Thank you! It will be fixed in the next version

**Comment by davila7** [comment]
It is already fixed in version 3.3.20

**Comment by davila7** [comment]
Update and then restart VSCode, then update the max_token and it should be working now
