### ISSUE TITLE
Unable to configure CodeGPT with Azure OpenAI provider

### ISSUE THREAD

**Issue by filip-be** [davila7/code-gpt-docs#277]
Hi!

It looks like it is not possible to configure CodeGPT with Azure OpenAI anymore.

CodeGPT extension version: v3.3.25
VSCode version: 1.89.1

Provider configuration:
![image](https://github.com/davila7/code-gpt-docs/assets/3452394/379495c1-cf29-4537-94ef-dc7c201c7531)

Models are not available for selection:
![image](https://github.com/davila7/code-gpt-docs/assets/3452394/80393e59-caae-44d7-aac9-f6f21dacf433)

Chat returns connection error:
![image](https://github.com/davila7/code-gpt-docs/assets/3452394/b5165f35-03ed-4c55-9411-4e92cfe3de70)

**Comment by davila7** [comment]
@filip-be 
the problem is that you are entering the incomplete URL. We updated the documentation with a better description of how to get data from Azure

Please check this link: https://docs.codegpt.co/docs/tutorial-ai-providers/microsoft-azure

**Comment by filip-be** [comment]
Thanks @davila7, I've managed to configure chat completion successfully!
Could you also tell if CodeGPT supports Autocomplete (Completion API/Copilot) with Microsoft Azure OpenAI provider? I don't see this on the list and there seems to be no way to configure it manually.
