### ISSUE TITLE
Add azure provider to autocomplete list

### ISSUE THREAD

**Issue by castletaste** [davila7/code-gpt-docs#278]
Add the Azure provider selection to the autocomplete selector list
![VSCodium KW5hZfwD Monday](https://github.com/davila7/code-gpt-docs/assets/74972418/40580892-6292-4e2f-884d-680267fa8117)

**Comment by PilarHidalgo** [comment]
Hello, thank you for writing. We will look over your feedback. To follow up on your concern, please add it to our Canny roadmap. https://codegpt.canny.io/requests
