### ISSUE TITLE
Auto-complete errors with ollama, Chat works fine

### ISSUE THREAD

**Issue by geoffgs** [davila7/code-gpt-docs#279]
Using ollama with any model produces the same results for auto-complete, quiet failures. Meanwhile the Llama-Coder extension has no trouble and the CodeGPT Chat works fine. Seems like a CodeGPT-specific problem I haven't figured out how to resolve. 

**Steps to Reproduce**: 
- Setup CodeGPT per https://docs.codegpt.co/docs/tutorial-ai-providers/ollama and https://docs.codegpt.co/docs/tutorial-features/code_autocompletion with ollama
- Ensure no other LLM auto-completes are active
- Create a comment and CMD+SHIFT+I or simply wait for an auto-complete to fail

**Expected Behavior**:
- Auto-completion of any kind

**Actual Behaviour**:
- Silent failures

**Environment**:
MacOS Sonoma 14.4.1
CPU: M2 Pro
RAM: 32GB

VSCode:  1.89.1 (Universal)
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:14:24.611Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2 - I noticed a [recommendation](https://github.com/davila7/code-gpt-docs/issues/265#issuecomment-2083292733) for Node 20, but this is what VSCode ships with for Mac
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0

CodeGPT: 3.3.25
ollama: 0.1.32
Models: codellama, deepseek-coder

**Other Logs**:
From Extension Host after a CMD-SHIFT-I
```
[Extension Host] TypeError: Cannot read properties of undefined (reading 'globalState')
    at cz (/Users/some.user/.vscode/extensions/danielsanmedium.dscodegpt-3.3.25/dist/extension.js:515:412)
    at M8 (/Users/some.user//.vscode/extensions/danielsanmedium.dscodegpt-3.3.25/dist/extension.js:517:15)
```

From VSCode Output > CodeGPT Autocomplete, same repeated message with any key strokes :
`[{timestamp}] completion provider = Ollama`

From VS Code DevTools Console, when switching context a Python tab:
```
[Extension Host] CodeGPT Language Change 
{langID: 'python', lang: 'super-secret-code.py', activeTextEditor: {…}}
activeTextEditor: {document: {…}, selection: {…}, selections: Array(1), visibleRanges: Array(1), options: {…}, …}
lang: "super-secret-code.py"
langID: "python"
[[Prototype]]: Object
```

**Comment by geoffgs** [comment]
Found the bug on my end, wholly unrelated. Apologies.

**Comment by mitchins** [comment]
@geoffgs am experiencing the exact same, would be helpful if you shared your resolution.
