### ISSUE TITLE
CodeGPT crashes when opening large file

### ISSUE THREAD

**Issue by ffaa3dd** [davila7/code-gpt-docs#280]
**Description:** When I try to open a large file (over 20MB) in CodeGPT, the application crashes immediately.

**Steps to Reproduce:**

1-Open CodeGPT
2-Go to File > Open.
3-Select a file larger than 20MB.
4-Click Open.

**Expected Behavior:** CodeGPT should open the large file without crashing.

**Actual Behavior**: CodeGPT crashes with an error message saying, "Application has stopped working."

**Environment:**

OS: Windows 11
CodeGPT Version: 1.2.3
Memory: 32GB
Processor: Intel i7

**Comment by PilarHidalgo** [comment]
@ffaa3dd Hi! Did this happen to you from Playground or the extension? This information is crucial to understanding the issue and helping you.
Also, I understand that you're experiencing issues when trying to open large files in CodeGPT. However, it's important to note that the maximum file upload size in CodeGPT is 20MB. This limit is set to ensure optimal performance and prevent system overloads. If you need to work with larger files, I would recommend breaking them down into smaller chunks before uploading. This approach can help improve processing speed, resource utilization, and error handling.

If you continue to experience issues, please ensure that your system meets the minimum requirements for running CodeGPT and that you're using the latest version of the application.

**Comment by danielatik** [comment]
Hi @ffaa3dd ! The last version of CodeGPT is 3.3.23. I think the CodeGPT you're using is not our CodeGPT.

This is our version with more than 1.2 MM downloads:
https://marketplace.visualstudio.com/items?itemName=DanielSanMedium.dscodegpt&ssr=false#overview

Could you confirm us you are using our CodeGPT?
