### ISSUE TITLE
can't connect my codegpt account

### ISSUE THREAD

**Issue by LinYunling** [davila7/code-gpt-docs#281]
![image](https://github.com/davila7/code-gpt-docs/assets/14899416/c55eb701-db13-4651-a888-73c9b22839eb)

sign in, and connect in web, but it doen't work.

![image](https://github.com/davila7/code-gpt-docs/assets/14899416/f6d6b9f8-6f7f-48eb-bff0-51980aa3dc67)

**Comment by LinYunling** [comment]
my vscode info:
Version: 1.89.1 (user setup)
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:13:33.891Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by PilarHidalgo** [comment]
@LinYunling, I apologize for the misunderstanding. Yesterday, we had issues updating information. I'm attaching the screenshot of the extension now. Free accounts have limited interactions, so the "fetch failed" error appears.  
![image](https://github.com/davila7/code-gpt-docs/assets/37567214/fdc00554-5723-4155-8668-c8170b451079)
