### ISSUE TITLE
Crashes and communication problems after 01/06/2024

### ISSUE THREAD

**Issue by brunojet** [davila7/code-gpt-docs#282]
Since 06/01/2024 I have had problems with the plugin in VsCode. The chat stopped responding and started showing the attached screen. If I access the chat via AndroidStudio it works, but very slow. I use the openai platform and the chat within the platform works correctly.

![image](https://github.com/davila7/code-gpt-docs/assets/40765738/ef7903b8-a4da-4653-9da2-f9570bff7adc)

**Comment by PilarHidalgo** [comment]
I understand that you are experiencing issues with the extension. To ensure everything works correctly, please provide information about the versions of Node, VS, and the extension you are using.

Additionally, if you use the Free plan account, as shown in the image, you may have exhausted your daily interactions. Furthermore, it is necessary to connect the account from the playground. You can follow the tutorial below: https://www.youtube.com/watch?v=yErnyqXobcI

**Comment by PilarHidalgo** [comment]
@brunojet Also, if you want to use other OpenAI models, you can follow the tutorial below. https://docs.codegpt.co/docs/tutorial-ai-providers/openai
