### ISSUE TITLE
Add disable option for "Add to CodeGPT Chat (Ctrl + Shift + E)" when mark code

### ISSUE THREAD

**Issue by stf1981** [davila7/code-gpt-docs#283]
Hello,
in Version 3.3.30 everytime when i mark code for copy & paste a suggestion are showed for "Add to CodeGPT Chat (Ctrl + Shift + E)".
Can you add a disable option for that, please. I like to use CodeGPT but this is to me too obtrusive. 
thx

**Comment by danstan5** [comment]
Hi, just FWI I've had to roll back to an earlier version (3.3.25) for now so I can continue using VSCode & CodeGPT without this popping up everywhere. Looking forward to a fix - thanks

**Comment by SenseiMarv** [comment]
@PilarHidalgo I updated to version 3.3.36 now but still see the text whenever marking anything. I didn't find any option to turn it off, how was it fixed in v3.3.33? Am I supposed to do anything to turn it off? Thanks for trying to fix it quickly.

**Comment by sucat** [comment]
Same. I'm on `v3.3.36` and can see this annoying prompt.
<img width="385" alt="image" src="https://github.com/davila7/code-gpt-docs/assets/7252341/6e62f575-85ad-433a-85c9-67493fa4c7f0">
<img width="424" alt="image" src="https://github.com/davila7/code-gpt-docs/assets/7252341/f4c72b6e-4e8a-41b2-9ea9-f9c33e733412">

**Comment by stf1981** [comment]
Same here. @PilarHidalgo reopen the issue, please. thx

**Comment by dylan-k** [comment]
I would also like to know how to disable or hide this annoying popup that happens any time i select anything in the editor. Until then, I'll follow the example from comments here, and roll back to an earlier version.

**Comment by PilarHidalgo** [comment]
@dylan-k @stf1981 @sucat @danstan5 Hi guys, I'll communicate this to my team, thanks in advance.

**Comment by dylan-k** [comment]
`v3.4.10 (pre-release)` and it's still there...
It's really annoying, and what's also annoying is that this issue was closed as "completed" as though a promise to communicate about an issue is the same thing as resolving an issue.

**Comment by sucat** [comment]
`v3.4.12` and it's still there. Could you clearly state which version will get the issue sorted? I raised it: https://codegpt.canny.io/requests/p/add-disable-option-for-add-to-codegpt-chat

**Comment by dylan-k** [comment]
In the `v3.4.17 (pre-release)` it looks like they have it removed.

**Comment by davila7** [comment]
We finally removed the message in this latest version.

We had planned to do it in previous versions but there were other advances in the roadmap that we had to comply with.

Don't forget to update the scores in the marketplace and messages in Canny

Thank you for your messages, we continue to improve with all the feedback you give us
