### ISSUE TITLE
Connect to Custom Dialog will not accept pasted text?

### ISSUE THREAD

**Issue by OldishCoder** [davila7/code-gpt-docs#290]
I'm trying to set up a custom AI provider.
I have the API key and I have the URL... but there is no way to paste them into the dialog:
![image](https://github.com/davila7/code-gpt-docs/assets/142182836/bbdb2349-2024-40de-ba97-0a5766595d15)
The paste buttons do not work and ctrl-v does not work either.

Is there some other place to enter these? A text file? The windows registry?

This pic shows what I see in the overall options page:
![image](https://github.com/davila7/code-gpt-docs/assets/142182836/f7cd3916-c46d-480d-8f78-1cc63170187c)
There is not a setting 'CodeGPT: Set API KEY' - I do not see any way to add keys... did the install fail or something?

Running on windows 10 with VSCode 1.90.0

**Comment by PilarHidalgo** [comment]
Hi! thanks for reporting this; I will mention it to my team

**Comment by OldishCoder** [comment]
I just installed yesterday. v3.4.0.  After I rebooted, I can access the settings, so maybe it was a stale configuration... this seems to be working...

**Comment by OldishCoder** [comment]
Good to close...
