### ISSUE TITLE
You exceeded your current quota, please check your plan and billing details

### ISSUE THREAD

**Issue by ashishtele** [davila7/code-gpt-docs#3]
![image](https://user-images.githubusercontent.com/14126898/213841408-513f6a75-e15e-4d0c-a62b-b1e28a47a970.png)

I am getting the above error when trying to run any command. What can be the probable reason?

**Comment by davila7** [comment]
You must add credits to your OpenAI account.

Go to https://openai.com/api/ and check your account status.

**Comment by ashishtele** [comment]
Thank you. I have been using a Free trial account.
