### ISSUE TITLE
Always get : OpenAI API Response was: Error: Request failed with status code 429. 

### ISSUE THREAD

**Issue by vivtiw** [davila7/code-gpt-docs#30]
I have VSCode: 1.74.3 version
CodeGPT: 1.0.14 ( Tried with 1.0.13)

I always get 429 requests ( ask CodeGPT, Ask Stackoverflow, cmd-shift-i..) despite not sending any requests successfully. 
My plan is free and there is certain amount of requests I can send. I am not sure what can the problem be.
![image](https://user-images.githubusercontent.com/2409997/216194471-a97b584f-339f-441d-a50f-f10dec349e9f.png)

**Comment by davila7** [comment]
This is the error link from the OpenAI page

https://help.openai.com/en/articles/6891831-error-code-429-you-exceeded-your-current-quota-please-check-your-plan-and-billing-details

**Comment by Relicus** [comment]
I have full qouta remaining and on plus plan but still receive the 429 error. Tried everything.

**Comment by Relicus** [comment]
![image](https://user-images.githubusercontent.com/34719091/219278439-9937d64d-deb1-4035-a1e4-df7474273a6f.png)

**Comment by Relicus** [comment]
Found the solution. Thanks!
