### ISSUE TITLE
sk-gISMgVGEbXXXXXXX API could not process the query, try selecting the code and using Ask CodeGPT to write your own query

### ISSUE THREAD

**Issue by jtagaca** [davila7/code-gpt-docs#32]
I'm getting this error despite selecting a code block, I've been using this extension for a month now and I love it but a week ago this just started to happen, anyway you can help with this?

Thanks!

**Comment by davila7** [comment]
In the last update, the provider type was added in Settings (OpenAI or Cohere).

This means that the API Key is no longer saved in Settings (to improve security) and now you must select the Provider, follow the steps below to correct this problem:

Check the settings.json
[VSCode Setting Json](https://code.visualstudio.com/docs/getstarted/settings?fbclid=IwAR1wqZxrGQxvktk0Bhnl4JVjf0C5h7S7ZcRzIQj_L3_2LA4TWMc10FKbLkc#_settingsjson)

Change the value of the API Key to OpenAI or Cohere
and then enter your API Key like this:
[Set API Key](https://www.codegpt.co/docs/tutorial-basics/installation?fbclid=IwAR3w_qdkpcMuEZobXyWIoArNwxW0ZgOHnvdE37MqfD6Eu3-_rhHdmcxFXFw#use-your-api-key)

You will now be able to use OpenAI or Cohere as a provider and store the API Key securely.
I will be adding more AI providers soon 🙌

**Comment by jtagaca** [comment]
Hi it still gives the same error 

![image](https://user-images.githubusercontent.com/63562250/216852607-00afbe87-9c87-4c4a-be38-ba16c2f04fe9.png)

anything else I can do? I tried reinstalling but same issue occurs

**Comment by davila7** [comment]
Try this to reload the extension:

https://stackoverflow.com/questions/42002852/how-to-restart-vscode-after-editing-extensions-config

**Comment by jtagaca** [comment]
Still doesn't work, I even uninstalled it and installed again.

**Comment by jtagaca** [comment]
I installed other Chat gpt extensions and they all work with the app key but this extension just doesn't work, even though this is my favorite :(

**Comment by davila7** [comment]
If you install and uninstall an extension in VSCode the settings.json file keeps saving the same data.

You can use this extension that allows you to reload the window:
https://marketplace.visualstudio.com/items?itemName=natqe.reload

**Comment by jtagaca** [comment]
still no go, I think that reloading is not the issue.

**Comment by davila7** [comment]
I think it's VSCode caching setting.json values.
Anyway, in the next update, I will fix that bug if VSCode keeps the cache.

**Comment by davila7** [comment]
> Hi it still gives the same error
> 
> ![image](https://user-images.githubusercontent.com/63562250/216852607-00afbe87-9c87-4c4a-be38-ba16c2f04fe9.png)
> 
> anything else I can do? I tried reinstalling but same issue occurs

@jtagaca I hid the image since your API Key could be seen, I recommend that you delete it and create a new one.

**Comment by jtagaca** [comment]
got it thanks a lot!

**Comment by davila7** [comment]
@jtagaca 
I was able to replicate the error.

I tried to change the provider but the change didn't take place as I had VSCode open twice with two different projects.
You could try just open a VSCode window, change the settings, then cmd+shift+p, search for Developers: Reload Windows and use a Code GPT feature again

**Comment by jtagaca** [comment]
it works now thanks a lot!
