### ISSUE TITLE
OpenAI API Response was: Error: Request failed with status code 407. More information about this error: https://www.codegpt.co/docs/tutorial-basics/api_errors

### ISSUE THREAD

**Issue by vuhongthien** [davila7/code-gpt-docs#33]
help

**Comment by davila7** [comment]
It seems you are using proxy.
You can check this article to solve the problem.

https://softwareengineering.stackexchange.com/questions/348449/407-proxy-authentication-required#:~:text=The%20407%20error%20was%20probably,should%20authenticate%20with%20the%20proxy.
