### ISSUE TITLE
When I ask something in Chat GPT I receive empty answer 

### ISSUE THREAD

**Issue by Swashh** [davila7/code-gpt-docs#35]
<img width="590" alt="Снимок экрана 2023-02-09 в 14 38 10" src="https://user-images.githubusercontent.com/48477935/217815931-1d888a00-0d9e-45ea-b837-c0cd3c604528.png">

For example, I asked to explain any row of code, but then I got just nothing

**Comment by davila7** [comment]
Could you write an example of the line of code you are trying to explain

**Comment by Swashh** [comment]
@davila7 
<img width="1200" alt="Снимок экрана 2023-02-10 в 11 14 21" src="https://user-images.githubusercontent.com/48477935/218051888-d5ee9928-4ac4-488b-b753-822d11050c3a.png">
<img width="1162" alt="Снимок экрана 2023-02-10 в 11 10 30" src="https://user-images.githubusercontent.com/48477935/218051896-7d660f8d-22d6-429f-8967-8eea96293631.png">

**Comment by davila7** [comment]
@Swashh you have to select the code and then right click and select Explain CodeGPT.

<img width="941" alt="Captura de Pantalla 2023-02-10 a la(s) 10 18 14 a  m" src="https://user-images.githubusercontent.com/6216945/218127863-4b323426-a817-4322-88ce-56f385d974a6.png">
