### ISSUE TITLE
429 Error

### ISSUE THREAD

**Issue by ensarduman** [davila7/code-gpt-docs#36]
I am getting 429 error message;

OpenAI API Response was: Error: Request failed with status code 429. More information about this error: https://www.codegpt.co/docs/tutorial-basics/api_errors

**Comment by davila7** [comment]
@ensarduman

If you click on the url of the error you will be able to see the 429 errors of the OpenAI API
<img width="691" alt="Captura de Pantalla 2023-02-13 a la(s) 11 37 16 a  m" src="https://user-images.githubusercontent.com/6216945/218517125-24bfdd80-dbb6-48b0-aab6-9170a969d5f2.png">

You should review each error and see how to fix it.

Important:
If you are going to use the connection with OpenAI you must have credits in your account.
Read this section:
https://www.codegpt.co/docs/intro#important
