### ISSUE TITLE
Error para cambiar el idioma al Code GPT

### ISSUE THREAD

**Issue by x-chama-x** [davila7/code-gpt-docs#37]
sistema operativo: Windows 10
Versión de VSCode: 1.75.1

Imagen del error: 
![image](https://user-images.githubusercontent.com/67705754/218616720-ac1ff89e-dc67-4ad3-a91d-8920a9a99895.png)
lo quiero cambiar a español y me aparece eso:
![Captura](https://user-images.githubusercontent.com/67705754/218616628-595f4e11-5305-4704-a464-e9917c82e9b1.PNG)
si aprieto ese cartel me sale esto:
![image](https://user-images.githubusercontent.com/67705754/218617088-47ca0492-be43-43e3-9f25-a97d8291055c.png)

nose que hacer...

Versión de CodeGPT: v1.0.15

**Comment by davila7** [comment]
@x-chama-x 
Tu archivo settings.json esta mal fomateado, puede ser por la falta de una coma.

revisa este artículo para corregirlo:
https://code.visualstudio.com/docs/getstarted/settings#_common-questions

**Comment by x-chama-x** [comment]
Lo pude solucionar, te agradezco la ayuda. Saludos crack!

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: Daniel ***@***.***>
Enviado: jueves, 16 de febrero de 2023 12:46 a. m.
Para: ***@***.***>
CC: Francisco ***@***.***>; ***@***.***>
Asunto: Re: [davila7/code-gpt-docs] Error para cambiar el idioma al Code GPT (Issue #37)


@x-chama-x<https://github.com/x-chama-x>
Tu archivo settings.json esta mal fomateado, puede ser por la falta de una coma.

revisa este artículo para corregirlo:
https://code.visualstudio.com/docs/getstarted/settings#_common-questions
