### ISSUE TITLE
CodeGPT VSCode

### ISSUE THREAD

**Issue by enjofaes** [davila7/code-gpt-docs#38]
Perhaps this is already an issue related to another open one. But got this response: "OpenAI API Response was: Error [ERR_SOCKET_CLOSED]: Socket is closed" when trying to ask codeGPT to generate a code.

**Comment by davila7** [comment]
This could be due to a variety of reasons, such as an unstable internet connection or a firewall blocking the connection.

Could you try with another internet connection to discard these reasons
