### ISSUE TITLE
CodeGPT in vs code does not work after install github copilot with labs

### ISSUE THREAD

**Issue by RobertoMartinCaccia** [davila7/code-gpt-docs#39]

**Comment by davila7** [comment]
@RobertoMartinCaccia 

Could you provide more information?
Do you see any errors?

**Comment by RobertoMartinCaccia** [comment]
Disculpa no sabia que eras de Chile, lo vi en twitch :) y felicitaciones por la extension esta genial.
No puse mas contexto porque no hay errores ni nada, simplemente desde que instale el github copilot labs cuando quiero utilizar code GPT abre un nuevo file en vs code y queda en blanco.
Los pasos para reproducirlo serian instalar code GPT y despues github copilot labs, se que no es mucho disculpas nuevamente.
