### ISSUE TITLE
add the API key, but can't get any output

### ISSUE THREAD

**Issue by ozbillwang** [davila7/code-gpt-docs#4]
have enter API Key (press cmd+shift+p and search for CodeGPT: Set API KEY) in VS Code. But when write codes with comments, no any help from ChatGPT. 

after check, I got below error.
```
You exceeded your current quota, please check your plan and billing details.
```

But the API key in OpenAI is never be used.

![image](https://user-images.githubusercontent.com/8954908/213887272-8d569036-6363-4cb8-8b52-55b78d9699fe.png)

If I directly use https://chat.openai.com/, I can get answer quickly.

**Comment by davila7** [comment]
Go to your OpenAI Account and then click on Manage Account

<img width="182" alt="Captura de Pantalla 2023-01-21 a la(s) 4 24 34 p  m" src="https://user-images.githubusercontent.com/6216945/213887724-dcdd2e16-d2d7-4e43-b659-8957d5655288.png">

Then click on Usage

<img width="193" alt="Captura de Pantalla 2023-01-21 a la(s) 4 25 06 p  m" src="https://user-images.githubusercontent.com/6216945/213887735-dbf73436-9f51-44ae-90a1-a13a8f2c336b.png">

Here you can see if you have credits to use the API

<img width="617" alt="Captura de Pantalla 2023-01-21 a la(s) 4 25 15 p  m" src="https://user-images.githubusercontent.com/6216945/213887755-73af357f-a8d0-43d0-9c2a-56736eab547d.png">

**Comment by ozbillwang** [comment]
no any , my account is "personal", free account

![image](https://user-images.githubusercontent.com/8954908/213888088-38ca44cd-4b0b-4a38-b08a-13a84b7ae046.png)

**Comment by davila7** [comment]
That's the reason, you don't have credits to use the API. When you create an account at OpenAI, it gives you $18 USD free for 3 months.

<img width="160" alt="Captura de Pantalla 2023-01-21 a la(s) 4 43 32 p  m" src="https://user-images.githubusercontent.com/6216945/213888206-8ac763e6-f195-43eb-853d-8430b5a504a1.png">

In the image you can see that you have no credit.

**Comment by ozbillwang** [comment]
ok, I see. I registered openai beta before, not for ChataAI, seems the API has been expired. 

Sure, let me switch to other mailboxes.

**Comment by ozbillwang** [comment]
Switch to a new mailbox, but seems it still asked for mobile detail, which I provided the same one. 

But don't get credit on the new mailbox profile. 

![image](https://user-images.githubusercontent.com/8954908/213890583-76aac851-4594-4cdc-972a-ca088fa8382e.png)

**Comment by ozbillwang** [comment]
so it need be applied via "OpenAI ChatGPT API Waitlist"

![image](https://user-images.githubusercontent.com/8954908/213894938-b069ef70-a68b-4464-8abb-683c1f4fcd66.png)

**Comment by ozbillwang** [comment]
@davila7 

Recommend to update in README how how to get the API permmission and credits as pre-requisite

**Comment by davila7** [comment]
> Switched to a new mailbox, it asked for mobile detail, which I provided the same one.
> 
> But don't get credit on the new mailbox profile.
> 
> ![image](https://user-images.githubusercontent.com/8954908/213890583-76aac851-4594-4cdc-972a-ca088fa8382e.png)

To be able to use the extension you must have credits, either with the free trail or with your own credits.
If the credits were not uploaded to your account, you should check with OpenAI support

**Comment by davila7** [comment]
> so it need be applied via "OpenAI ChatGPT API Waitlist"
> 
> ![image](https://user-images.githubusercontent.com/8954908/213894938-b069ef70-a68b-4464-8abb-683c1f4fcd66.png)

The extension does not use the ChatGPT API, it uses the GPT-3 and Codex API.
When the ChatGPT API is released I will add it inside the extension so it can be selected in Settings.
You don't need to register on the waitlist to use it with the extension

**Comment by davila7** [comment]
> @davila7
> 
> Recommend to update in README on how to get the API permmission and credits as pre-requisite
> 
> ### Prerequisite
> Make sure you have applied and active API in ChatGPT.
> 
> if you don't, you will get prompt as above after you login https://openai.com/api/
> 
> ```
> ChatGPT is coming to our API soon, sign up to stay updated
> ```
> 
> ![image](https://user-images.githubusercontent.com/8954908/213895136-ca05a42b-509e-4236-8938-24ef5c403bc4.png)
> 
> Follow up the sign-up link and apply in waitlist
> 
> ![image](https://user-images.githubusercontent.com/8954908/213895118-7e2e13f4-0e6c-4b38-93c7-c4f929744095.png)

Thanks! I will add the credit requirements to the installation process.
It is not necessary to register in the ChatGPT waitlist to be able to use it, I am already registered and when it is released it will be available in the extension.

**Comment by ozbillwang** [comment]
> The extension does not use the ChatGPT API, **it uses the GPT-3 and Codex API.** When the ChatGPT API is released I will add it inside the extension so it can be selected in Settings. You don't need to register on the waitlist to use it with the extension

Thanks. 

But where to get the free trial? My account still shows $0.00

**Comment by davila7** [comment]
> > The extension does not use the ChatGPT API, **it uses the GPT-3 and Codex API.** When the ChatGPT API is released I will add it inside the extension so it can be selected in Settings. You don't need to register on the waitlist to use it with the extension
> 
> Thanks.
> 
> But where to get the free trial? My account still shows $0.00

Your OpenAI credits last for 3 months and then expire.

I would really appreciate it if you can change your rating in the VSCode marketplace since the problem is your OpenAI credits and not the extension.

I would appreciate it if you could make the change as it affects the display of the extension on the marketplace.
