### ISSUE TITLE
How to restore hotkeys to default?

### ISSUE THREAD

**Issue by suenot** [davila7/code-gpt-docs#40]
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/1426876/219388388-ff80d6a4-645e-4aec-a260-e818a75a9cb3.png">
I remove one of item in list. Reinstall extension didn't help.

**Comment by davila7** [comment]
@suenot  check this link:

https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-shortcuts-editor

**Comment by suenot** [comment]
<img width="1288" alt="image" src="https://user-images.githubusercontent.com/1426876/219396134-f3351e94-d2ad-4ab1-83f5-a3fb92962143.png">
Thanks, find settings.
