### ISSUE TITLE
ctrl + shift + i

### ISSUE THREAD

**Issue by rapidAman** [davila7/code-gpt-docs#41]
get code is not working for rust program, after writing the comment I am keeping my cursor at the end but then also it is not working. 
showing this pop up
![image](https://user-images.githubusercontent.com/95608931/219554771-b921d5e7-95e5-436e-a910-0ed6a2ffcc4e.png)

**Comment by davila7** [comment]
What is the extension of the file you are editing?

**Comment by rapidAman** [comment]
.rs

**Comment by davila7** [comment]
Support for rust files will be added in the next version.

Thanks for the information.

**Comment by tutecode** [comment]
Hi! I have the same issue I'm trying to edit a package.json file.
