### ISSUE TITLE
Ops! Incomplete Completion. The request requires 640 tokens and you only have 500. Add more tokens in your CodeGPT Settings.

### ISSUE THREAD

**Issue by Matt-Iwago** [davila7/code-gpt-docs#42]
[image](https://user-images.githubusercontent.com/75965099/219573108-d6b83c6b-18fe-4a65-a9f3-ec9e3db141e4.png)
![aa](https://user-images.githubusercontent.com/75965099/219573247-016ae18a-271b-4c83-a8b5-af806c21f916.PNG)

**Comment by davila7** [comment]
Go to settings -> Extensions -> CodeGPT and add more tokens:

<img width="646" alt="Captura de Pantalla 2023-02-17 a la(s) 1 55 43 p  m" src="https://user-images.githubusercontent.com/6216945/219759996-f856ebec-f468-4edc-9ccb-e93a0348ed66.png">
