### ISSUE TITLE
Error en aPI de cohere

### ISSUE THREAD

**Issue by azuranob** [davila7/code-gpt-docs#43]
Me aparece este error cuando utilizo las teclas rapidas cmd+shift+i al final de una pregunta a code GPT, he utilizado CodeGPT: Set API KEY, pero no se si esta cogiendo la api key de Cohere o la de OpenAI

**Comment by azuranob** [comment]
Cohere API Response was: Error 404: model at 'text-ada-001' does not exist.. More information about this error: https://www.codegpt.co/docs/tutorial-basics/api_errors

**Comment by davila7** [comment]
En el error se puede ver que está tomando la API de Cohere y esta llamando al modelo "text-ada-001" que es de OpenAI
Intenta cambiar la configuración para que tome el modelo de Cohere:

Luego cmd+shift+p y busca: Developer: Reload Window  para que refresque la instancia y tome las nuevas configuraciones.

<img width="285" alt="Captura de Pantalla 2023-02-17 a la(s) 1 36 29 p  m" src="https://user-images.githubusercontent.com/6216945/219754920-d3865709-08b8-4924-9149-5adc35be782e.png">

**Comment by azuranob** [comment]
Solucionado! Gracias!
