### ISSUE TITLE
Cmd + shift + p isn't showing the result.

### ISSUE THREAD

**Issue by souravkumardubey** [davila7/code-gpt-docs#44]
The result after pressing the keys is resulting into a small popup in the right corner of my VS Code and its showing the result in that.

**Comment by davila7** [comment]
Could you attach an image.

Do you mean cmd+shift+i ?

**Comment by pherm** [comment]
some error, look a error provider service auth

**Comment by souravkumardubey** [comment]
> Could you attach an image.
> 
> Do you mean cmd+shift+i ?
![Screenshot 2023-02-20 at 7 17 13 PM](https://user-images.githubusercontent.com/73059672/220346868-20c5a561-e9d1-459b-975d-d548f8575d39.png)

I'm getting the result in this form but not as a comment.

**Comment by pherm** [comment]
yeah cmd+shift+i

**Comment by davila7** [comment]
> some error, look a error provider service auth
> 
> OpenAI API Response was: Error: Request failed with status code 500. More information about this error: https://www.codegpt.co/docs/tutorial-basics/api_errors
> 
> 500 is error server.

Look like OpenAI is down, you could check here: https://status.openai.com/

**Comment by souravkumardubey** [comment]
> yeah cmd+shift+i
> 
> Ps: You must highlight the code you wish to comment, then give cmd+shift+i

sorry but that isnt working on mac, for mac its mentioned that the command is cmd+shift+p which is resulting in what I have shown in the screenshot.

**Comment by davila7** [comment]
@souravkumardubey 
There are two different features:

GetCode:
You must create a comment and with the cursor at the end of the line press cmd+shift+i
https://www.codegpt.co/docs/tutorial-features/get_code

The other functionality is Ask CodeGPT:
With or without a code selected you can generate a question by pressing cmd+shift+p
https://www.codegpt.co/docs/tutorial-features/ask

**Comment by souravkumardubey** [comment]
> @souravkumardubey 
> There are two different features:
> 
> GetCode:
> You must create a comment and with the cursor at the end of the line press cmd+shift+i
> https://www.codegpt.co/docs/tutorial-features/get_code
> 
> The other functionality is Ask CodeGPT:
> With or without a code selected you can generate a question by pressing cmd+shift+p
> https://www.codegpt.co/docs/tutorial-features/ask

Sorry, but I'm talking about the "explain the selected code" feature. It used to work flawlessly by explaining in the form of comment 2-3 days ago. But now it's not.

**Comment by pherm** [comment]
Bro is error server @souravkumardubey. Plugin work. 

Ps: As I wrote hours ago, that kind of error (500 or similar) is not a client-side error.

**Comment by davila7** [comment]
@souravkumardubey 

Sorry for the misunderstanding, now I know what specific function you are using.
I think the problem may be from OpenAI, since the service is unstable and apparently they are returning 500 error from the server and they are not delivering the error, however, they are delivering the correct response.

You can check this URL until the service is stable and try again.
https://status.openai.com/

**Comment by souravkumardubey** [comment]
Yes, that is what I was trying to explain that I'm getting the response but not in the comment format, but in a bottom-right toast popup. Thank you! This feature is actually very helpful and saves a lot of time.
