### ISSUE TITLE
Open-Sourceing the extension Code

### ISSUE THREAD

**Issue by michaelfeil** [davila7/code-gpt-docs#46]
Hi Daniel,

thanks for the awesome project. 
Are there any plans to publish the source code that is powering the extension?
E.g. in a https://github.com/davila7/code-gpt repo 

This would make it possible to make complex extensions, e.g. making in compatible with similar services like https://github.com/fauxpilot/fauxpilot

**Comment by DrShushen** [comment]
It seems the code has still not been made open source? Is it still a plan to make it open source?
At the moment some people may be hesitant to use this extension for this reason, including myself.

**Comment by davila7** [comment]
@DrShushen 
Yes, of course, things have been quite hectic these days with GPT-4 and PaLM, but we're still working on open source. This issue has not been closed for the same reason.

This project was started by myself. Then Midudev joined and made two direct shows on twitch showing the code and refactoring it to be able to leave the base to be opensource.

First video:
https://www.twitch.tv/videos/1739937240

Second video:
https://www.twitch.tv/videos/1746808327

Finally, one more person joined who is working on passing the entire front of the extension to React.
Our goal is to finish porting everything to React to release the code (If you know react please send me a DM, we need help with this topic.)

This code-gpt-docs repo is also opensource and needs maintenance with every release. We are few in the project and we need help from the community to maintain both projects.

**Comment by DrShushen** [comment]
That's great news, unfortunately I am primarily a Python dev, so won't be able to help out with React.

**Comment by GiancarloZ** [comment]
> ase send me a DM,

React dev here

**Comment by amnweb** [comment]
Forget it, this will never be open-sourced; there are many good extensions currently, so we can use them.

**Comment by michaeltansg** [comment]
Hi @davila7. I am seeking for VS Code extension similar to co-pilot but with the ability to connect to OSS LLM providers and chance upon your product. I plan to introduce this company-wide, but we are stringent on being able to know what goes under the hood. So while the product has a privacy declaration like so:

[AI Providers APIs: When you directly connect your account to the AI models provided by the extension, we do NOT mediate the call, and the request goes directly to each provider's API.](https://marketplace.visualstudio.com/items?itemName=DanielSanMedium.dscodegpt&ssr=false#overview:~:text=AI%20Providers%20APIs%3A%20When%20you%20directly%20connect%20your%20account%20to%20the%20AI%20models%20provided%20by%20the%20extension%2C%20we%20do%20NOT%20mediate%20the%20call%2C%20and%20the%20request%20goes%20directly%20to%20each%20provider%27s%20API.)

in order for us to adopt this extension, we would appreciate if the extension is open-sourced. Thank you for your consideration.

**Comment by PilarHidalgo** [comment]
@michaeltansg , @amnweb Thanks for your feedback. Currently, you can use the extension for free with other providers or have a free account with us, but it has some limitations. If you are interested in trying out a specific feature on the paid plan, please feel free to contact us to discuss it.
