### ISSUE TITLE
Several, related issues?

### ISSUE THREAD

**Issue by dzar-aker** [davila7/code-gpt-docs#47]
I have uninstalled and reinstalled in VS Code with the same issues:
- I had another extension using my API key and removed it, as well
- When I try to do anything with ChatGPT I get 
`XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX API could not process the query, try selecting the code and using Ask CodeGPT to write your own query`
- The API key shown is NOT my new API key that I entered. It's an old one. 
- When I check my API usage, none have ever been used. Not the one shown, nor the one I created today and entered into VS Code before submitting this report.

So nothing seems to work. Any suggestions? 

I am on v1.0.15
I've tried with .jsx, .rb and .py files—none work.

**Comment by davila7** [comment]
Please check this link:
https://github.com/davila7/code-gpt-docs/issues/32

**Comment by dzar-aker** [comment]
Thank you! How did I miss that?

Indeed, the issue was some old stuff in my settings.json that I removed and now it's working.
