### ISSUE TITLE
Always getting this error: OpenAI API Response was: Error: Request failed with status code 429. More information about this error: https://www.codegpt.co/docs/tutorial-basics/api_errors

### ISSUE THREAD

**Issue by Princeyadav05** [davila7/code-gpt-docs#48]
Getting the following error everytiime.

"OpenAI API Response was: Error: Request failed with status code 429. More information about this error: https://www.codegpt.co/docs/tutorial-basics/api_errors"

Even though the billing on my OPEN AI Account shows $0.05 / $18.00.

I've tried to change accounts, Api keys and even reinstalled the extension, with no luck.

**Comment by davila7** [comment]
You could check if the expiration date of your credits has not expired

<img width="410" alt="Captura de Pantalla 2023-02-27 a la(s) 11 07 03 a  m" src="https://user-images.githubusercontent.com/6216945/221616115-41b96b61-744a-4ec1-a3e7-f53a48e530ca.png">

**Comment by Princeyadav05** [comment]
Says expired 1st Feb 2023.
Grant 1	$18.00	Expired 1 February 2023

**Comment by Princeyadav05** [comment]
@davila7 can you please help me understand this? I thought open ai free to use as long as you are not hitting their servers with many requests.

Is there a way I can make this work?

**Comment by modisulak** [comment]
Add your credit card info and the error would go away.

**Comment by davila7** [comment]
> @davila7 can you please help me understand this? I thought open ai free to use as long as you are not hitting their servers with many requests.
> 
> Is there a way I can make this work?

The OpenAI API is not free. Here you can see the prices: https://openai.com/pricing

In any case, it is very cheap, I use it a lot, every day, all day and I have not exceeded 8 dollars a month.
For normal use you should not spend more than 3 dollars a month.

Check your account in the Usage menu to see that info
