### ISSUE TITLE
Can we use GPT-3 model instead of Davinci model?

### ISSUE THREAD

**Issue by bhaskoro-muthohar** [davila7/code-gpt-docs#51]
Like the tittle say, is it possible to utilize GPT-3 model instead?

**Comment by ackvf** [comment]
as per their tweet from Mar 1 https://twitter.com/OpenAI/status/1630992406542970880

Seems to be 10x cheaper

https://openai.com/blog/introducing-chatgpt-and-whisper-apis 

> Model: The ChatGPT model family we are releasing today, gpt-3.5-turbo, is the same model used in the ChatGPT product. It is priced at $0.002 per 1k tokens, which is 10x cheaper than our existing GPT-3.5 models. It’s also our best model for many non-chat use cases—we’ve seen early testers migrate from text-davinci-003 to gpt-3.5-turbo with only a small amount of adjustment needed to their prompts.

**Comment by davila7** [comment]
@ackvf  @bhaskoro-muthohar 

I am working to upload the Chatgpt model very soon... it will be in the next update and it also comes with a surprise.

<img width="403" alt="Captura de Pantalla 2023-03-02 a la(s) 10 42 04 p  m" src="https://user-images.githubusercontent.com/6216945/222625992-7c362556-42ae-4233-98bc-1d6c0b22ec7d.png">

**Comment by laozhuang727** [comment]
amazing, when can it be release?

**Comment by davila7** [comment]
please installa version 2.0.1
gpt-3.5-turbo and gpt-3.5-turbo-0301 are now available

**Comment by ackvf** [comment]
Just curious, would it be possible to make it such so that it accepts any string matching an existing model? Having this ability would be future-proof. You would not have to push updates when they release new models.

This endpoint
```
https://api.openai.com/v1/models
```

returns a response like this
![image](https://user-images.githubusercontent.com/2313018/223905973-4f074e1c-d3ee-4b1f-bf99-923c7e2f1b9a.png)

and simply iterating over the rows gives me 69 models

```
[
  "babbage",
  "davinci",
  "gpt-3.5-turbo-0301",
  "text-davinci-003",
  "babbage-code-search-code",
  "text-similarity-babbage-001",
  "text-davinci-001",
  "ada",
  "curie-instruct-beta",
  "babbage-code-search-text",
  "babbage-similarity",
  "gpt-3.5-turbo",
  "code-davinci-002",
  "code-search-babbage-text-001",
  "text-embedding-ada-002",
  "code-cushman-001",
  "whisper-1",
  "code-search-babbage-code-001",
  "audio-transcribe-deprecated",
  "text-ada-001",
  "text-similarity-ada-001",
  "text-davinci-insert-002",
  "ada-code-search-code",
  "ada-similarity",
  "code-search-ada-text-001",
  "text-search-ada-query-001",
  "text-curie-001",
  "text-davinci-edit-001",
  "davinci-search-document",
  "ada-code-search-text",
  "text-search-ada-doc-001",
  "code-davinci-edit-001",
  "davinci-instruct-beta",
  "text-similarity-curie-001",
  "code-search-ada-code-001",
  "ada-search-query",
  "text-search-davinci-query-001",
  "curie-search-query",
  "davinci-search-query",
  "text-davinci-insert-001",
  "babbage-search-document",
  "ada-search-document",
  "text-search-curie-query-001",
  "text-search-babbage-doc-001",
  "text-davinci-002",
  "curie-search-document",
  "text-search-curie-doc-001",
  "babbage-search-query",
  "text-babbage-001",
  "text-search-davinci-doc-001",
  "text-search-babbage-query-001",
  "curie-similarity",
  "curie",
  "text-similarity-davinci-001",
  "davinci-similarity",
  "cushman:2020-05-03",
  "ada:2020-05-03",
  "babbage:2020-05-03",
  "curie:2020-05-03",
  "davinci:2020-05-03",
  "if-davinci-v2",
  "if-curie-v2",
  "if-davinci:3.0.0",
  "davinci-if:3.0.0",
  "davinci-instruct-beta:2.0.0",
  "text-ada:001",
  "text-davinci:001",
  "text-curie:001",
  "text-babbage:001"
]
```

**Comment by ackvf** [comment]
@davila7 BTW, what's the surprise? 😅😅
