### ISSUE TITLE
OpenAI API Response Error

### ISSUE THREAD

**Issue by yohappy** [davila7/code-gpt-docs#56]
OpenAI API Response was: TypeError: Cannot read properties of undefined (reading 'body')

**Comment by davila7** [comment]
@yohappy what function are you using?

**Comment by AugustRush** [comment]
> 

+1

**Comment by jjmato** [comment]
> OpenAI API Response was: TypeError: Cannot read properties of undefined (reading 'message')

1. set api key
2. open codegpt chat
3. type for example Hello
4. get error above

**Comment by davila7** [comment]
fixed with the last version
