### ISSUE TITLE
OpenAI API Response was: TypeError: Cannot read properties of undefined (reading 'message')

### ISSUE THREAD

**Issue by nisiyuan** [davila7/code-gpt-docs#57]
OpenAI API Response was: TypeError: Cannot read properties of undefined (reading 'message')

**Comment by jonathanray** [comment]
Select "Developer: Reload Window" from the Command Palette or close and restart VS Code.

**Comment by frankgestrada** [comment]
I have performed both actions recommended by jonathanray (Select "Developer: Reload Window" from the Command Palette or close and restart VS Code.) and am still having the same issue.  In VS Code (1.76.0) I have selected "Find Problems CodeGPT" and also "Refactor CodeGPT" for 107 lines of python (3.10) code and I get the following message "OpenAI API Response was: TypeError: Cannot read properties of undefined (reading 'message')".  If I select smaller chunks of code and run "Find Problems CodeGPT" or "Refactor CodeGPT" it randomly executes without error or it fails with the same message.

**Comment by davila7** [comment]
@frankgestrada 
Could you write your setting configuration:

CodeGPT version:
Provider:
Model:
Language:
max token:
temperature:

If you are using OpenAI, always remember to check this page if you are getting any errors:
https://status.openai.com/

<img width="888" alt="Captura de Pantalla 2023-03-07 a la(s) 9 42 05 a  m" src="https://user-images.githubusercontent.com/6216945/223455400-14e2641f-e62a-4844-a240-ee2460e17365.png">

**Comment by frankgestrada** [comment]
@davila7 
CodeGPT version: 2.0.1
Provider: OpenAI (VS Code "CodeGPT" extension)
Model: text-davinci-003
Language: Python 3.10.10
max token: 2333
temperature: 0.35

**Comment by davila7** [comment]
@frankgestrada could you try again today?

Yesterday all the models were with problems 👇
https://status.openai.com/incidents/75n0s8jzv5gx

**Comment by davila7** [comment]
I recommend you use the gpt-3.5-turbo model. I have had better results in some cases with that model

**Comment by zusldev** [comment]
Mismo problema aca, usando davinci o turbo model en español o inglés, temperature por defecto. Con todas las opciones de code gpt me da el error: OpenAI API Response was: TypeError: Cannot read properties of undefined (reading 'message').

**Comment by davila7** [comment]
> message

Probaste recargar el editor con Developer: Reload Windows 
Tambien cerrando completamente VSCode y volviendo a abrir


<img width="257" alt="Captura de Pantalla 2023-03-07 a la(s) 2 38 24 p  m" src="https://user-images.githubusercontent.com/6216945/223534053-2c60b08b-4016-4734-bf35-80926558fc2c.png">

**Comment by zusldev** [comment]
> > message
> 
> Probaste recargar el editor con Developer: Reload Windows Tambien cerrando completamente VSCode y volviendo a abrir
> 
> <img alt="Captura de Pantalla 2023-03-07 a la(s) 2 38 24 p  m" width="257" src="https://user-images.githubusercontent.com/6216945/223534053-2c60b08b-4016-4734-bf35-80926558fc2c.png">
Si, tambien reinstalando la extensión, eliminando y agregando nueva api key, hasta reiniciando la pc jaja. Es la primera vez que lo uso.

**Comment by davila7** [comment]
> > > message
> > 
> > 
> > Probaste recargar el editor con Developer: Reload Windows Tambien cerrando completamente VSCode y volviendo a abrir
> > <img alt="Captura de Pantalla 2023-03-07 a la(s) 2 38 24 p  m" width="257" src="https://user-images.githubusercontent.com/6216945/223534053-2c60b08b-4016-4734-bf35-80926558fc2c.png">
> 
> Si, tambien reinstalando la extensión, eliminando y agregando nueva api key, hasta reiniciando la pc jaja. Es la primera vez que lo uso.

Puedes revisar si tienes créditos en tu cuenta de OpenAI

**Comment by zusldev** [comment]
> > > > message
> > > 
> > > 
> > > Probaste recargar el editor con Developer: Reload Windows Tambien cerrando completamente VSCode y volviendo a abrir
> > > <img alt="Captura de Pantalla 2023-03-07 a la(s) 2 38 24 p  m" width="257" src="https://user-images.githubusercontent.com/6216945/223534053-2c60b08b-4016-4734-bf35-80926558fc2c.png">
> > 
> > 
> > Si, tambien reinstalando la extensión, eliminando y agregando nueva api key, hasta reiniciando la pc jaja. Es la primera vez que lo uso.
> 
> Puedes revisar si tienes créditos en tu cuenta de OpenAI

Toda la razón, por despistado no me di cuenta que mis creditos habian expirado. Muchas gracias ya funciona perfecto!

**Comment by davila7** [comment]
> > > > > message
> > > > 
> > > > 
> > > > Probaste recargar el editor con Developer: Reload Windows Tambien cerrando completamente VSCode y volviendo a abrir
> > > > <img alt="Captura de Pantalla 2023-03-07 a la(s) 2 38 24 p  m" width="257" src="https://user-images.githubusercontent.com/6216945/223534053-2c60b08b-4016-4734-bf35-80926558fc2c.png">
> > > 
> > > 
> > > Si, tambien reinstalando la extensión, eliminando y agregando nueva api key, hasta reiniciando la pc jaja. Es la primera vez que lo uso.
> > 
> > 
> > Puedes revisar si tienes créditos en tu cuenta de OpenAI
> 
> Toda la razón, por despistado no me di cuenta que mis creditos habian expirado. Muchas gracias ya funciona perfecto!

Genial! De todas formas me sirve para modificar el mensaje y enviar directamente el error en la extensión. Lo dejo en inglés para los demás

@frankgestrada @PeterTemps @nisiyuan 
Please check if your account has credits.
In this link, you can see the step-by-step: https://www.codegpt.co/docs/intro#important

**Comment by frankgestrada** [comment]
> I recommend you use the gpt-3.5-turbo model. I have had better results in some cases with that model

I have changed the model to gpt-3.5-turbo and the error has not returned.  I also checked my account, and it does not appear to be an issue; I have a pay per use subscription with a decent upper limit.  

Thanks for the help.

**Comment by davila7** [comment]
You have to check if you have credits in the Usage Sections:

<img width="830" alt="Captura de Pantalla 2023-03-10 a la(s) 12 28 22 a  m" src="https://user-images.githubusercontent.com/6216945/224231309-6332893c-19c5-4f6f-a55e-29fb9378157a.png">

If you want to buy credits you have to go to Billing:
<img width="971" alt="Captura de Pantalla 2023-03-10 a la(s) 12 30 35 a  m" src="https://user-images.githubusercontent.com/6216945/224231602-2dbbd2d5-9368-46a4-8980-8fae6e9da5b1.png">

**Comment by BjarkeCK** [comment]
Same error here.

**Comment by paulmaunders** [comment]
I also get this error `OpenAI API Response was: TypeError: Cannot read properties of undefined (reading 'message')`.

I have tried `gpt-3.5-turbo` and `text-davinci-003` but I get the same error with both.

**Comment by haimat** [comment]
I have the same issue:
- checked monthly usage
- set model to `gpt-3.5-turbo`
- reloaded VS Code

Any other ideas?

**Comment by grishaMelisov** [comment]
same

**Comment by dedguy21** [comment]
I'm getting this error as well

**Comment by hyze2d** [comment]
Same thing, tried everything above 
OpenAI API Response was: TypeError: Cannot read properties of undefined (reading 'message')

**Comment by josh3io** [comment]
same issue. brand new OS and vscode installation. tried reloading, restarting, and changing model without success.

**Comment by davila7** [comment]
I am working on an update that will show the error coming from the OpenAI api

It will be ready in the following days.

**Comment by marvinperrottSB** [comment]
So one can only use Code GPT on a paid plan? Is that correct?

**Comment by richardkenneth** [comment]
I had same issue.
I'll share what worked for me.

Go to VS code Settings, under Extensions, under CodeGPT.
Select each of the AI provider and remove each of the keys (using Cmd+Shift+P and selecting "CodeGPT: Remove API key"). Then add the keys starting from A212, followed by Cohere before OpenAI.

You may want to change the ChatGPT model to "gpt-3.5-turbo". Then reload window (using Cmd+Shift+P and selecting Developer: Reload window). When window have been reloaded, if you wish, you can revert the model to "text-davinci-003". 

Then try again. Goodluck.

**Comment by marvinperrottSB** [comment]
I did that. Still no luck. Would I be using the same key for all of them or different keys?

**Comment by zs-dima** [comment]
+1 the same issue.

**Comment by edsonmojica** [comment]
same issue here

**Comment by tremmel** [comment]
same issue.

**Comment by davila7** [comment]
Uploading version 2.0.2 with this issue fixed.
Also with the gpt-4 and gpt-4-32k integrated

<img width="473" alt="Captura de Pantalla 2023-03-14 a la(s) 10 56 47 p  m" src="https://user-images.githubusercontent.com/6216945/225193537-97784898-60e1-454f-92f0-0d30b4afc7b3.png">

**Comment by dedguy21** [comment]
My issue was resolved by generating a new key and then adding it.

**Comment by davila7** [comment]
Yes, now the extension will show you the error message from OpenAI

<img width="540" alt="Captura de Pantalla 2023-03-14 a la(s) 10 58 39 p  m" src="https://user-images.githubusercontent.com/6216945/225193800-96f2f104-df26-487d-9282-e8a9dd66e2b9.png">

**Comment by hayusama** [comment]
hi, to solve this problem I generated a new key on openAI (even without subscription) then I added it as an openAPI key I reloaded the system and it worked fine.

**Comment by Nicogamerman** [comment]
> hi, to solve this problem I generated a new key on openAI (even without subscription) then I added it as an openAPI key I reloaded the system and it worked fine.

Hi! how can i generate a new key?

**Comment by davila7** [comment]
> After changing the API Key, and do everything, it tells me the Error 429 You must need to pay for use it no?

Yes, please check this link: https://www.codegpt.co/docs/intro#important

**Comment by davila7** [comment]
this issue is fixed in version 2.0.2

Please update your extension an reload the editor 👍

**Comment by Nicogamerman** [comment]
> > After changing the API Key, and do everything, it tells me the Error 429 You must need to pay for use it no?
> 
> Yes, please check this link: https://www.codegpt.co/docs/intro#important

same problem here, and i didnt use any credit yet

**Comment by davila7** [comment]
> > > After changing the API Key, and do everything, it tells me the Error 429 You must need to pay for use it no?
> > 
> > 
> > Yes, please check this link: https://www.codegpt.co/docs/intro#important
> 
> same problem here, and i didnt use any credit yet

Check if you have credits in your account Or if the expiration date of the credits has not expired

<img width="668" alt="Captura de Pantalla 2023-03-15 a la(s) 8 50 13 p  m" src="https://user-images.githubusercontent.com/6216945/225481066-0e4c87d1-27dc-467b-837a-6d1b7dfca4ec.png">

**Comment by Nicogamerman** [comment]
> > > > After changing the API Key, and do everything, it tells me the Error 429 You must need to pay for use it no?
> > > 
> > > 
> > > Yes, please check this link: https://www.codegpt.co/docs/intro#important
> > 
> > 
> > same problem here, and i didnt use any credit yet
> 
> Check if you have credits in your account Or if the expiration date of the credits has not expired
> 
> <img alt="Captura de Pantalla 2023-03-15 a la(s) 8 50 13 p  m" width="668" src="https://user-images.githubusercontent.com/6216945/225481066-0e4c87d1-27dc-467b-837a-6d1b7dfca4ec.png">

![image](https://user-images.githubusercontent.com/103078548/225482984-69a453b1-1d7d-46ad-b64b-ede1c81ea253.png)

Thats the problem! it is expired!

**Comment by onkeloki** [comment]
Same here,
mac OSX 
tryed several api keys 
tryed to reloead 
tryed different models 

no luck

**Comment by davila7** [comment]
Please update to the latest version, this message is fixed and it shows the OpenAI error.
Remember to reload Visual Studio Code with the command: "Developer: Reload Window"

> > > > > After changing the API Key, and do everything, it tells me the Error 429 You must need to pay for use it no?
> > > > 
> > > > 
> > > > Yes, please check this link: https://www.codegpt.co/docs/intro#important
> > > 
> > > 
> > > same problem here, and i didnt use any credit yet
> > 
> > 
> > Check if you have credits in your account Or if the expiration date of the credits has not expired
> > <img alt="Captura de Pantalla 2023-03-15 a la(s) 8 50 13 p  m" width="668" src="https://user-images.githubusercontent.com/6216945/225481066-0e4c87d1-27dc-467b-837a-6d1b7dfca4ec.png">
> 
> ![image](https://user-images.githubusercontent.com/103078548/225482984-69a453b1-1d7d-46ad-b64b-ede1c81ea253.png)
> 
> Thats the problem! it is expired!

Credits have an expiration time. If you upgrade to the paid plan and use the extension as normal, you shouldn't pay more than $5 per month.

**Comment by davila7** [comment]
> Same here, mac OSX tryed several api keys tryed to reloead tryed different models
> 
> no luck

Please update to the latest version, this message is fixed and it shows the OpenAI error.
Remember to reload Visual Studio Code with the command: "Developer: Reload Window"

**Comment by onkeloki** [comment]
> > Same here, mac OSX tryed several api keys tryed to reloead tryed different models
> > no luck
> 
> Please update to the latest version, this message is fixed and it shows the OpenAI error. Remember to reload Visual Studio Code with the command: "Developer: Reload Window"
VSCODE: Version: 1.76.2
Code GPT: v2.0.3
reloades Several times: Developer: Reload Window"
Vscode restart did not solve the problem
...
but a coworker with nearly same mac and VScode configuration get it work.
so it might be something on my network or my computer :(

**Comment by onkeloki** [comment]
sorry  i dont know where to finde a Network error panel in vscode
![image](https://user-images.githubusercontent.com/183480/225906914-cc910b08-7542-49a2-ab49-affe58b3bba0.png)

![image](https://user-images.githubusercontent.com/183480/225907144-672439d9-10d3-49e9-9152-fb45d58f5ecb.png)

**Comment by davila7** [comment]
Thank you! With this image I can already get the error and show it

**Comment by alanwilter** [comment]
For the problem is this:

If I open a local project in my Mac with Vscode, CodeGPT: `create a fibonacci function in python` works fine.

If I try the very same thing with a `vscode-remote` project, I got this error:

```
OpenAI API Response was: TypeError: Cannot read properties of undefined (reading 'status')
```

Why this?

**Comment by xiao55555** [comment]
seems to need a VPN

**Comment by TsingWei** [comment]
> For me the problem is this:
> 
> If I open a local project in my Mac with Vscode, CodeGPT: `create a fibonacci function in python` works fine.
> 
> If I try the very same thing with a `vscode-remote` project, I got this error:
> 
> ```
> OpenAI API Response was: TypeError: Cannot read properties of undefined (reading 'status')
> ```
> 
> Why this?

Same for me. It seems that codeGPT does not fit vscode-remote well.

**Comment by landontholen** [comment]
I fixed it on mine. GPT was using 

`return response.choices[0].text.trim();`

But in openai package 0.27.0 and higher the structure changes to 

`return response.data.choices`

**Comment by TsingWei** [comment]
> I fixed it on mine. GPT was using
> 
> `return response.choices[0].text.trim();`
> 
> But in openai package 0.27.0 and higher the structure changes to
> 
> `return response.data.choices`

@landontholen How do you fix it? Re-compile the plugin？
