### ISSUE TITLE
Where is my API Key stored?

### ISSUE THREAD

**Issue by philFernandez** [davila7/code-gpt-docs#60]
The extension's description only says that storing my API Key in settings in bad, and that it is instead stored safely and securely. Why is storing my API key in my settings on my computer bad? And where does my API key go to be "safely stored" when putting it into this extension?

Edit: After some research I see that other extensions can read my settings.json file, so I get why that is not a good place, but still curious where this extension puts my API key?

**Comment by davila7** [comment]
If you add the api key in your Settings, other extensions have access to that file.

That is a .json file and all the extensions you have installed in VSCode have access to read it.
In the case of Code GPT, the API Key is saved with Secret Storage. No other extension will have access to it and only you can delete or modify it.

More information here:
https://code.visualstudio.com/api/references/vscode-api#SecretStorage
