### ISSUE TITLE
Error 401: Incorrect API key provided: undefined.

### ISSUE THREAD

**Issue by DannyXY** [davila7/code-gpt-docs#62]
I installed CodeGPT in my VSCode and added the key from the VSCode extensions commands but  the extension can't seem to read it
Any help?

Edit:
All I had to do was restart the VSCode
Fixed, but now I'm getting a 429

**Comment by davila7** [comment]
Please check what kind of error do you have in this link: https://www.codegpt.co/docs/tutorial-basics/api_errors

**Comment by DannyXY** [comment]
Just noticed my tokens were expired 
Never mind and thanks for the help
