### ISSUE TITLE
OpenAI: API Response was: Error 404

### ISSUE THREAD

**Issue by albertomarun** [davila7/code-gpt-docs#63]
I ask the system any question with any existing model and it answers me this: "OpenAI: API Response was: Error 404: That model does not exist More information about this error: https://www.codegpt.co/docs/tutorial-basics/api_errors"

**Comment by davila7** [comment]
What model are you try to use?

**Comment by albertomarun** [comment]
This: 

gpt-4  

gpt-4-32k

**Comment by davila7** [comment]
You must have access to your account. Please join the waiting list and you should receive this email
Once you receive it you can already use those models. I am already using it and it works great

<img width="507" alt="Captura de Pantalla 2023-03-16 a la(s) 3 31 18 p  m" src="https://user-images.githubusercontent.com/6216945/225732789-cf27aaa0-4bbb-4d88-b36b-41a15664b02e.png">
