### ISSUE TITLE
OpenAI API Response was: TypeError: Cannot read properties of undefined (reading 'status')

### ISSUE THREAD

**Issue by AnthonyGKruger** [davila7/code-gpt-docs#64]
Hi, 

I have been trying to make use of the code-gpt extension on github however whenever I attempt to use any of its features I get this response: **OpenAI API Response was: TypeError: Cannot read properties of undefined (reading 'status')**

Has anyone else had this issue and been able to resolve it? I cant seem to find anything online.

**Comment by davila7** [comment]
what codegpt version do you have?

**Comment by AnthonyGKruger** [comment]
I will have to check abit later but I installed it through vscode so it would be the latest version wouldn’t it?Anthony KrugerOn 17 Mar 2023, at 07:02, Daniel Avila ***@***.***> wrote:﻿
what codegpt version do you have?

**Comment by davila7** [comment]
please update to version 2.0.3 and then use the command: Developer: Reload Window

**Comment by AnthonyGKruger** [comment]
I have done that and am getting the same issue...I also already have a paid subscription.

**Comment by davila7** [comment]
Could you check if you have credits in your account: https://www.codegpt.co/docs/intro#important

**Comment by AnthonyGKruger** [comment]
Sorry I see my attachment never went through.
![IMG_5899](https://user-images.githubusercontent.com/60028700/226082646-379014f5-393c-4f59-8025-c8ec816ce4b8.jpeg)
