### ISSUE TITLE
My OpenAI account was deactivated after using CodeGPT

### ISSUE THREAD

**Issue by LRanger1010** [davila7/code-gpt-docs#65]
I enterd my openai api key and used codegpt with a few querys. Then I received an email from openai team, and they deactivated my account.
![image](https://user-images.githubusercontent.com/23703850/225845940-d139ccd3-6e96-4d0b-83da-7b408c7fda70.png)
What is the reason and what can I do now?

**Comment by davila7** [comment]
CodeGPT uses the official Nodejs package by OpenAI to connect to the API. This is the repo:

https://github.com/openai/openai-node

For my part, I have been using CodeGPT for more than 6 months, carrying out different types of tests without any problem. They have even given me access to GPT-4 to further test the extension.

I recommend that you check if you are using other plugins or extensions that connect with Browser Autologin. These types of connections can end up canceling your account.
