### ISSUE TITLE
Error in C#: Create a comment and leave the cursor at the end of the comment line

### ISSUE THREAD

**Issue by xha257** [davila7/code-gpt-docs#7]
In all of my C# scripts in VS code, I tried simple comments like "Function that checks wether a string is a number ", it will return:"Create a comment and leave the cursor at the end of the comment line"
I'm on Windows, I got the error message after ctrl+shift+i when cursor is at the end of the comment.
![image](https://user-images.githubusercontent.com/37316554/213947049-c04a6837-5d08-4a09-9be7-4ffaa3b9cb24.png)

![image](https://user-images.githubusercontent.com/37316554/213947082-92995668-20a8-4eb5-923e-80d015e0b71a.png)

**Comment by davila7** [comment]
Are you using copilot too?
It may be causing some interference. Could you confirm this for me to test with Copilot

**Comment by xha257** [comment]
Thanks for replying! I'm using copilot actually.

**Comment by TomerYakir** [comment]
The same thing happens to me in golang and I'm not using copilot.
VS code version 1.74.3 (Universal)

**Comment by davila7** [comment]
I found the bug, it is fixed in the next version 1.0.12

**Comment by davila7** [comment]
Fixed in version 1.0.12
