### ISSUE TITLE
Language setting does not work

### ISSUE THREAD

**Issue by edr1412** [davila7/code-gpt-docs#70]
I changed `Code GPT > Query:Language` from English to Chinese, but it still answers in English.

**Comment by davila7** [comment]
@edr1412 what feature are you using?

**Comment by edr1412** [comment]
@davila7  I tried refactor and find problem, the answer is in english. Maybe all features has the problem.

**Comment by davila7** [comment]
If you made the language change in Settings, try reloading the window with the following command:

cmd+shif+p and look for the command "Developer: Reload Window"

**Comment by TuiMao233** [comment]
The same problem, setting the language doesn't work
