### ISSUE TITLE
Feature porting from vscode-chatgpt

### ISSUE THREAD

**Issue by Zendrex** [davila7/code-gpt-docs#72]
Since the tragic news of vscode-chatgpt's discontinuation, there are a few things that I would love to see brought over to code-gpt.

These are all personal preferences, however nice to haves in my eyes.

1) ~~A separate tab for the chat so it doesn't take over the explorer. Typically I kept GPT on the right side of my monitor within VSC while leaving my explorer/etc untouched.~~

2) The ability to show real-time response instead of just "thinking" for the chat window.

3) Buttons above codeblocks which allow for import/copy, similar to what vscode-chatgpt had.

4) Better response interactions. At the moment code-gpt opens a new file and pastes the response from the api, however because of this, things like linters get mad and it can also make the response very difficult to read. Not to mention having to close the newly created tab over and over again. Simply responding in the chat window would be nice instead of creating a new file.

5) Disable sending requests when the input field is empty.

5) Ability to clear conversations via a button.

6) Allow for control over text injection/appending.

7) Respect VSC themes (backgrounds, etc).

8) A more minimal response layout. Why is there a new line before every response and such a wide bottom margin after while the chat input doesn't have this.

**Comment by davila7** [comment]
@Zendrex  
Thank you very much for the proposals, I will pass them to discussion to add the improvements.

Could you clarify what happened with vscode-chagpt ?

**Comment by Zendrex** [comment]
> @Zendrex Thank you very much for the proposals, I will pass them to discussion to add the improvements.
> 
> Could you clarify what happened with vscode-chagpt ?

Feel free to take a look here. They discontinued it yesterday.
https://marketplace.visualstudio.com/items?itemName=gencay.vscode-chatgpt

**Comment by davila7** [comment]
How unfortunate what happened.
I received some feedback from people that their OpenAI account was being locked out because they were using the Browser Autologin service.
The project was great.

**Comment by Zendrex** [comment]
Additionally, here is the repo now that it's open source.
https://github.com/gencay/vscode-chatgpt

**Comment by Zendrex** [comment]
Both being streamed in the chat window plus having the chat window detached from the sidebar should go hand in hand. Like mentioned in another issue, closing and opening the window clears the chat, having a separate window entirely would solve this issue at least in the meantime till a more robust solution can be produced.

**Comment by Zendrex** [comment]
Additionally, is there an ETA on when we can see the extension open-sourced? I recall reading somewhere that it was on the roadmap a while back, but have yet to see it anywhere.

**Comment by davila7** [comment]
@Zendrex 
Download the new version 2.0.4, it already comes with the improvements of points: 2, 3 (only the copy button) and 5.

Working on the others one.

**Comment by TanguySoto** [comment]
Just upvoting this issue :) I agree with all the improvements proposition, especially number 4. Thanks @davila7 for the work!

**Comment by davila7** [comment]
@TanguySoto @Zendrex 

Issue 4 will be added next week! And we are preparing an amazing update 😱
