### ISSUE TITLE
Ask StackOverflow doesn't return response

### ISSUE THREAD

**Issue by dvdgorila** [davila7/code-gpt-docs#75]
Hello, 

There appears to be an issue with the ask stackoverlow function. 

The prompt returns a list of stackoverflow posts, however choosing from the returned list creates a blank page after a couple of secs, of the chatGPT thinking response. 

![CleanShot 2023-03-21 at 16 26 11@2x](https://user-images.githubusercontent.com/5569832/226732491-a6dcb561-2b9d-4064-bc0d-2d85e76d6fe3.jpg)

![CleanShot 2023-03-21 at 16 25 19@2x](https://user-images.githubusercontent.com/5569832/226732329-9594fd12-ed59-4c10-b6f0-8ba28f1679fa.jpg)

And finally the blank response. 

![CleanShot 2023-03-21 at 16 26 50@2x](https://user-images.githubusercontent.com/5569832/226732633-76c9dcc9-0e54-481d-b406-d7a4849f0573.jpg)

**Comment by davila7** [comment]
@dvdgorila 
What provider and model are you using?

**Comment by davila7** [comment]
@dvdgorila @TomYeoman 
Thanks for reporting it, we already found the bug!
It will be corrected during the day in version 2.0.5

<img width="644" alt="Captura de Pantalla 2023-03-22 a la(s) 9 12 17 a  m" src="https://user-images.githubusercontent.com/6216945/226915000-7e5e2a56-69ca-4fd9-8847-15f02494a645.png">

**Comment by TomYeoman** [comment]
Amazing thanks for the quick turnaround @davila7 🙌

**Comment by davila7** [comment]
@TomYeoman @dvdgorila 
This is already fixed in version 2.1.1! Thank you
