### ISSUE TITLE
Ask codegpt no response

### ISSUE THREAD

**Issue by UniMars** [davila7/code-gpt-docs#76]
When i ask gpt in the window, there is no response. And yet when i connect through api, it works.
![image](https://user-images.githubusercontent.com/65664032/226946869-821cbe58-c4c5-4bd8-a393-3f2cf814092b.png)
![image](https://user-images.githubusercontent.com/65664032/226947105-3633f889-db93-4c6e-be00-816e8c57d9e4.png)

**Comment by davila7** [comment]
@UniMars 
update to version 2.0.4

**Comment by UniMars** [comment]
> @UniMars update to version 2.0.4

It is 2.0.4

**Comment by dumb** [comment]
Same thing is happening to me with the latest update.

I was on v2.0.4 this morning, and it was working. Updated to v2.1.1, and now nothing but empty responses.

<img width="729" alt="Screen Shot 2023-03-23 at 12 08 39 PM" src="https://user-images.githubusercontent.com/857046/227265624-80391a33-16a5-46c0-b777-3f92c0e8d116.png">

API key is set. Attempted with gpt-3.5-turbo and gpt-4. Like UniMars, I can connect to the GPT API no problem, just not with this extension.

**Comment by davila7** [comment]
@dumb 
We are finding cases where the OpenAI API just returns a blank response... We are going to identify the problem and display the error and if there is no error, retry until the response is delivered.

For now, I recommend you reload the editor and try the question again

<img width="451" alt="Captura de Pantalla 2023-03-23 a la(s) 3 23 04 p  m" src="https://user-images.githubusercontent.com/6216945/227326031-62e98950-8482-4a68-9ad5-1d56f03ebc8c.png">

**Comment by davila7** [comment]
@dumb 
Another thing... you must have at least one editor open.
We are going to add the alert for this case as well.

**Comment by albixu** [comment]
I have the same problem. I don't receive any response or error message when I ask  to chat. It only show a chatbot icon with label CODEGPT. Nothing more.

Can somebody help me to solve this problem?

Thanks

**Comment by matsaleh13** [comment]
I'm having the same issue. I just created my API key and used the `CodeGPT: Set API Key` command. After that, no response to anything I type.

I went to the OpenAI site and inspected my key, and it shows that it has never been used, so seems like my chats aren't even making it to the server?

**Comment by lisasuosuo** [comment]
I have the same issue. The side bar show "stop generate" seems like it is in running but will not over.

**Comment by invi2000** [comment]
I have the same problem. It worked fine once last week. When I wanted to use it again today it doesn't do anything. I only get the empty response with the "Stop Responding" button and nothing else.

I re-entered the APU key, re-installed the extension, I even uninstalled VSCode and reinstalled everything but the problem persists.

```Version: 1.78.0 (user setup)
Commit: 252e5463d60e63238250799aef7375787f68b4ee
Date: 2023-05-03T20:09:00.748Z
Electron: 22.4.8
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: Yes

Code GPT v2.1.6
Published
12/25/2022, 07:38:30
Last released
5/7/2023, 17:47:29
Last updated
5/8/2023, 13:05:39
```

**Comment by tiagonunocosta** [comment]
> I have the same problem. It worked fine once last week. When I wanted to use it again today it doesn't do anything. I only get the empty response with the "Stop Responding" button and nothing else.
> 
> I re-entered the API key, re-installed the extension, I even uninstalled VSCode and reinstalled everything but the problem persists.
> 
> ```
> Commit: 252e5463d60e63238250799aef7375787f68b4ee
> Date: 2023-05-03T20:09:00.748Z
> Electron: 22.4.8
> Chromium: 108.0.5359.215
> Node.js: 16.17.1
> V8: 10.8.168.25-electron.0
> OS: Windows_NT x64 10.0.19044
> Sandboxed: Yes
> 
> Code GPT v2.1.6
> Published
> 12/25/2022, 07:38:30
> Last released
> 5/7/2023, 17:47:29
> Last updated
> 5/8/2023, 13:05:39
> ```
> 
> UPDATE I found the issue here. It was a new security service on my work laptop which seems to block the API calls. When I temporarily disable the security service the extension acts normal as before.

Can you please write more information about your solution, please
