### ISSUE TITLE
Cannot use it: API key error appeared (Error 401)

### ISSUE THREAD

**Issue by MohammadRaziei** [davila7/code-gpt-docs#77]
I think I entered the wrong API key. but there is no way that I undo it!!!!!

I receive this:

```
OpenAI API Response was: Error 401: Incorrect API key provided: TnPTwUId****************************9FYd. You can find your API key at https://platform.openai.com/account/api-keys. More information about this error: https://www.codegpt.co/docs/tutorial-basics/api_errors
```
 
please help. I uninstall it multiple times and reinstall it again and again. but it never ask me the key again!!

**Comment by davila7** [comment]
@MohammadRaziei 

When you change the API Key, then you must use the "Developer: Reload Window" command

**Comment by MohammadRaziei** [comment]
Yes, I want to change the API key but there is no way to enter it again. I use Developer: Reload Window but it does not ask me again that key. How can I change it? it stock somewhere that I cannot change even by reinstalling the plugin

**Comment by davila7** [comment]
@MohammadRaziei 
if you are using OpenAI your API Key must start with sk-xxxxxxxxxxxx. Please check if you have the correct API Key
