### ISSUE TITLE
Github link for extension is returning 404

### ISSUE THREAD

**Issue by kiranFullStack** [davila7/code-gpt-docs#79]
![Screenshot 2023-03-24 at 1 45 41 AM](https://user-images.githubusercontent.com/40055761/227342119-ea456a76-8bbc-40ed-aecd-74a68c247f24.png)

https://github.com/davila7/codegpt

**Comment by subha1206** [comment]
<img width="918" alt="image" src="https://user-images.githubusercontent.com/36275153/227512377-fe91b7fb-e418-4e9e-aee5-6e0cd22f01c1.png">
Because the repo is not available for public yet. 

Cool work BTW @davila7
