### ISSUE TITLE
OpenAI API Response was: Error 401: Incorrect API key provided

### ISSUE THREAD

**Issue by kittiphone02** [davila7/code-gpt-docs#80]
![image](https://user-images.githubusercontent.com/100832028/227407359-984d84e6-3575-4a73-9fd8-82bdc9136061.png)

**Comment by davila7** [comment]
@kittiphone02
You can fix your problem by reading the following link:
https://help.openai.com/en/articles/6891781-error-code-401-incorrect-api-key-provided
