### ISSUE TITLE
High contrast colors when used with a light theme

### ISSUE THREAD

**Issue by scyleaf** [davila7/code-gpt-docs#83]
Hey, I love the extension so far, and thank you for your work!
I am one of the light theme users, and unfortunately for me the Code-GPT pane looks like so:

<img src="https://user-images.githubusercontent.com/112348148/227577130-8bb293c6-9379-4766-aff5-0ef4637e79d9.png" width=250/>

I assume this happens because the background color for the question boxes is either not set or is picked from the user theme, but the background color for the answer boxes is a set color. Is it possible to set the user question boxes background to a suitable color such that the pane is readable?

**Comment by davila7** [comment]
@scyleaf 
Today we are going to release the update that suits the theme you have configured.
Will be available in version 2.1.2

**Comment by scyleaf** [comment]
I got the update. It works great now! thank you for your work

**Comment by davila7** [comment]
> I got the update. It works great now! thank you for your work

Awesome!
