### ISSUE TITLE
Add possibility to personalize or append abritrary text to the prompts sent to AIs

### ISSUE THREAD

**Issue by TanguySoto** [davila7/code-gpt-docs#84]
For many reasons, mostly being able to personalize our interactions with the models, it would be great if we could always append abritrary text (defined in extension Settings maybe?) to the prompts sent to AIs for each of the commands. 

For example I would always add _"don't add explanation or comments"_ to the `Get Code from comments` command prompts and hence reduce both the cost and reading time of using the command since the response will be shorter.

**Comment by jhklarcher** [comment]
I agree with this.

Sometimes I use CodeGPT for regular writing in Markdown and LaTeX files.

I have noticed that when using GPT3.5-turbo and GPT4 in CodeGPT, the response to any of my prompts in "Ask Code GPT" tends to be a code snippet, probably because it uses a prompt that directs it to write code. Therefore, prompts like "summarize this text" do not aways work.

Being able to use a completely open prompt that does not relate to code could be useful.

**Comment by davila7** [comment]
@jhklarcher @TanguySoto 

Did you try writing through the chat?
https://www.codegpt.co/docs/tutorial-features/chat_code_gpt

**Comment by jhklarcher** [comment]
I tried that, but it seems to open a code snippet box and show it as a comment.

(I set the model to GPT-4)

![image](https://user-images.githubusercontent.com/1714393/228396089-cd907bc5-7640-4a75-bb45-c18d02599c24.png)

**Comment by TanguySoto** [comment]
@davila7 Sure the chat is good but what makes your plugin cool is the other commands! I still think this would be useful for many people when you have time to work on it.

**Comment by PilarHidalgo** [comment]
I understand your need for customization. In CodeGPT, you can personalize the behavior of your AI agents by adjusting the prompts and settings. However, the ability to append arbitrary text to the prompts sent to AIs for each command is currently not available directly in the extension settings.

You can, however, create a new agent in the CodeGPT Plus Playground and customize its prompt to include your specific instructions, such as "don't add explanation or comments". This way, the agent will be trained to follow your specific instructions when generating responses.

Remember, the effectiveness of the agent's responses will depend on how clear and specific your instructions are. For example, you can specify the format of the answers, include examples, and test your prompt with main questions according to your system's goals.
