### ISSUE TITLE
Is it possible to customize the address of the API?

### ISSUE THREAD

**Issue by 1368129224** [davila7/code-gpt-docs#86]
Hi, I'm a Chinese user, due to the famous firewall, the OpenAI API is not accessible in China. I found a way to use Cloudflare Worker to proxy the `api.openai.com`, and it works.

So I would like to know if it is possible to customize the address of the API, for example by using `openai-proxy-api.pages.dev/api` instead of `api.openai.com`.

Thanks!

**Comment by disenone** [comment]
+1

**Comment by PilarHidalgo** [comment]
Hello! Currently, CodeGPT does not support customizing the API endpoint. It's designed to work directly with the official API endpoints provided by the AI model providers such as OpenAI, Microsoft Azure, Google AI Studio, etc. However, your suggestion is valuable and I will forward it to our development team for consideration in future updates. If you have any other questions or need further assistance, feel free to ask!
