### ISSUE TITLE
Can Code-GPT support a custom OpenAI API endpoint?

### ISSUE THREAD

**Issue by riba2534** [davila7/code-gpt-docs#88]
I am a Chinese user, and due to the well-known network firewall, I cannot directly access api.openai.com. I need a reverse proxy to forward requests. I have set up my own reverse proxy server, so I hope Code-GPT can support a user-defined API request address.

**Comment by Kreijstal** [comment]
This is not only nice for other users, but for users who want to log traffic for debugging.

**Comment by disenone** [comment]
+1

**Comment by sallen450** [comment]
+1
