### ISSUE TITLE
Ops! Account problems. More information in the VSCode notification error.

### ISSUE THREAD

**Issue by jbbergy** [davila7/code-gpt-docs#9]
Hi,

I'm trying to use the extension with a "Pay as you go" configured account. I have a newly generated API Key dedicated to the extension. But when i try to use any features, i have the following message :

"Ops! Account problems. More information in the VSCode notification error."

There is no more details in the notifications of VSCode.

I'm working on Windows 10, with WSL2.

**Comment by Ronan-david** [comment]
Hi, I have the same issue, same error message.

I have a free acount but i have 18$ credited on my account, with the graphs showing no usage whatsoever. My acccount is set to be expired on may 2023.

I have opened my chatpgt account on my Chrome website, while trying to use the VSCode CodeGPT app. My default browser is Brave though. 

I have tried with and without my VPN on, but i get the same error nonetheless.

Thanks.

**Comment by davila7** [comment]
In the version that is updated today, you will be able to see the error that the OpenAI API sends directly in the message, and in this way, you will be able to solve it.
The new version is 1.0.10

**Comment by davila7** [comment]
@Ronan-david  @jbbergy 
The new version is now available so you can see the message that comes from the OpenAI API

**Comment by davila7** [comment]
Fixed in version 1.0.12

**Comment by jbbergy** [comment]
thanks, it works well now ;)
