### ISSUE TITLE
Command 'CodeGPT: Set API KEY' resulted in an error

### ISSUE THREAD

**Issue by eparizzi-clevertech** [davila7/code-gpt-docs#90]
![image](https://user-images.githubusercontent.com/121125445/228255978-93849db3-2f0c-48a3-9b48-774eab836cca.png)

Version: 1.76.2 (system setup)
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:55:54.936Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

**Comment by PilarHidalgo** [comment]
To connect with the CodeGPT Playground, follow these steps:

Visit the official CodeGPT Plus website: https://app.codegpt.co/
If you don't have an account, create one. You can sign up using your email or through Google or GitHub authentication.
Once you've logged in, you'll be directed to the Playground. Here, you can interact with agents, configure their behavior, and even share them with others.
Remember, if you choose to log in via Google or GitHub, you must always use the same method to log in.
