### ISSUE TITLE
Command 'CodeGPT: Set API KEY' resulted in an error user interaction failed

### ISSUE THREAD

**Issue by zastrixarundell** [davila7/code-gpt-docs#92]
I tried to set the CodeGPT API key by going to `https://platform.openai.com/account/api-keys`, generating a new key and copying it via CTRL+C and the green copy button and to paste it into CodeGPT with:

`F1` > `>CodeGPT: Set API KEY` > paste > `Enter`.

After that I get the following error:
![image](https://user-images.githubusercontent.com/30195425/228829488-8aca1394-3af4-4b65-81dd-c0c2701089de.png)

This is happening locally and on an SSH connection. VScode is running in a flatpak.

**Comment by salman-it** [comment]
Facing same issue on Fedora 37, VScode flatpak version 1.72.2

**Comment by zastrixarundell** [comment]
Swtiched to a system installation of vscode and that fixed the issue. As the extension is closed source I can't know for sure but probably some form of file can't be read/written to because of how flatpak is sandboxed.

**Comment by jimyhuang** [comment]
Try to kill exists gnome-keyring-daemon process, then the gnome-keyring-daemon success called by flatpak in my environment. And API key can now set without problem.
 
Flatpak will try to start with the parameter like this:
```
ps aux | grep gnome-keyring-daemon
/usr/bin/gnome-keyring-daemon --start --foreground --components=secrets
```

The wrong one on kde default startup were
```
/usr/bin/gnome-keyring-daemon --start
```
