### ISSUE TITLE
"ask a question" sidebar issue when generating answer always scrolls to bottom

### ISSUE THREAD

**Issue by eskruolis** [davila7/code-gpt-docs#94]
I cant get it to stop auto scrolling to bottom every new line which really is disturbing and can not use answers until it fully generates the answer. Also - maybe add STOP GENERATING ANSWER:" button? Thanks!

**Comment by davila7** [comment]
Great, we are already working on the stop button

Thanks!

**Comment by eskruolis** [comment]
Hey!

Is there option or solution to this "I cant get it to stop auto scrolling to bottom every new line which really is disturbing and can not use answers until it fully generates the answer." ?

**Comment by davila7** [comment]
@eskruolis 

We are working on that too

**Comment by mikebouzidis-aurizon** [comment]
I absolutely love the extension but it drives me nuts that I need to manually scroll to the bottom each time to see the answer. Can we have it that it jumps to the bottom once the answer is complete? Or provide an option for auto scroll?
