### ISSUE TITLE
Please enter your api key, go to https://codegpt.co for more information.

### ISSUE THREAD

**Issue by swotwor** [davila7/code-gpt-docs#96]
"API KEY saved. Use the command "Developer: Reload Window". However, after trying to use it, I received the following error: "Please enter your API key. Go to https://codegpt.co/ for more information."

**Comment by davila7** [comment]
Try to completely close VSCode and reopen

**Comment by swotwor** [comment]
> Try to completely close VSCode and reopen

I just haven't tried reinstalling VS Code.

**Comment by swotwor** [comment]
And I forgot to mention, there's a pop-up window on the right with the text "Enter your API KEY to save it securely."

**Comment by Neflux** [comment]
I solved this by upgrading vscode to the latest version (on my Ubuntu 22.04LTS)
`wget 'https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64' -O /tmp/code_latest_amd64.deb
sudo dpkg -i /tmp/code_latest_amd64.deb`

**Comment by swotwor** [comment]
> I solved this by upgrading vscode to the latest version (on my Ubuntu 22.04LTS) `wget 'https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64' -O /tmp/code_latest_amd64.deb sudo dpkg -i /tmp/code_latest_amd64.deb`

Niiiice))) I installed the latest version of VS Code and it worked. It didn't install updates for some reason, and I don't understand why. Thx))

**Comment by Riaun** [comment]
what abt windows

**Comment by VirulentVenom** [comment]
> I solved this by upgrading vscode to the latest version (on my Ubuntu 22.04LTS) `wget 'https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64' -O /tmp/code_latest_amd64.deb sudo dpkg -i /tmp/code_latest_amd64.deb`

Unfortunately doesn't help me. Problem still exist on windows 10
