### ISSUE TITLE
when asking question through command palate it answers entire paragrah in one line resulting not being able to see all andhave to scroll

### ISSUE THREAD

**Issue by samarth-nagar** [davila7/code-gpt-docs#97]
![image](https://user-images.githubusercontent.com/110125971/229344162-ce2b7931-2f22-4b98-bae8-a66294132b89.png)
maybe adding a limit to words in a line will help i dont know where the code but :-
      var maxWords = 15;
      var body = document.getElementsByTagName("body")[0];
      var text = body.innerText;
      var words = text.split(" ");
      if (words.length > maxWords) {
          body.innerHTML = words.slice(0, maxWords).join(" ");
something like this would work

**Comment by davila7** [comment]
I recommend that you use the chat that allows you to add the entire question inside a textarea.

Check this link:
https://www.codegpt.co/docs/tutorial-features/chat_code_gpt

**Comment by samarth-nagar** [comment]
The link is broken
